### ISSUE TITLE
OIO hangs without cursor tracking when restarting with 'clean' state

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1019]
I haven't been able to (re)start online.interlisp.org in any configuration -- it stops and the cursor stops tracking. It won't run xterm or login as guest.

**Comment by nbriggs** [comment]
You can ssh into the underlying EC2 instance.  Does the EC2 instance need to be restarted?
I do see that the "unattended update" recently updated a few things but that doesn't look as though it would have broken anything.

```
Start-Date: 2022-11-09  17:10:53
Commandline: apt upgrade
Requested-By: ubuntu (1000)
Upgrade: ubuntu-advantage-tools:amd64 (27.11.2~20.04.1, 27.11.3~20.04.1), openjdk-17-jre-headless:amd64 (17.0.4+8-1~20.04, 17.0.5+8-2ubuntu1~20.04), mongodb-database-tools:amd64 (100.6.0, 100.6.1), distro-info-data:amd64 (0.43ubuntu1.10, 0.43ubuntu1.11)
End-Date: 2022-11-09  17:11:05
ubuntu@oio:~$ date
Wed Nov  9 19:56:57 UTC 2022
```

**Comment by masinter** [comment]
It said it needed to be restarted so I did that but it didn't cure the problem.
Nor did resetting my init partition.

**Comment by nbriggs** [comment]
Did you restart it about 3.5h ago?

**Comment by nbriggs** [comment]
Looks as though somebody did something... or it just spontaneously recovered.   Try it again now.

**Comment by masinter** [comment]
The problems seem to involve windows update to Microsoft edge and Chrome (but not firefox)

**Comment by nbriggs** [comment]
It had problems with Safari when I first tried it -- the noVNC pane would exit back to the browser with the "start medley ..." screen.  Then it started working, and I had done nothing to it.

**Comment by fghalasz** [comment]
Looks like there is some (newly introduced?) issue with running more than one user at a time on the OIO EC2 instance.  Will work on tracking this down tomorrow (Thursday).  Probably the cause of the erratic behavior you are experiencing.

**Comment by masinter** [comment]
The problem was checking the "View Only" box in the noVNC settings
![image](https://user-images.githubusercontent.com/1116587/201805803-563486ce-b165-4047-9b5d-098e110a25ff.png)

which shouldn't be (what would it mean?)

**Comment by nbriggs** [comment]
It means you get output (view) but cannot send any input -- like keystrokes or mouse movement events.

**Comment by fghalasz** [comment]
Will avoid this issue by removing View-only mode from our customized version of noVNC.

**Comment by masinter** [comment]
the fix is in the recent online.interlisp.org releases.
