### ISSUE TITLE
Greet error when starting up new release

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1022]
The error is when loading MEDLEYDIR-INIT:  "No such medley directory library".

IL:MEDLEYDIR is bound to {DSK}<home>runner>work>medley>medley>

even though (UNIX-GETENV "MEDLEYDIR") returns "/Users/kaplan/Local/medley3.5/release-medley", which is where the sysout and library are located.

**Comment by masinter** [comment]
is this online or a new sysout or ...?

**Comment by rmkaplan** [comment]
run-medley release on my mac

**Comment by fghalasz** [comment]
Fixed in PR#1027
