### ISSUE TITLE
The #, $, %, ^ keys do not work in Online Medley

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1029]
Hitting the  #, $, %, ^ keys (aka the SHIFT-3, SHIFT-4, SHIFT-5, SHIFT-6 keys) do not work in Medley Online.  Pressing these keys is a no-op.

**Comment by pamoroso** [comment]
What's your setup? All of the keys work for me with Online Medley under chromeOS on an ASUS Chromebox 3 with an Italian keyboard.

**Comment by nbriggs** [comment]
I believe Frank fixed this problem in the latest(?) release of online.interlisp.org.
