### ISSUE TITLE
Can't compile with CYGWIN now error 127?

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1041]
```
Larry@TV-PC ~/il/maiko/bin
$ ./makeright x
making so far for cygwin on x86_64.
making with display x releasename cygwin.x86_64-x ldename ldex
start making lde for cygwin.x86_64-x.
clang -m64 -std=gnu99 -fno-strict-aliasing -DMAIKO_ENABLE_NETHUB -c -O2 -g3 -DXWINDOW -DRELEASE=351 -I../inc/ -I../include/ ../src/ldeboot.c -o ../cygwin.x86_64-x/ldeboot.o
make: *** [makefile-tail:187: ../cygwin.x86_64-x/ldeboot.o] Error 127
```

it looks like 
```
Larry@TV-PC ~/il/maiko/bin
$ diff makefile-cygwin.x86_64-x makefile-linux.x86_64-x
```

**Comment by nbriggs** [comment]
Error 127 is probably command not found.  Do you have clang installed? do you have it on your search path?  Perhaps you have gcc instead, in which case you should edit the makefile-cygwin.x86_64-x to comment out the clang line near the top and uncomment the gcc line.

— Nick

**Comment by masinter** [comment]
I'm pretty sure I compiled with clang before, and that I did a loadup without error including makeinit. But I need to go back and see if I saved the makefile-init for cygwin; I haven't seen it.

Running a Medley sysout made on linux but running on cygwin (with a maiko compiled with the D flags fixed I get that the sysout runs, but there is some arithmetic problem -- when I use the background menu Exec/Interlisp it moves the mouse X position far to the right; it's like some arithmetic operation is in error.

I'll work on seeing if there's a simple error that test.vm will show.

**Comment by nbriggs** [comment]
It could be an arithmetic problem with the mouse position from the X server.

**Comment by masinter** [comment]
it might be my configuration. The opcodes diagnosticss I was having trouble getting windows-side WSLg to listen to Windows-side X11 clients .... with two X11 servers with different numbers it kind of works but they could step on each other.

**Comment by nbriggs** [comment]
Try it running the Cygwin lde/ldex speaking back to the X server on your Mac.

**Comment by masinter** [comment]
I haven't figured out how to do that, either. From the mac, ssh -Y just hangs.
From the PC, I can   DISPLAY=larrys-imac:0 (or use the IP address of the imac) but I can't run any X program on the PC; lde fails (with an odd error message) and xclock and xeyes can't open DISPLAY.

![image](https://user-images.githubusercontent.com/1116587/213945705-651a1bdd-292d-4d9c-aff5-2e2b2aa468b0.png)
![image](https://user-images.githubusercontent.com/1116587/213945806-f5738647-3d04-4c59-af78-ff74a10d9908.png)

**Comment by nbriggs** [comment]
On your mac, make sure that your ~/.ssh/config contains, in the host entry for the TVPC,
```
Host tvpc'sname  tvpc's-ip-address
   ForwardX11 yes
   ForwardX11Trusted yes
```
and try again with `ssh -Y tvpc`.   If that doesn't work, if you're trying to open a connect back using the mac's IP address, then you have to have the XQuartz Security options "Authenticate connections" and "Allow connections from network" checked.  You should certainly have at least "Authenticate connections" set (and restart XQuartz) before you try the `ssh -Y tvpc`.

**Comment by nbriggs** [comment]
Also make sure that on the TVPC in the sshd_config file (I don't know where that would be located on a Windows PC; on Unix boxes often /etc/sshd_config) it has an `XAuthLocation xxxx` entry, where `xxxx` is the full path to the `xauth` executable on the TVPC.

**Comment by masinter** [comment]
I can now compile and run with cygwin, if I launch vcxsrv X server first. I can't do a loadup because there is no makefile-init for cygwin, but that isn't really a problem.  The other problems with X and ssh might be a problem if there weren't a lot of work-arounds, but I think I will close this issue.
