### ISSUE TITLE
Add matrix and math functions from Kaisler's Interlisp book

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1054]
**Is your feature request related to a problem? Please describe.**
The book [INTERLISP: The Language and Its Usage](https://interlisp.org/documentation/1986-interlisp-language-book-1.pdf) by Stephen Kaisler contains two libraries of functions not part of the stock Medley system that are useful in common programming situations. The libraries are described in sections 11.4 *A MATRIX PACKAGE* (2D arrays) and 13.7 *MORE ARITHMETIC FUNCTIONS* (stats and complex numbers) of the book.

**Describe the solution you'd like**
I can type in the code in those sections of the book and submit a PR, so that the functions are added to the Medley source tree and ship with the system.

**Describe alternatives you've considered**
Stephen Kaisler may already have the code in machine readable format.

**Additional context**
To practice SEdit and structure editing I'm typing in the functions of sections 11.4 and 13.7 of the book, so I'll have the code in machine readable format anyway.

**Comment by masinter** [comment]
Odd that it isn't in the Interlisp Reference Manual; I don't remember any details of this. It may be that this has been subsumed by Common Lisp?

**Comment by nbriggs** [comment]
Steve's book is based on IRM83. The addition of Common Lisp to the system (somewhere around 1986?) gave us two-d arrays (and complex numbers and so on).  In light of that, I don't think that those matrix functions are particularly useful except as an exercise for you learning to use SEdit and the file package.

**Comment by pamoroso** [comment]
Common Lisp did indeed provide all these features and more. I was thinking the functions in the book might help with remaining in the Interlisp world, but Common Lisp is just a package away and those functions are redundant.

**Comment by nbriggs** [comment]
The Interlisp implementation itself uses Common Lisp functions.  There is no separation between the worlds, though someone wanting to write code that is portable to other *Common Lisp* implementations would want to avoid depending on things in the IL package.

**Comment by pamoroso** [comment]
Okay thanks, if there are no objections I'll close the issue.

**Comment by nbriggs** [comment]
No objections.  As the creator of the issue feel free to close it.
