### ISSUE TITLE
graph edit from SPY -> TEdit doesn't erase lines when it moved around a node

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1055]
we started spy, played around a bit, used shift-select to copy the graph into a tedit document and then edited that graph. 
Moving a node around didn't display right:

![image](https://user-images.githubusercontent.com/1116587/214727907-937436b5-be1c-406e-b6cb-5c724b3b33b0.png)

this is wrong

**Comment by masinter** [comment]
i've tracked this down to a single PR/merge: 
 4efe2
if I checkout 4efe2 or any more recent, and do a loadup I get the error
if I checkout 4fac4 or any older, I don't see the problem.

4efe2 lists me as author, but I think these are @rmkaplan commits? GRAPHER didn't change in this commit. I think the problem is in DRAWLINE (on IMAGEIO).
There's a comment on EDITGRAPH2

![image](https://user-images.githubusercontent.com/1116587/218345733-b036f4d5-a240-425d-a27b-ed80913669d3.png)

Just loading the older IMAGEIO.LCOM doesn't work -- gives errors ... I think this commit changed IMAGEIO.

this is worrisome because it seems like a bug we introduced quite a while ago and just recently detected.

**Comment by nbriggs** [comment]
The IMAGEIO source didn't change for 4fac4..4efe2, but it *was* recompiled.

**Comment by rmkaplan** [comment]
Hmm,

To the best of my recollections, my changes in IMAGEIO, a year or so ago, had to do with external formats, getting the right default character functions in the display file device.  

I vaguely remember an issue with the different drawline implementations, but that may have been pre-github.

Does it work in the Venue sysout?

**Comment by masinter** [comment]
The problem is in the function \DRAWLINE.DISPLAY on ADISPLAY. It has an edit date by rmk the date of the checkin. If I load in from 4fac4e... the source (carefully... using GETDEF and PUTDEF DLD and compiling DLD and then MOVD(DLD \DRAWLINE.DISPLAY) the problem goes away. Note that is necessary to load a record from BIGBITMAP but BIGBITMAP isn't loaded or on Exports.
