### ISSUE TITLE
TEdit crashes when closing window while Character Looks menu open

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1057]
**Describe the bug**
TEdit crashes when closing the window with the `Close` menu option while the Character Looks menu is open, and a break window appears reporting the error `INVALID-ARGUMENT-LIST`. The issue is reproducible.

**To Reproduce**
1. sign into your Interlisp Online account
2. under `Initial Exec`, select `Interlisp`
3. click `Run Medley`
4. right-click the desktop
5. select `TEdit`
6. frame the window
7. middle-click the window title
8. select `Expanded Menu`
9. select `Character Looks`
10. right-click the title bar of TEdit's main window
11. select `Close`

**Expected behavior**
TEdit's window closes with no break or error.

**Screenshots**
The break window:
![TEditCrash1](https://user-images.githubusercontent.com/10342479/215283851-b629c135-ed69-4744-9463-0c10532be2ce.png)

The full desktop:
![TEditCrash2](https://user-images.githubusercontent.com/10342479/215283849-83a8b901-4fd0-48cf-a4c7-196cce76d9bf.png)

**Context (please complete the following information):**
 - OS: chromeOS Stable
 - OS Version: 109.0.5414.94
 - Host arch: x86_64 (ASUS Chromebox 3)
 - Maiko version: not sure how to get it
 - IL:MAKESYSDATE: 18-Dec-2022 20:59:08

**Additional context**
TEdit does't crash if the Character Looks menu is closed before executing the `Close` command of TEdit's main window.

**Comment by rmkaplan** [comment]
Thanks, I have Tedit open on the operating table, I’ll look at it.

**Comment by masinter** [comment]
look at the TEdit and mail files in the test repo in: test/library/TEDIT/hand-aux/
for more test cases

**Comment by rmkaplan** [comment]
I can replicate this behavior running online, but not in a fresh full makesys I build on my mac, on the current master.

The online makesys is dated 18-Dec-22.  Maybe something has improved since then?

**Comment by pamoroso** [comment]
I still get the crash with the x86_64 `.deb` file of the [medley-230130-9ee705b2](https://github.com/Interlisp/medley/releases/tag/medley-230130-9ee705b2) release installed on Crostini Linux, the Linux container of chromeOS.

**Comment by pamoroso** [comment]
The value is `30-Jan-2023 23:32:31`.

**Comment by rmkaplan** [comment]
That's close to the “release” sysout that was just announced, except that the MAKESYSDATE for the one I just downloaded is off by 2 seconds:  30-Jan-2023 23:32:29.  How can there be a 2 second difference in MAKESYSDATE?

But still, I can’t make it fail when I run on my Mac (with or without my personal greeting).  Can anybody else make it fail, other than in Paolo’s configuration?

**Comment by fghalasz** [comment]
Here's the story  Paolo's break happens on the new apps.sysout (which is very similar to the online.sysout).  It does not happen on full.sysout.

Probably this means that some TEdit patch or advice added by Notecards or ROOMS is causing the problem.  I will put in my queue to track this down.

And the two second difference reflects that in the github build workflow, that full.sysosout was built two second before apps.sysout.  Given that apps.sysout is built on top of a completed full.sysout, those are some impressively fast machines at github.

**Comment by rmkaplan** [comment]
Good.  Let me know what the patch is, maybe it is something that should be moved back into Tedit.

**Comment by pamoroso** [comment]
My bad, I miscopied the sysdate and the correct one is indeed `30-Jan-2023 23:32:29`. I confirm the crahs doesn't occur when running `full.sysout` with the `-f` option.

**Comment by rmkaplan** [comment]
Is this still an issue in the Apps sysout?

**Comment by pamoroso** [comment]
The issue is fixed by #1857 so I'm closing this one.
