### ISSUE TITLE
add Interlisp/medley references to Zotero bib

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1066]
The website [Lispm.de](http://lispm.de) archives an impressive and eclectic collection of Lisp documents, some of which of potential interest to the Medley Interlisp project including IRM:
* [LOOPS](http://lispm.de/docs/Publications/AI%20Programming/LOOPS/)
* [Lisp Language Manuals](http://lispm.de/docs/Publications/Lisp%20Language%20Manuals/): various IRM editions (search for `interlisp`)
* [UI](http://lispm.de/docs/Publications/UI/): IRM Vol. 3 (search for `interlisp`), LOOPS primer (search for `loops`)

_Originally posted by @pamoroso in https://github.com/Interlisp/medley/issues/1030#issuecomment-1407458412_

**Comment by Catillamen** [comment]
Added the 1974 and 1978 Interlisp Reference Manuals and disambiguated the 1974, 1978, and 1983 IRMs.
Also uploaded PDFs of these documents, plus Vol 1, 2, and 3 of the Interlisp-D Reference Manual (1985).
For the other things mentioned, verified that the Zotero already included them, and tagged any that weren't already tagged.

**Comment by pamoroso** [comment]
As far as I understand this issue is completed. Can it be closed?

**Comment by pamoroso** [comment]
If there are no objections I'll close this issue.

**Comment by pamoroso** [comment]
@Catillamen Thanks, I'm closing the issue as completed.
