### ISSUE TITLE
Can't make a fuller database:  exports.all and whereis files not found in tmp/

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1068]
I'm trying to crank up again after being "on leave" for a few months.

I have run the loadup-all.sh script to make a full sysout plus exports.all plus whereis.  Those all end up in my working-medley/tmp/ as they used to.

But the loadup-db.sh script doesn't find them there, and so the script fails. It seems to want exports.all in library/, not sure about the whereis database.

Which is not good, because they still may be in an experimental state, as is the makesys attempt, should not override what may have been saved previously.

Maybe tmp/ should be put on the loadup-db directories list?

**Comment by masinter** [comment]
I thought this was fixed a while ago. Not sure if all the cases are covered consistently. SOme points:
1. loadup-db.sh was changed commit 5fea4e6666 to use "-n" (new, from tmp) to run it.
2. loadup-all.sh does all of the loadups AND does a copy-all.sh. which should copy whereis.hash to loadups and exports.all to library (as well as the sysouts to loadups). 

if you look at the October 25 entry d5d21397d4 

>     In order to get this to work it was necessary to change a hack for deciding where to find EXPORTS.ALL and WHEREIS.HASH. Now  if you do `./scripts/loadup-all.sh` to make a full, lisp sysouts, exports.all and whereis.hash it will still build the sysouts in tmp/ but will also "link" new versions in loadups (and library for exports.all). This replaces the previous hack scanning the sysout name for "tmp/".

@fghalasz more recent rework of this might have lost edits? I'm not sure I remember the details.

**Comment by rmkaplan** [comment]
I see what happened.

The problem is that when GITFNS copies an updated executable script to the working directory (a gwc option), it doesn’t copy the executable bit.  (I don’t know how to do that—I’ll create a separate issue for that.)

When I make sure that all of the scripts are executable, by hand, then the loadup-all does put things in the place where loadup-db.sh can find them.

However: loadup-db does not copy/link the fuller.database to loadups/.  I think it should.

(And, I think that when it is done, it should delete the tmp/fuller.sysout.  A lot of storage hanging around with versions accumulating, for no particular purpose—it can be rebuilt in about 5 minutes.)

**Comment by masinter** [comment]
There's an issue #1070 about gitfns not setting execute bit and #1101 about fuller.database files. Closing this one.
