### ISSUE TITLE
Complete configuration of Google Analytics

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#1102]
The Interlisp home page does not implement Google Analytics or any tracking tools.  

The number of unique and return visitors and understanding what pages are visited (or not) could be of value.

[Web Wellness Report](https://github.com/Interlisp/Interlisp.github.io/files/9579292/screencapture-grader-tappnetwork-results-interlisporg-1-2022-09-15-14_49_13.pdf)

**Comment by nbriggs** [comment]
I we do implement tracking, we have to fully comply with the CCPA (and for Europeans, GDPR) regulations.

**Comment by masinter** [comment]
> Once you have your analytics ID, you can enable Google Analytics by adding it to your site’s configuration file. [For details on how to do this, see the Docsy documentation on configuring Google Analytics ](https://www.docsy.dev/docs/adding-content/feedback/)[1](https://www.docsy.dev/docs/adding-content/feedback/). By default, Docsy uses the gtag.js analytics library for both GA4 and Universal Analytics (UA) site tags.

**Comment by stumbo** [comment]
Closed by [PR 106](https://github.com/Interlisp/Interlisp.github.io/pull/106)

I currently have Google Analytics set up using my Google Analytics token.  We can change that if needed.  The tracker listens to do not track and acts accordingly.  I had to enable tracking to verify it worked.  

Here's the real time log from Google Analytics:


![Image](https://github.com/Interlisp/medley/assets/22384842/4fb1acd9-473e-4362-95e4-37bee66a8ca2)

**Comment by masinter** [comment]
shoould we wait until we have an Interlisp.org tag, and analytics on online.interlisp.org ?
