### ISSUE TITLE
Logo for interlisp.org landing page (and many other places)

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1106]
I created some mockups of possible logos to use on the interlisp.org landing page (as well as on the interlisp github site, within Medley itself, on online.interlisp.org, etc.).

### Current landing page and logo
![option0 front page](https://user-images.githubusercontent.com/1251539/190946155-56c5fece-b91f-48ae-a970-e716bb36216a.png)
&nbsp;
### Option 1 (already rejected a while back - but included here for completeness)
![option1 front page](https://user-images.githubusercontent.com/1251539/190946228-0a8c3677-7126-4d7d-bac1-fd80af295758.png)
&nbsp;
### Option 2
![option2 front page](https://user-images.githubusercontent.com/1251539/190946897-5d236dfd-779e-40e7-9993-2968ae9a8af3.png)
&nbsp;
### Option 3
![option3 front page](https://user-images.githubusercontent.com/1251539/190947134-9fa9041e-f50a-4c4e-a836-a4ef90b95ef5.png)
&nbsp;
### Option 4
![option4 front page](https://user-images.githubusercontent.com/1251539/190947157-1a43f746-5042-4844-b754-cfcc8ebdeda5.png)
&nbsp;
### Option 5
![option5 front page](https://user-images.githubusercontent.com/1251539/190947179-7f0ba607-fb7f-409f-8a2d-47959e623044.png)
&nbsp;
### Option 6
![option6 front page](https://user-images.githubusercontent.com/1251539/190947216-449cf417-278a-48f5-95f9-addd52a86bb7.png)
&nbsp;

Comments & votes on any of these options?  I can create any number of variations on these themes - so let me know which features work and which don't and we can go from there.

-- Frank

**Comment by nbriggs** [comment]
I like option 2.  I prefer consistent fonts between “Medley” and “Interlisp” and “Common Lisp” (so “no" to 3, 4, 5).  I don’t like “cute” ellision (option 1).  Option 6 - hmm, I think I prefer to have Medley.

— Nick

**Comment by masinter** [comment]
the designer who did an admirable jobs also delivered some logos which i rejected for trademark reasons 
https://drive.google.com/drive/folders/1w_bMHCOTyDvv_zgum4OAxcBBVcc4Di95?usp=sharing

> 
> LM
> Larry Masinter 07:58 PM
> @ I'm afraid the logo concepts you made seem to use parts of other logos of companies whose software we use -- Docker, GitHub, etc.
> 
> This isn't so good because I think we want a logo that evokes Interlisp as existing before hand..... And secondly, our logo shouldn't contain components of other companies' trademarks.
> 
> LM
> Larry Masinter 08:14 PM
> I''''''lask the team to review
> 

----

**Comment by larsbrinkhoff** [comment]
Someone vectorized this Interlisp book cover.  Here's a PNG version.
![Interlisp](https://user-images.githubusercontent.com/775050/225833348-3e76a26d-3f7c-40e4-88af-aaabd7cf152d.png)

**Comment by larsbrinkhoff** [comment]
I have this printed on a t-shirt.
![Screenshot from 2023-03-17 07-52-54](https://user-images.githubusercontent.com/775050/225833546-ea70923c-0016-4264-b84d-9cb50612cc0f.png)

**Comment by pamoroso** [comment]
I like option 2 but without "+ Common Lisp". This keeps the logo minimal and less busy, which is important when it's small, avoids ambiguities (e.g. is Medley Interlisp + Common Lisp the name of a Common Lisp implementation?), and omits "incidental" details and features (why not Medley Interlisp + NoteCars + ROOMS?).

**Comment by masinter** [comment]
> The 3/4 circle of overlapping windows with the word "Medley" isn't a bad starting point, but some kind of different typeface? Even the figures from the 1984 Interlisp Manual https://github.com/Interlisp/medley/issues/1106#issuecomment-1473262523 might be fun components. The logo need not be serious.

(included URLs to this issue #1108 and also #1106

**Comment by Michele31415** [comment]
On 3/16/2023 11:06 PM, Frank Halasz wrote:
>
> I created some mockups of possible logos to use on the interlisp.org 
> landing page (as well as on the interlisp github site, within Medley 
> itself, on online.interlisp.org, etc.).
>
I like option 2 best.  Italicizing the Lisp part helps set off the word 
Medley.  If I may make a small suggestion, I'd prefer seeing Medley 
nudged left a bit.  This makes the overall visual presentation look more 
balanced (to my eye) and helps emphasize that the "thing" is Medley and 
that it contains Interlisp + Common Lisp.



             - Michele

**Comment by masinter** [comment]
![logo 1](https://user-images.githubusercontent.com/1116587/226037404-2f882edf-c61f-4313-9a44-fb6417dd992b.jpg)
![logo 2](https://user-images.githubusercontent.com/1116587/226037437-017a9690-1be8-4277-a415-be0a11de719b.jpg)
I think Logo 1 is in the right direction, except the little figures actually are little jokes.
Can you guess what they mean, or update them to fit around the 3/4 overlapping windows while retaining 

I love the idea of not taking ourselves so seriously.

**Comment by nbriggs** [comment]
You need to know the jokes before making the logo -- DWIM is catching the sleeping user, the sleeping user by themself without DWIM doesn't make sense.  The figure with the oars lost the "P.A." in their hat when it was darkened, which is important (it being the Programmer's Assistant ?)

**Comment by masinter** [comment]
Just fyi:
Rameela Sharif 02:42 PM
Sounds good! You can let me know if you have any changes for the presentation

LM
Larry Masinter Today 02:26 PM
The talk went well yesterday. There was a lot of editing of the content. The slides I used are at https://docs.google.com/presentation/d/1w_U7GJe0KCLGbjaoj7NjvTWN1_igDqjb/edit?usp=sharing&ouid=106838758956333672633&rtpof=true&sd=true

Perfect! I have your aspirations in mind and will be updating you asap with the changes.



Also, do let me know if you have any more updates



Thanks

LM
Larry Masinter Today 02:35 PM
On the Logo: I think we should try something simple like Logo 1 but without the figures, just a partial circle with MEDLEY inside and "INTERLISP" below and to the right. I think to evoke the "overlapping windows" effect, try to make the top of each rectangle a little thicker. I like the shape of the curve (not quite a circle). One requirement we have to use the logo in the Medley system itself is that it renders reasonably in Black and White 1 bit per pixel, 72 pixels/inch. That seems likely with the simple typefaces you've chosen but it would be good to verify.

LM
Larry Masinter 02:46 PM
I went ahead and paid milestone 2. ... I think the new logo draws on the old but is refreshed with a designer's eye

**Comment by johnwcowan** [comment]
LGTM
