### ISSUE TITLE
Side task bar demo video nits

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1126]
regarding https://youtu.be/iY10VFhaTVI

You might want to start medley with a smaller window to make sure the video is legible when displayed.

Each stage of image adjustment intoduces more "noise".

The reason for the side task bar wasn't to make it more modern. It was a necessary element in running online. The Side task bar doesn't exist in most current installations. 

The use of a text editor to make a file isn't really part of the "Interlisp experience" either.
You should make text files using TEdit and writing out as 'plain text'.

Medley thinks it owns the file system and all of the files, or it can work with a remote file system too.

Showing extra keys ... isn't quite "accessibility". 

Copy/paste is a separate feature
I think "remote resizing" is preferred

**Comment by masinter** [comment]
we should talk about the purpose of the demos. There's an element of showing people what it was  like, to have their entire environment in Lisp. There was no other shell, editor outside of lisp. 

There were problems but also some advantages to this paradigm, but let's not emphasize "going outside" Lisp as our first demo.

**Comment by Michele31415** [comment]
On 4/7/2023 7:48 PM, Larry Masinter wrote:
>
> we should talk about the purpose of the demos. There's an element of 
> showing people what it was like, to have their entire environment in 
> Lisp. There was no other shell, editor outside of lisp.
>
> There were problems but also some advantages to this paradigm, but 
> let's not emphasize "going outside" Lisp as our first demo.
>

I always thought one of the coolest things about Interlisp-D was how 
easy it was to do graphics.  Try this:

(SETQ DEMOW (CREATEW))
(FOR I FROM 1 TO 1000 DO (BITBLT (SCREENBITMAP) LASTMOUSEX LASTMOUSEY 
DEMOW 100 100 50 50) (DISMISS 20))

Then wander the mouse around the screen and see its neighborhood appear 
in the window as you go.  One line, done.  How much C code would that take?

             - Michele

**Comment by masinter** [comment]
I have in mind a kind of "self-propelled demo": write down in a TEdit file the steps
---
1. Create a window. It will ask you to draw out a shape  
```
   (SETQ DEMOW (CREATEW))
```
2.  Try copying some of the screen to that window
```
  (BITBLT (SCREENBITMAP) LASTMOUSEX LASTMOUSEY DEMOW 100 100 50 50)
```
3. Do it 1000 times, waiting a few milliseconds
```
   (FOR I FROM 1 TO 1000 DO
    (BITBLT (SCREENBITMAP) LASTMOUSEX LASTMOUSEY DEMOW 100 100 50 50)
    (DISMISS 20))
```
4. Move your mouse around.
---
where each code segment above will just stuff the expression into the input buffer of an Interlisp Exec window except for the last (maybe move the mouse for them if they don't respond.

If you want to do a video, just link to a short segment which shows the whole thing.
But if you're running the demo in a Medley... they can play and know what to expect.

**Comment by RonVin-AspIII** [comment]
@masinter 
Just tried the above code with CREATEW - it is very cool! Would you like me to add this in one of our videos?

Also, going along with what Larry said, we'll also aim to put in a little context about Lisp and Medley and their features at the beginning of the demo, other than addressing the nits above.

**Comment by hjellinek** [comment]
This is obsolete.
