### ISSUE TITLE
Ideas for reorganizing web site

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1127]
These seem like good suggestions; and we're not too far but might be able to use the advice:

> Home Page: The home page should provide an introduction to the project and its history. It should also highlight the key features of the project and provide links to the most important pages on the site.

We have too much in the current home page that belongs in other pages.

>  About Page: The About page should include a brief history of the project, its mission statement, and its goals. It should also include information about the development team, any academic or corporate partners, and the project's governance.

Some topics missing or not clearly stated. So this is a good take.

> Documentation Page: The Documentation page should provide detailed technical documentation for the project, including installation instructions, usage guidelines, and API documentation. It should also provide links to any related publications or research papers.

I think this transformation is underway. 

> Blog Page: A blog page can be a useful way to communicate new developments, share tutorials or insights, and create engagement with your user community.

probably better to cast our "News" as a blog, with the implication of material being dated.

> Gallery Page: If the project involves visual output such as images or videos, consider creating a gallery page to showcase this material in a visually appealing way.

The screenshots can remain in the medley pinned Discussion, but the web site, youtube and other elements could be referenced.

> FAQ Page: A frequently asked questions (FAQ) page can be a useful way to address common user questions and concerns in a standardized way.

We can set one up. We might need to wait until more Questions are Asked.

> Contact Page: The Contact page should provide information on how to get in touch with the development team. This can include a web form, contact information, and a FAQ section addressing any common questions or concerns.

The Jasper AI has FAQs in two places -- Bad Robot Bad.

**Comment by phantomics** [comment]
Most of this is resolved in changes I've made; I'll address the remaining items and close this.

**Comment by phantomics** [comment]
These are all addressed now to my knowledge.
