### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1128]
A few points:
1. The 1985 entry "Koro INTERLISP-D RELEASE NOTES" is actually the Lyric release "Xerox Common Lisp Implementation Notes" document.
2. The 1989 entry for PepPro (I'm co-author) link is broken. The AAAI no longer has any of the proceedings of the IAAI 1989 conference (or any IAAI before 2010). I have a pdf (scanned, saved from the AAAI site some time ago) of the paper, but AAAI technically holds the copyright to it, so I don't know about making it public.
3. The 1986 SpinPro paper that's in Zotero, is not in this Bibliography. The PepPro paper references SpinPro, as they share the MP expert system development environment (built on Interlisp-D/Common Lisp). I have a pdf (scanned) of this paper, also. In this case the copyright is held by the American Chemical Society. The link in Zotero goes to the ACS site which has the abstract but requires payment for the full text. ($40 for 48 hours access. Presumably the access is not in a download/savable format, to enforce the 48-hour time frame.)
4. I thought that would try to directly edit the page to add the basic information for the SpinPro paper to this page but noticed that it was generated. So, I cloned the repo, modified the update_bibliography.sh to capture the unsorted JSON items to a file, and I saw that the SpinPro entry **IS** there. HOWEVER, in that entry, the URL key is in lowercase, so I suspect that may be related. _Also_, the `.data.date` formats are different, but the PepPro entry date is in the less-standard format! ("March 28–30, 1989" PepPro vs. "1986-04-30" SpinPro).

**Comment by MattHeffron** [comment]
I have what **_seems_** to be a fix for the point #3 in my comment above.
It's a change to the call to jq where it is merging the sorted and mapped json into a single json object.
I do not have permission to push a branch with the changes to GitHub (and so cannot create a Pull Request).
I can send the _one_ file to someone if they want to do it.

Matt

**Comment by nbriggs** [comment]
@MattHeffron - until we get the permissions right, you can fork the repo, push a modified branch to your fork, and then generate a pull request for your new branch to be merged back into the main repo.  I do this frequently for projects that I don't have write access to.

**Comment by Catillamen** [comment]
Found that there were two "XEROX COMMON LISP IMPLEMENTATION NOTES" in Zotero -- made sure we had all the good stuff on one and marked the other for removal. They're basically identical, and I only tagged the non-removal-marked one.
Though, question about that particular document: the title, of course, references Common Lisp, but isn't Lyric an Interlisp release? Is there some overlap here I'm not aware of?
Also, I realize I somewhat preemptively changed this to done, since I have no idea about the status of concern 4 above. Changing things back to In Progress for now.

**Comment by Catillamen** [comment]
Fourth issue needs to be separated into an implementation issue rather than bibliography issue. Otherwise, seems handled.

**Comment by masinter** [comment]
looking at this again, I'm not sure what, if anything, has to happen to deal with item 4.

@MattHeffron could you please review and file a new issue if more has to happen to satisfy; I am closing this issue.

**Comment by MattHeffron** [comment]
> looking at this again, I'm not sure what, if anything, has to happen to deal with item 4.
> @MattHeffron could you please review and file a new issue if more has to happen to satisfy; I am closing this issue.

I had forgotten about this issue. I fixed it some time ago.
