### ISSUE TITLE
"What People Are Saying" needs way of submitting references, including ycombinator link in message

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1129]
> 
> 	
> gumby 26 days ago | next [–]
> 
> Many people who read about Lisp Machines are not aware that the InterLisp-D world and the MIT world (CADR, LMI, Symbolics etc) had significantly different approaches to how the systems should work, so even if you have read or used the MIT-style systems you will learn a lot by using Medley. I came from MIT out to PARC for a year, and later moved CYC from D machines to Symbolics machines (a complete reimplementation using a different fundamental architecture) so have good experiences with them both.
> At heart, the InterLisp language itself isn't that different from MIT lisps, as Interlisp started down the road at BBN and there was a lot of cross fertilization in both directions. And CommonLisp, while heavily based on the "MIT" model has a lot of Interlisp influence in it.

I'd like to try to capture this kind of commentary, in a more systematic way. I think Zotero will archive copies and we can excerpt a quote and point at the original https://news.ycombinator.com/item?id=34300806#34303580 

I suppose we should use a more neutral tone than "testimonial" -- "testimonals and critiques" or just "discussions"?

**Comment by masinter** [comment]
I think this fits better as a Discussion topic rather than on the web site, because people say things almost daily... and you don't really need the same kind of version control.

**Comment by stumbo** [comment]
Closed -- Blog posts are captured on website.  We have a link for submitting new posts.

**Comment by masinter** [comment]
when I went to Interlisp.org I couldn't find "What People Are Saying". Is it indexed? In the outline?

**Comment by pamoroso** [comment]
Isn't [this](https://interlisp.org/medley/about/comments) the *What people are saying* page?

**Comment by masinter** [comment]
That's the page. But I couldn't find it using "search" or looking in the index on the left. 

it might be nice to have this form or an option on it to submit things to the bibliography through Zotero. 

>
