### ISSUE TITLE
Interlisp web site nits

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1130]
Going through issues, things I don't know how to fix:

- [x] The home page has 3 "Interlisp"s, one smaller in faint grey, a bigger one, and one in the logo (and another in the text just below)
- [x] I wasn't sure about the LICENSE. We're using MIT for the code. Is Eclipse better? There's a top level LICENSE and a content/en/license.md -- which is intended?
- [x] I'm not quite sure about the deployment actions? Do we just push to main branch? To gh-pages? The main content is in content/en. What are assets, data?
- [x] case of file names: does Hugo match up names or is it case-exact.
- [x] how do I do intra-site links?
- [x] in content/en/about/_index.md there's a comment about php. We're not using php?
- [x] there were a lot of pointers to documents in the former "docs" directory. I'd to serve them (and a number of old PDFs, is that the way to do it?

**Comment by phantomics** [comment]
These items are complete.
