### ISSUE TITLE
Documentation section of website

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1131]
All of the files in the Medley PDFs folder in the shared Interlisp Google Drive should be linked to the web site and served from there. these probably need organization into "of historical interest" and "current and revisable".

**Comment by masinter** [comment]
This is in the /software/using/  part. It isn't complete (Paolo's inventory in Zotero would be a good start) it's along the way.

**Comment by pamoroso** [comment]
How can I help with this? What should be done in practice?

**Comment by masinter** [comment]
I think of this as an engineering task: we need to clear the road from not-knowing medley to knowing,  and remove boulders and fill potholes, using the resources available.

Some things we can fix, and others we can document and provide warnings and the route around.

* assess the material we have -- what documents, website material, youtube videos are there, and what shape they are in? IRM, Steve's books, User guides, Primers, The LispCourse notes? Blake's guide, Keystrokes.md?
*  What can be done within available constraints? We can't (re)write large reference material but perhaps start with an overview of available documentation, caveats (things to watch out for) ... 

* organize some friends to help? People are willing to contribute when they know their contributions will be used and appreciated and the task is small enough. 

Let's go through the "Documentation" issues/discussions ... make sure they're really documentation issues.

**Comment by pamoroso** [comment]
A possible way of implementing this engineering approach is to start charting a path through the existing documentation resources.

The path would recommend an ordered list of resources to pursue to arrive to a first stop and gain an introductory understanding, as well as an additional list to proceed to another stop for an advanced understanding.

The path would assume the form of a page or section somewhere under the subtree of the project site on using Medley. It would list the resources and explain for each what the user gains, the parts that may be skipped, any limitations or issues, and so on.

Then we could fill the potholes by adding more itineraries, updating the resources in the lists, producing new documents, and so on.

I can take care of charting the path. As for the issues and discussions tagged `Documentation`, I can help review them.

**Comment by masinter** [comment]
Start with https://interlisp.org/software/using-medley/

```
git clone https://github.com/Interlisp/Interlisp.github.io
cd Interlisp.github.io/content/en/software/using-medley/
```

**Comment by pamoroso** [comment]
I submitted [PR 192](https://github.com/Interlisp/Interlisp.github.io/pull/192) with the draft of the new section *Getting started* of the page [Using Medley](https://interlisp.org/software/using-medley). The section contains two reading lists of documentation resources as [proposed above](https://github.com/Interlisp/medley/issues/1131#issuecomment-1852843877).

**Comment by pamoroso** [comment]
In my [PR](https://github.com/Interlisp/Interlisp.github.io/pull/192) I wanted to link to the site page [The Basics of Interlisp](https://interlisp.org/software/Using.html) with this code:

```
[The Basics of Interlisp](Using)
```

But the link is broken and leads to the 404 error page `https://interlisp.org/software/using-medley/Using`. What's the correct Hugo syntax for linking to that page?

By the way, all the links in section [Exported Medley Documentation](https://interlisp.org/software/using-medley/#exported-medley-documentation) on the same page are similarly broken.

**Comment by stumbo** [comment]
Try replacing (Using) with (/software/Using.html) this will match what we explicitly said the page address should be:

---
title: The Basics of Interlisp
url: /software/Using.html
type: docs
weight: 2
---

That will get it referencing the right location.  I'm not sure why we put the url: in The Basics of Interlisp page, so I don't want to remove it.

**Comment by stumbo** [comment]
Moved my original comment to the [PR](https://github.com/Interlisp/Interlisp.github.io/pull/192) and reclosed...
