### ISSUE TITLE
thoughts on new web site

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1133]
- [x]  Contact Information: did you decide to drop the Wikipedia link? Should we link to [info@interlisp.org](mailto:info@interlisp.org) instead or in addition to the Interlisp Google group? We don't use that mailing list consistently. There's the Libera Chat IRC and Twitter @interlisp8 handle too.
- [x] What is Medley Interlisp? We spent the most time wordsmithing this for the announcement that was glossed over. But I mainly like the wording https://www.softwarepreservationnetwork.org/Interlisp/ I especially like the point that we're not done and would like others to help (which disclaimer belongs on the online site). The part about joining SPN belongs in the organizational partners part of the website, though.
- [x] (maybe the part about the 'canonical' structure editor goes away, but there are three structure editors: the TTY editor, which I still find useful, and DEDIT (in the library) which is superseded by SEDIT but still interesting. And you can think of the "file package" as a consequential part of "structure editing".  The quote from "What have we lost?" is an interesting perspective but isn't really supportable. It's fine to quote misconceptions but not as a lead. 
- [x] Logo - we need a better logo. The alt text should say it's a 3/4 (not half-) circle of
 overlapping windows (not screens).
- [x] Documentation -- again this is an area where I think we've made great headway but it still isn't in order. Maybe "for review and update" instead of "available"?

- [x] some of the wiki pages were outdated and we need to update them. for example, the ongoing projects became the 2021 annual report and we haven't published project news since March.
- [x] The organization should bring together things for
 * people who want to learn about Interlisp but don't want to use it
* people who are interested in the project and group but don't care about the system
* people who want to use or try out or modify things
I want to keep the word "Documentation" to be the latter -- no history there except in passing.

- [x] The Running section should be ordered by ease:
* Online
* Docker
* Install from release
* Building Maiko
* Building loadups
with platform specific advice for Windows, Mac, Linux, Android  that mainly just link to the first five sections.

- [x] I want to do more recorded demos of different parts of the system. I've been doing "Issue Roulette" and recording the sessions like @ecraven asked for, but having someone watching and asking questions would be better.

- [x] "Cool URLs Don't Change" was Sir Tim's slogan. I'm sure there are
 links search engines that point to files and pages that no longer will exist.

I'm willing to say that our current URL's aren't cool. I don't think there's a way to get 404 logs of URLs we no longer serve, but perhaps a custom 404 page? See Creating a custom 404 page for your GitHub Pages site - GitHub Docs
. We could plead for people where to look?

I hate to lose history but I have a copy in my clones of older [Interlisp.github.io](http://interlisp.github.io/) repo contents... so we can put off doing anything about that.
I'd say just go for it, 

- [x] please put a header on the home page with the same "Web Site In Transition" and asks people to report problems. [info@interlisp.org](mailto:info@interlisp.org) or an issue here.

**Comment by phantomics** [comment]
After some research on Hugo/Github deployment, it appears it may not be possible to set up 301 redirects when hosting on Github pages:

https://discourse.gohugo.io/t/how-to-configure-301-trailing-slash-redirect-for-github-gitlab-pages/29604/3
https://discourse.gohugo.io/t/how-to-return-301-moved-permanently/16734

To make the old site's URLs permanently redirect we may need to change hosting.

**Comment by stumbo** [comment]
I believe that is correct, there are two possibilities:
- Rehost.  I believe netify supports easy deployment of hugo and 301 remapping.  They are fairly tightly integrated with the hugo ecosystem. 
- Continue with the existing strategy of putting `alias` information in the yaml headers to capture redirect information.  

I've taken the latter approach and used Google Analytics information to identify inbound links that need redirecting.

**Comment by masinter** [comment]
I asked bing copilot to explain: 
```
{{ define "main" }}
  <main id="main">
    <div>
      <h1 id="title"><a href="{{ "" | relURL }}">Go Home</a></h1>
    </div>
  </main>
{{ end }}
```

---

and it replied

---

This is a Hugo template for a custom 404 page. Let's break it down:

- `{{ define "main" }}` and `{{ end }}`: These lines define a new Hugo template called "main". Everything between these lines will be included wherever the "main" template is used in your Hugo site.
- `<main id="main">` and `</main>`: These lines define a `<main>` HTML element with an ID of "main". This is where the main content of your 404 page goes.
- `<div>` and `</div>`: These lines define a `<div>` HTML element. This is a generic container for other HTML elements.
- `<h1 id="title"><a href="{{ "" | relURL }}">Go Home</a></h1>`: This line defines an `<h1>` HTML element with an ID of "title". Inside this element, there's an `<a>` HTML element, which is a hyperlink. The `href` attribute of the hyperlink is set to the relative URL of the home page of your Hugo site. The text of the hyperlink is "Go Home".


So, when a user visits a page that does not exist on your Hugo site, they will see a 404 page with a heading that says "Go Home". If they click on "Go Home", they will be taken to the home page of your site. This is a simple and user-friendly way to handle 404 errors. You can customize this template to suit the needs and style of your site. For example, you could add more information about why the user is seeing the 404 page, or include links to other important pages on your site. Remember to rebuild your site after making changes to your templates so that the changes take effect.

---

and suggested

> Can you show me how to add more information to this template?

and selecting that

---

Sure, you can add more information to your 404 page by adding more HTML elements to the template. Here's an example of how you could modify your template to include more information:

```html
{{ define "main" }}
  <main id="main">
    <div>
      <h1 id="title">Page Not Found</h1>
      <p>The page you were trying to reach does not exist. It might have been removed, had its name changed, or is temporarily unavailable.</p>
      <p>Please check the URL for typos or visit our homepage.</p>
      <a href="{{ "" | relURL }}">Go Home</a>
    </div>
  </main>
{{ end }}
```

In this modified template, I've added two `<p>` elements with additional information for the user:

- The first `<p>` element informs the user that the page they were trying to reach does not exist and provides some possible reasons why this might be the case.
- The second `<p>` element suggests some actions the user can take, such as checking the URL for typos or visiting the homepage.

Remember to replace the content of these elements with your own custom messages. After you've made these changes, make sure to rebuild your site so that the changes take effect. This will provide a more informative and user-friendly experience for visitors who encounter a 404 error on your site.

**Comment by masinter** [comment]
Looks to me that all of these issues have been addressed.
