### ISSUE TITLE
w3c link checker reports

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1134]
I ran the link checker again depth 5 and found these problems
2021 Annual Report. It's harmless to fix broken links 
- [x]  Lines: 389, 390 https://interlisp.org/documentation/interlisp-books.md 404. This was from the wiki or gitbook? There's a interlisp-books.md in the gitbook/wiki translations but it isn't very useful.
- [x] Meeting Agendas and Notes is a broken link because (I think) it's not settled how to do them.
- [x] There were gitbook inserted mysteriou hyperlinks ` <a href="#_nixrj1smqrtw" id="_nixrj1smqrtw"></a>` -- they seem to be a gitbook artifact and should be removed.
- [x] it would be good to redirect incoming URLs looking for something in the former 'docs' directory to look instead in 'documentation'.
- [x] The bibliography has lots of links to the publication site that give a 302 error redirect to a 403 Forbidden. 83 links.  @AbeJellinek can you help?
- [x] the bibliography has some pretty funky URLs -- google searches and so forth. Those should be cleaned up.

**Comment by stumbo** [comment]
@masinter  -- re: it would be good to redirect incoming URLs looking for something in the former 'docs' directory to look instead in documentation.    I've completed this task for the documents that currently reside in `documentation`.  There are many other in the old `docs` folder.  Is  it worth moving these forward into the new web site?  

It looks like the remaining bibliography issues are `doi.org` links redirecting to a paywall.  Once membership is validated you pass through to the correct paper.

**Comment by masinter** [comment]
i don't know how hard it is to set up the redirects or whether there are other costs.
Setting up a 404 page that tells people to search or report problems might be just as good. Your call.

**Comment by stumbo** [comment]
Added [Issue 1252](https://github.com/Interlisp/medley/issues/1252) to Bibliography section for fixing 'funky URLs', searches, etc.

**Comment by phantomics** [comment]
As per [this document](https://gohugo.io/templates/404/) I've added a [404 page template](https://github.com/phantomics/InterlispDraft.github.io/blob/main/layouts/404.html) but it doesn't seem to display.

**Comment by stumbo** [comment]
Try using the following for your 404.html page:
```
{{ define "main" -}}
<div class="td-content">
	<h1 id="title"><a href="{{ "" | relURL }}">Go Home</a></h1>
</div>
{{- end }}
```

This syntax works on my machine.  I just borrowed what docsy uses for a [404](https://github.com/google/docsy/blob/main/layouts/404.html) and swapped in your header.
