### ISSUE TITLE
The URL for 'Create Documentation Issue" 

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1140]
I can't find where the "Create documentation Issue" that shows up when my window is wide -- where is it? `grep -lri "create documentation issue"` doesn't help, nor does searching for parts of the URL that's there.

Now to create a documentation issue, you can do

 `https://github.com/interlisp/medley/issues/new?template=documentation.md&projects=Interlisp/medley/5`

The CSUCI students are going to take on the bibliography.  I split the 'documentation' label into projects: website and bibliography

**Comment by stumbo** [comment]
The **Create Document Issue** link is generated by Hugo/Docsy and is derived from line 162 of the `config.toml`
```
github_repo = "https://github.com/interlisp/Interlisp.github.io"
```

I assume there is some way of customizing the link, but it'll take a little rooting around in the Docsy documentation to figure it out.

**Comment by stumbo** [comment]
Closed with the merge of PR Issue_1140
