### ISSUE TITLE
SVG/PNG versions of logo:  where to keep them.

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1160]
The svg/png versions of the logo are ready.  They need to be used by a variety of "repos" including online, interlisp.github.io, the new launcher app, the github site, etc.

Question is where to keep them.  They should be under version control - i.e., in githiub.  But what repo?

Proposal 1:  Create new repo "Assets" (or "Resources") and keep the logos in the "logo" directory under there.  

Proposal 3: Rename the current "Utilities" repo to be something like "Common", put the current contents of Utilities one directory down in a "Utilities" directory and add a "logo" directory to this repo.

Wherever we store the logos, eventually the favicon and the iconsets created from the logo should be stored in the same place - so that all apps/online sites use the same logos/icons.

Thoughts?

**Comment by masinter** [comment]
> Proposal 3: Rename the current "Utilities" repo to be something like "Common", put the current contents of Utilities one directory down in a "Utilities" directory and add a "logo" directory to this repo.
👍🏽

**Comment by fghalasz** [comment]
OK.  Done.  Repo Utilities is now repo "Common".  It has been rearranged with utilities and assets directories.  Under assets is logo and icons.   Populated it with new logo svgs and pngs.  Populated it with one icon - favicon - with more iconsets to follow.
