### ISSUE TITLE
FONT NOT FOUND error when inserting equation with integral in TEdit

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1175]
**Describe the bug**
After loading the EQUATIONS LispUsers module into Interlisp Online, when I insert an equation with an integral in TEdit I get a break window with the `INTERLISP-ERROR` error `FONT NOT FOUND (coerced to) (SIGMA 20 (MEDIUM REGULAR REGULAR) 0 DISPLAY)`.

**To Reproduce**
1. sign into your Interlisp Online account
2. under `Initial Exec`, select `Interlisp`
3. click `Run Medley`
4. at the Exec, evaluate `(FILESLOAD EQUATIONS)`
5. launch TEdit
6. from the middle-button menu, select `Equation`
7. select `integral`

**Expected behavior**
TEdit prompts to enter the components of the integral.

**Screenshots**
The break window:
![tedit-equations-break](https://user-images.githubusercontent.com/10342479/233851679-47741dd0-0190-4382-a46f-47412f26c6cd.png)

The full desktop:
![tedit-equations](https://user-images.githubusercontent.com/10342479/233851688-d76f1597-c17b-409a-ad44-c804ae8abacb.png)

**Context (please complete the following information):**
 - OS: chromeOS Stable
 - OS Version: 112.0.5615.62
 - Host arch: x86_64 (ASUS Chromebox 3)
 - Maiko version: not sure how to get it
 - IL:MAKESYSDATE: 22-Apr-2023 13:37:34

**Additional context**
The issue has been occurring since at least the 18-Dec-2022 20:59:08 build.

**Comment by nbriggs** [comment]
The "other" font directory, containing the SIGMA font (and some others) doesn't appear to be in the file system visible to Medley.  We have the fonts, I would guess it's a function of what's being built into the Docker images.

**Comment by fghalasz** [comment]
The Medley Docker images (including online) are built from the release tars.  What's included in the release tars was set a long time ago and hasn't been updated in. At least the last year and a half. I will look into adding the extra fonts file into the release tars.  Should be an easy fix.

**Comment by rmkaplan** [comment]
Fixed at least iin #1857 if not before
