### ISSUE TITLE
odd black blobs in TEdit expanded menu

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#120]
![image](https://user-images.githubusercontent.com/1116587/103423851-ef136700-4b5d-11eb-9f15-7a95a4e033d4.png)

**Comment by nbriggs** [comment]
What sysout was this in?

**Comment by masinter** [comment]
it happens with the latest xfull35.sysout (and it's been there for a while)
![Screenshot 2020-12-31 150301](https://user-images.githubusercontent.com/1116587/103430502-a9fd2e00-4b79-11eb-88b2-4b9d302fe853.png)
and doesn't occur in full.venuesysout. I bet they are LF's in some file that was checked in without
git config autocrlf never
