### ISSUE TITLE
Suggestion for text on Using Medley page

### ISSUE THREAD

**Issue by KathrynLA** [Interlisp/medley#1226]
I think we need to explain here what the user needs to know about:
- The difference between running and building Medley
- Which option is easiest for a beginner/non-programmer
- Why there are so many options and how they differ

**Comment by pamoroso** [comment]
The project site no longer covers building Medley from source. So I recommend adding a short note to the [Software](https://interlisp.org/software/) page to explain the difference between installing locally and accessing Medley online. The remaining options differ only in the operating system the installers are for and therefore seem self explanatory.

I can take care of this.

**Comment by pamoroso** [comment]
I submitted these changes as [PR #206](https://github.com/Interlisp/Interlisp.github.io/pull/206).

**Comment by pamoroso** [comment]
[PR #206](https://github.com/Interlisp/Interlisp.github.io/pull/206) was merged, which resolved this issue.

**Comment by masinter** [comment]
THere is also some documentation about building the sysouts using scripts. This isn't documentEd on the web site but rather in the medley and maiko repositories in their READMEs.

https://github.com/Interlisp/medley/pull/1507/files

needs review and approval or else making some transition from one to the other.

**Comment by pamoroso** [comment]
I shared [my feedback](https://github.com/Interlisp/medley/pull/1507/files) on PR #1507. Other than that it looks good to me.
