### ISSUE TITLE
Suggestions for Running Medley Interlisp web page

### ISSUE THREAD

**Issue by KathrynLA** [Interlisp/medley#1227]
Under Interlisp Online, it says see caveats. But there is no link to caveats. How do I know what they are?
What is a Docker Container?
What is the difference between running Medley in a Docker Container or running in Windows?
How would the user know which version to use?

**Comment by pamoroso** [comment]
Medley Online and the project site no longer mention caveats and Docker, which eliminates the ambiguity and the need to take a decision. Therefore I'll close this issue.
