### ISSUE TITLE
Incomplete tax id/registered charity numbers in Interlisporg entry on vocabulary page

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1230]
**Errors happen. Please tell us the URL**
https://interlisp.org/medley/project/vocabulary/

**What does it say?**
A California-registered non-profit organization (DBA Interlisp.org) Established August 2021. 501c3 EIN 87xxxx California registered charity NNNNN.

**What should it say?**
The "xxxx" and "NNNNN" should reflect the actual ids, or this sentence should be removed.

**Comment by stumbo** [comment]
Fixed by [PR #91](https://github.com/Interlisp/Interlisp.github.io/pull/91)
