### ISSUE TITLE
Vocabulary page: DLISP, sentence mangled

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1231]
**Errors happen. Please tell us the URL**
https://interlisp.org/medley/project/vocabulary/

**What does it say?**
DLISP
By Warren Teitelman: a first attempt at building a “Display” (GUI) with Interlisp running on Maxc (A PDP-10 clone a Xerox Alto as a graphics terminal connected to it via Ethernet).

**What should it say?**
DLISP
By Warren Teitelman: a first attempt at building a “Display” (GUI) with Interlisp running on Maxc (A PDP-10 clone) using a Xerox Alto as a graphics terminal connected to it via Ethernet.

**Screen shot**

**Comment by stumbo** [comment]
Fixed by [PR #93](https://github.com/Interlisp/Interlisp.github.io/pull/93).
