### ISSUE TITLE
Vocabulary entry for Common Lisp - inappropriately bulleted list

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1232]
**Errors happen. Please tell us the URL**

**What does it say?**

Common Lisp
The subject of a 10-year standards process to converge multiple dialects of the

- Lisp language.
- Strong influences from many Lisp dialects, including Interlisp.

**What should it say?**
Common Lisp
The subject of a 10-year standards process to converge multiple dialects of the Lisp language.  Strong influences from many Lisp dialects, including Interlisp.

**Screen shot**
![image](https://github.com/Interlisp/medley/assets/8138841/a520fc9e-9aca-4512-aa06-3cae4df793c3)

**Comment by stumbo** [comment]
Fixed by [PR #92](https://github.com/Interlisp/Interlisp.github.io/pull/92)
