### ISSUE TITLE
Status reports (like "Annual Reports") make more sense than calling it "History"

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1233]
**Errors happen. Please tell us the URL**
https://interlisp.org/medley/history/medley_history/

**What does it say?**
It calls it "History" and Medley_History

**What should it say?**

 I think we should distinguish between "History" (things tjat happened before 2000) and things that happened starting in 2020 (assuming that nothing significant happened between 2000 and 2020).  
The "Annual REports" and the video for BALISP are examples of Project Status Reports.  A link to the closed/merged issues and pull requests would be a useful link.

**Screen shot**

**Comment by stumbo** [comment]
[PR 96](https://github.com/Interlisp/Interlisp.github.io/pull/96) adds a Status section to the Project documentation and seeds it with the annual reports.  I've also added in the Bay Lisp Conference video and a link to the GitHub Issues page that filters to closed issues.
