### ISSUE TITLE
web site nits still

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1239]
URL: Landing page https://interlisp.org

- [x] Repeats "Medley Interlisp Project" and "Medley" at the top, in the logo, and in the next page section head. It might need more than 1 but not 5.
- [x] Graident Notecards screensnap panel makes text above it hard to read.  The words "INTERLISP" and "COMMON LISP" are illegible, but also other text. Making the font of white text larger might help, or darken the image more? 
- [x] The vocabulary is incomplete, and we should encourage participants to chime in. I'd add "sysout" "lcom" "dfasl", X11, SDL.
- [x] I might try Blake's advice of asking ChatGPT or Bard to rewrite the vocabulary and see what we get. TechSoup made the same suggestion.

i'm sure there are more

**Comment by phantomics** [comment]
These issues are resolved for now, we'll do more iteration on the front page as we progress.
