### ISSUE TITLE
more web site nits

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1240]
- [x] https://interlisp.org/medley/about/ seems to be About the Project (rather than About anything else).
- [x] in What People are Saying one of the Paul Ford tweets is repeated.
- [x] I like the placement but not the iinconsistent level of detail. And we should encourage people to write introductions.

**Comment by stumbo** [comment]
I made some minor updates to the [About](https://interlisp.org/medley/about/) page with [PR 108](https://github.com/Interlisp/Interlisp.github.io/pull/108).  Primarily some light editing and reformatting along with fixing a broken link.  Before I do much more we need to come up with a better vision of what all we want to cover here and how it will differ from the Project page.

**Comment by masinter** [comment]
I think an About page should be more of an Executive Summary -- brief, understandable, even if they read nothing else.

All the stuff about InterlispOrg inc belongs somewhere else.

**Comment by phantomics** [comment]
The "About" content has been moved to Project > Organization since it's all about the organization.

**Comment by phantomics** [comment]
This is good for now, we'll add more testimonials as they come in.
