### ISSUE TITLE
Credits Page Enhancements

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#1241]
**The Problem**

The [Credits](https://interlisp.org/medley/about/credits/) page focuses on a limited subset of individuals that have been involved with the Medley Interlisp project.  The credits should be expanded to include individuals that contributed to Interlisp from it's conception to the current restoration project.

This list would include individuals from BBN, PARC, Fuji Xerox, other organizations within Xerox that contributed and used Interlisp.  As with all such efforts, the result will be an incomplete list but it would give some acknowledgement and better represent the scope of the Interlisp effort.

**Comment by masinter** [comment]
i might have misunderstood -- I didn't understand issue #1092 vs #1241 (this one). I think the discussion on #1092 is still relevant and unreferenced or summarized here, so i'd rather keep it open.

**Comment by phantomics** [comment]
I'll add a broad acknowledgment statement at the top of credits and make plans to expand the individual credits.

**Comment by phantomics** [comment]
There's now a general acknowledgment at the top of the credits page. We could expand individuals' credits with a summary of their contribution but that opens questions of consistency. Any thoughts?

**Comment by phantomics** [comment]
Last remaining action item here is changing the credit names to link to people's Github profiles.

**Comment by phantomics** [comment]
The credits link to GH profiles so this appears done for now.
