### ISSUE TITLE
Change logo on landing page to use all white text instead of red and black text

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1242]
An all-white text logo is available in the logo repo (github.com/interlisp/common) in the file assets/logo/png/logo_white_no_border_568x385.png [here](https://github.com/Interlisp/common/blob/main/assets/logo/png/logo_white_no_border_568x385.png)

**Comment by stumbo** [comment]
Fixed in [PR 107](https://github.com/Interlisp/Interlisp.github.io/pull/107).
