### ISSUE TITLE
Vector (spatial) Library

### ISSUE THREAD

**Issue by RyanBurnside** [Interlisp/medley#1244]
From my limited knowledge, it seems that while Medley uses POSITIONS heavily in drawing and positioning there doesn't really seem to be a way to work with positional data in terms of vectors. I've been working on a Common Lisp vector library which is an algebraic abstraction over Common Lisp vector types called VEK. The idea is you can use these to preform manipulations then export the results back to a POSITION.

![Screenshot_2023-06-14_07-38-22](https://github.com/Interlisp/medley/assets/1874759/a1ea8627-023d-4984-83cd-0e02fab19ddd)

**Comment by pamoroso** [comment]
Does the MATMULT library package provide anything useful for this? The documentation is from page 233 of [this PDF document](http://www.bitsavers.org/pdf/xerox/interlisp-d/198809_Medley_1.0/300006_Lisp_Library_Modules_Sep88.pdf).

**Comment by RyanBurnside** [comment]
I think it's a bit more generic from what I've read (203).
But it's a good find.

**Comment by masinter** [comment]
I found some library documents and have proposed a  PR to add them to the medley repo.

https://github.com/Interlisp/medley/pull/1181  now includes MATMULT.TEDIT

Would be nice to get someone to review

**Comment by masinter** [comment]
``(FILESLOAD MATMULT)`` should install
``MAN MATMULT`` should give you documentation. 
@RyanBurnside 
If this doesn't meet your needs or has problems -- please reopen or raise another issue.
