### ISSUE TITLE
MASTERSCOPE doesn't expand (all) Interlisp macros

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1249]
To my surprise...

I define a record and an IL macro to extract a field in a less tedious way:

(RECORD REC (RECA))
PUT(GETREC MACRO ((X FIELD)(fetch (REC FIELD) of X]
EXPANDMACRO((GETREC Y RECA))
     → (fetch (REC RECA) of Y)

I define a function that invokes that macro, and analyze it
DEFINEQ((FOO (Y) (GETREC Y RECA)))
. ANALYZE FOO

Then ask:
. WHO USES THE FIELD RECA
NIL     (I expect to see FOO)

or .SHOW WHERE ANY FETCHES THE FIELD RECA
   (nothing)   I expect to see something like FOO (under GETREC)

This may have to do just with how Masterscope deals with its record keywords.  If I write a macro FUM that calls FOO, and then have BAR call FUM, asking who calls FOO will say  BAR under FUM

**Comment by masinter** [comment]
There is a bug I introduced because I didn't understsand that Medley supplies a MACRO-FUNCTION for Interlisp macros and CLisp words. There was a problem with Masterscope handling of CL macros but the fix I made in 2020 (one of the first when I was relearning Medley) was wrong.
#876
