### ISSUE TITLE
Loading EXPORTS.ALL doesn't set its FILEDATES property

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1259]
The effect is that if you have (FILES EXPORTS.ALL) in an EVAL@COMPILE, then the file gets re-loaded every time you compile.

This is because DOFILESLOAD, even when the loading function is LOAD?, checks the FILEDATES property before letting the call to LOAD? go through.

I think either MAKE-EXPORTS.ALL should put a form (maybe at the bottom) that sets the FILEDATES property, or we should stop DOFILESLOAD from trying to second guess what LOAD? is testing.  In particular, LOAD? looks at LOADEDFILELST as well as the FILEDATES property, and that would stop reloading of the same version.

Opinions?

**Comment by masinter** [comment]
My preference would be to change it to (declare  egal@compile dontcopy (fles sysedit)) and not load exports.all directly.   One of the open PRs is to get rid of AGC in favor of SYSEDIT.

**Comment by rmkaplan** [comment]
SYSEDIT sets some other parameters that are important when working ON the core system, a scenario that is a little bit different than working on something else (like TEDIT) that just has a dependency on core-system definitions.

**Comment by masinter** [comment]
still: there are multiple use cases for EXPORTS.ALL. Rather than building one into EXPORTS.ALL, have another file to load.

But what part of SYSEDIT would  you NOT want? see PR #1183

**Comment by masinter** [comment]
See PR #1184 what part of SYSEDIT would you NOT want?
Also: I've been thinking for things like this, whicvh aren't strictly bug-fixes but extending the Interlisp debugging environment, we should look zt the corresponding Common Lisp features that have arisen to solve related problems. Common Lisp has a couple of package managers -- something called "asdf" and I think two others are popular. Being able to load Common Lisp modules into Medley will probably require some faithful implementation.

**Comment by rmkaplan** [comment]
If I’m not really changing low-level stuff but just making use of macros and records, I might not want to override my current values of LCASEFLG CLISPIFTRANFLG RECOMPILEDEFAULT CROSSCOMPILING *REPLACE-OLD-EDIT-DATES* and so forth with their SYSEDIT values.

It is a different use case, to load SYSEDIT because you are starting to work on low-level stuff, compared to putting (FILES EXPORTS.ALL) in a COMS for some other file because you want to be sure that system declarations are automatically available when they are needed.

There might be a better longer-term scheme, if somebody wants to take that on.  Meanwhile I would settle for something that is better than what we have and maybe good enough.

**Comment by masinter** [comment]
what about getting rid of EXPORTS.ALL and have a function LOAD-EXPORTS which will load the exports .. then we wouldn't have to fuss where exports.all goes, or whether it is in sync with everything else loaded.

**Comment by nbriggs** [comment]
I don't think having a function to call makes it any better.  It still has to get the "right one" from the "right place".

**Comment by masinter** [comment]
if you want to (FIES EXPORTS.ALL) then EXPORTS.ALL has to be in a directory listed in DIRECTORIES -- can't be in TMP or LOADUPS  but one of LISPUSERS LISPCORE SOURCES INTERNAL ...
which leads to the probleme LISPUSERS et all are in "directories"' but EXPORTS.ALL isn't .
which is the problem in the release assets....

**Comment by nbriggs** [comment]
I'd look back to the original problem statement:  EXPORTS.ALL keeps getting reloaded because it doesn't set a FILESDATES property.  I think it should be easy to make sure it gets one.

**Comment by rmkaplan** [comment]
That’s the main issue, making sure it gets noticed properly so it doesn’t get uselessly or harmfully reloaded.  (Separately, why does DOFILESLOAD have its own heuristics different from LOAD?).

In terms of its location, it doesn’t need a function to make that uniform and independent of any of the other directory variables, because DOFILESLOAD has its own conventions.  So, with a MEDLEYDIR variable (e.g. EXPORTS.ALLDIRECTORY) defining the path, a command like (FILES (FROM EXPORTS.ALL) EXPORTS.ALL) should do it.

**Comment by masinter** [comment]
This is fixed in the current release.
