### ISSUE TITLE
run-medley -loadup option doesn't work with release sysout--MEDLEY-INIT-VARS isn't set up

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1264]
I am trying to build an LFG system in the release sysout, using the -loadup option in run-medley.

-loadup specifies a file to run instead of the normal greet, at least insofar as I can tell from the basic loadup scripts and how it works in my medley clone.

So I specified -loadup <the path to the LFG loadup LCOM>, and that file appears to load properly when the sysout starts up.  But it fails immediately because it can't find the first lispusers file that it wants to bring in.

The reason is that DIRECTORIES and LISPUSERSDIRECTORIES etc all retain their values from when the release makesys was created.  The paths all begin with {DSK}<home>runner>work>medley>medley>, even though MEDLEYDIR is correctly set to where I untarred the release distribution on my local machine.

I don't understand all the logic here, but I think that the function  MEDLEY-INIT-VARS on AROUNDEXITFNS isn't being called or isn't doing the right thing, even though the variable MEDLEY-INIT-VARS seems to have the names of all the relevant variables.

If I start up the release sysout without the -loadup, the normal greet happens.  In that case the directory variables that my INIT file explicitly sets have the right values.  But at least one variable, UNICODEDIRECTORIES is set to NIL.  This may be a separate issue, because it appears that UNICODEDIRECTORIES is not included in the release package.

**Comment by fghalasz** [comment]
I call (IL:MEDLEY-INIT-VARS 'IL:GREET) at the top of my LOADUP-APPS.CM to handle this issue.

**Comment by rmkaplan** [comment]
Does the GREET then do your personal greeting?

In making LFG loadups for (eventual) distribution, I don’t necessarily want to have things in there that my personal Init includes for my development work (like GITFNS) or for my own undocumented idioscynrasies.

How insulated is the release sysout made in this way?

**Comment by fghalasz** [comment]
The IL:GREET argument to MEDLEY-INIT-VARS has nothing to do with running GREET.   It just a SELECTQ selector for one of many ways that MEDLEY-INIT-VARS munges the various directories.

**Comment by rmkaplan** [comment]
OK, thanks.

I’m making progress.  The last (I hope) glitch appears to be that the old LFG preloaded some interpress fonts, and the release doesn’t include the font/ipfonts/ directory.

Have we decided to completely deprecate Interpress?

**Comment by nbriggs** [comment]
We shouldn't deprecate Interpress.

**Comment by rmkaplan** [comment]
Please add IPFONTS to the release

**Comment by fghalasz** [comment]
ipfonts added to releases in PR#1269

Note, however, this PR just adds fonts/ipfonts to the release tars (and installers).

It does not affect the loadups - so the ipfonts are not loaded into full.sysout as are the postscriptfonts.  See LOADUPFULLFONTS in sources/LOADUP-FULL.

**Comment by masinter** [comment]
It looks to me that this issue has been dealt with. If not, please feel free to reopen with explanation
