### ISSUE TITLE
Unusually long Interlisp Online startup time

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1268]
**Describe the bug**
For the past 2-3 weeks starting an Interlisp Online session on my Chromebox has been taking about 3-4X longer than usual, i.e. a couple dozen seconds compared to half a dozen seconds prior to that.

**To Reproduce**
1. sign into your Interlisp Online account
2. under `Initial Exec`, select `Interlisp`
3. click `Run Medley`

**Expected behavior**
The Interlisp environment is ready to use in half a dozen seconds or so.

**Screenshots**
The Interlisp Online loading screen after clicking `Run Medley`.

![interlisp-online](https://github.com/Interlisp/medley/assets/10342479/bbb087ed-8ef7-4517-b544-c33323d40de0)

**Context (please complete the following information):**
 - OS: chromeOS Stable
 - OS Version: 114.0.5735.205
 - Host arch: x86_64 (ASUS Chromebox 3)
 - Maiko version: not sure how to get it
 - IL:MAKESYSDATE: 22-Apr-2023 13:37:34

**Additional context**
I'm in Italy and use a 1 Gbps download / 200 Mbps upload fiber Internet connection that consistently delivers excellent performance. Here's a [speed test](https://www.speedtest.net/result/14966010036.png) I've run moments ago, a few minutes after taking the above screenshot:

![speedtest](https://github.com/Interlisp/medley/assets/10342479/379a9dc5-757f-485c-8682-7a77a9e3950f)

**Comment by masinter** [comment]
Following the instructions in the online repo docs, I ran `ssh oio` `oio ghosts kill`.
I should have checked to see what the jobs were doing gut I didn't.

What kind of load limiting do we need to make this not a problem?

**Comment by pamoroso** [comment]
Now the startup time is back to normal, i.e. half a dozen seconds or less.

**Comment by pamoroso** [comment]
The volume of ghosts may be growing as startup times are rising a bit.

**Comment by masinter** [comment]
looks like someone reset it.
or at least, no ghosts or active sessions.
