### ISSUE TITLE
What People are Saying suggestion

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1271]
### What type of entry?

Other

### Link to entry

https://hackaday.com/2023/07/09/reviving-interlisp-with-the-medley-interlisp-project

### Additional information

Maya Posch posted to Hackaday the short story *Reviving Interlisp with the Medley Interlisp Project*.

**Comment by stumbo** [comment]
Covered by \[PR-124\](Interlisp/Interlisp.github.io#124)

**Comment by stumbo** [comment]
Updated to add name of online blog
