### ISSUE TITLE
Rationalize build-release.sh with buildLoadup.yml - resulting in only one script to build releases.

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1285]
Synchronize the release build in buildLoadup with the release build in build-release.sh.  Put changes into release-build.sh, then call release-build.sh from buildLoadup to build releases in github actions.  That way we will have to maintain only a single set of code for building release tars.

**Comment by masinter** [comment]
these scripts have been reworked... no longer relevant.
