### ISSUE TITLE
Loadup-all.sh does not call Loadup-db.sh but copy-all.sh tries to copy the fuller.sysout and fuller.database files

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1289]
`loadup-all.sh` does not call `loadup-db.sh` but `copy-all.sh` (called from `loadup-all.sh`) tries to copy the `fuller.dribble' and `fuller.database` files to `loadups` - but these files have not yet been created.

We could add `loadup-db.sh` to `loadup-all.sh`.  But `loadup-db.sh` takes a long time - much longer than the rest of `loadup-all.sh`.  So we may want to keep it out of `loadup-all.sh`  in most cases.  Or we could add another command line option to `loadup-all.sh` so that the user can opt-in (or opt-out) of running `loadup-db.sh`.

Thoughts?

**Comment by masinter** [comment]
I wanted to release fuller.sysout too. loadup-db.sh takes 5 minutes. Is that long?
Does it matter?

**Comment by rmkaplan** [comment]
It isn’t long when building a release, but I wouldn’t want to see it in the loadup-all script that I use quite often in building my own systems.  The things I’m working on get analyzed incrementally, the other things change very slowly as PR’s are merged.  I run the loadup-db scripts maybe once a month.

**Comment by masinter** [comment]
I think I will continue to do my own loadups as I'm doing stuff.
@rmkaplan if you're happy doing your own loadups... ? I thought these changes were for you.

**Comment by rmkaplan** [comment]
This was about the expected/natural configuration of the release sysouts, not about sysouts made as part of internal development work.

The release could have a slightly different version of the “all” that makes the full database and copies it over.  I don’t think that copy-all runs for a local tmp build.

**Comment by masinter** [comment]
scripts/loadup-all.sh does a copy-all.sh at the end. This keeps us from having to add tmp to LOADUPSDIRECTORIES

**Comment by rmkaplan** [comment]
Hmm, I didn’t know that, I thought quite some time ago we got rid of loadups/ in local set ups.  Maybe it just went into .gitignore.

I’ve been running all of my local stuff out of tmp/, not depending on the copy.

Seems like we (or at least I) need some build scripts with a slightly different breakdown compared to the ones that the release process uses.

**Comment by rmkaplan** [comment]
BTW, the .gitignore lists the different files in loadups/ separately.  Shouldn’t it just say loadups/* ?

**Comment by masinter** [comment]
if you look in loadups there are these files that aren't ignored:
README.md - explain what is in loadups
starter.sysout -- stable Interlisp for makeinit to run in
lisp.venuesysout full.venuesysout -- oldest medley 3.5 sysouts we have. Could be moved to obsolete.

**Comment by fghalasz** [comment]
So I propose that we fully separate loadup-all.sh and loadup-db.sh (maybe renamed to loadup-fuller.sh).

loadup-all.sh just does up to full.sysout including calling copy-all.sh without any of the fuller files.

loadup-db.sh creates the fuller files and copies them to loadups.

That way Ron can continue with loadup-all.sh for everyday work and call loadup-db.sh when needed.  

From the github actions and release-medley.sh, we can call loadup-all.sh followed by loadup-db.sh so that the fuller stuff is included in the releases (if that's what we want).

**Comment by rmkaplan** [comment]
Seems reasonable.

**Comment by masinter** [comment]
@fghalasz I'm not sure in your scheme when the copy from tmp to loadups happen.
@rmkaplan It would simplify thigs if we stpped  using tmp and just writing the files as they are made into loadups. We could gitignore loadups if we moved starter.sysout and loadups/README.md.

**Comment by fghalasz** [comment]
The copy to loadups from tmp happens within each of the scripts (loadup-all and loadup-db) for the files that are created within that script.

**Comment by nbriggs** [comment]
tmp/RDSYS and tmp/RDSYS.LCOM also need to be copied into library/ as part of the build.  They are what give you "remote" access to a vmem files that was saved by uRaid's "v" command.

**Comment by masinter** [comment]
I think these issues have settled as far as matching the working style for a few of us, but we should start a "briefing blurb" that talks about how this whole thing holds together.

Once it's been stable a while.

**Comment by masinter** [comment]
this was a long discussion and I think we've have something now that makes this discussion not so interesting any more.
