### ISSUE TITLE
Search Updates

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#1291]
Update Search on `Interlisp.org` with the following:

- [ ] Update default Hugo search page to contain information on the scope of search on the Interlisp.org site
- [ ] Add Zotero Bibliography to the search space
- [ ] Add Interlisp Public Google Drive to the search space
- [ ] Add the Medley Interlisp YouTube Channel to the URLs to search

**Comment by masinter** [comment]
I'm not sure but even better would be checkboxes or some other way of selecting what spasce you wanted?

**Comment by masinter** [comment]
currently when I search for, say, https://interlisp.org/search/?q=bibliography#gsc.tab=0&gsc.q=bibliography&gsc.page=1   I get "no results"

**Comment by stumbo** [comment]
Part of the problem is that many of the pages on our site are not yet indexed by Google.  The bibliography pages are part of those not indexed yet:  [Pages discovered but not Indexed](https://search.google.com/u/1/search-console/index/validation?resource_id=https%3A%2F%2Finterlisp.org%2F&item_key=CAMYFiAC&hl=en&sharing_key=NQ4C_RJjbt1DRFUWLEsj6w)

**Comment by stumbo** [comment]
I've spent a little time working on this.  I've updated our custom search to *correctly* include both the lispcore and interlisp groups.  Searches now encompass the website, GitHub and the two google groups.  I've asked Google to reindex the bibliography page.  I'm hopeful the changes Matt made help the indexer do a better job of finding searchable content.  

I'm not confident that we'll be able to make information in Google Drive searchable.  I haven't found a good references that explains how to do it.  Most of what I see says to make content publicly available and then link to it -- once it's linked by a website it will get crawled by Google.  I'll do some experimenting along those lines and see if I can find a path forward.

**Comment by masinter** [comment]
i think we might want to be careful about what we publish rather than index the entire drive.
Let's close the issue as done.

it might be nice if "search" had some check boxess "this site" "all Interlisp sites" "mailing list archives" but I'll put that as a feature request once i've played with what we have.

**Comment by masinter** [comment]
There were 4 check boxes, and the first two seem ready, I'm proposing we don't do the 3rd. The fourth ( Add the Medley Interlisp YouTube Channel to the URLs to search) can wait till we have (more) videos.

**Comment by stumbo** [comment]
I'm good with that.  I will write up a short markdown document specifying what that we use Google's custom search and what sites we search, were the Custom Search setup is, access lists, etc.
