### ISSUE TITLE
\SUBREAD doesn't check the EOL convention

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1299]
This may have been something I missed when I did the external format conversion.

The function \SUBREAD (used by READ, RATOM etc.) gets its characters by calling \INCCODE.  That decodes the various external formats into character codes (interprets 255's for XCCS, high-order bit for UTF-8 etc.) but it doesn't coerce LF CR-LF to the canonical (CHARCODE EOL)=13.

The entry \INCCODE.EOLC decodes the format and canonicalizes the end-of-line.

This difference has gone unnoticed for quite awhile, mostly because LF and CR are separator characters in most readtables that would be used by these Lisp code-reading functions.

But it turns out that the Tedit Bravo converter, ancient code (LPD initials in some places) and funky in many respects, uses a readtable in which 13 is set as a break-character that it expects RATOM to return as a single-characer atom.

Is there a reason not to have RATOM and READ do the EOL interpretation, or was this just an oversight on my part?

**Comment by masinter** [comment]
fixed by #1300
