### ISSUE TITLE
"Getting Involved" is hard to find, even when looking for it

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1314]
- [x] "Getting Involved' should appear at least in the top-level link of "About the Projeect".

the link to the projects list should have a link to the Donations page.

I wonder if we could suggest people "sponsor" a project they want to see done.
i'm wondering if we could offer an hour for every $100 donation working on any issue in the issue list (using the PICK lispusers library if they don't want to choose one.

**Comment by phantomics** [comment]
"Get Involved" is now a top-level category visible in the header menu at all times. We could implement a "sponsor this" list; it would be best to discuss and make a plan.

**Comment by phantomics** [comment]
This is resolved for now, it's still difficult to determine how to turn donated money into work on Medley so the "sponsor this" option is tabled for now.
