### ISSUE TITLE
"Invalid argument: 4294967325error during GREET..."

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1317]
**Describe the bug**
Starting a clean, release sysout gives the error (see Screenshot).
This is referencing a current **master** repo, using the **medley-230815-701a642f-loadups.tgz** binaries.

**To Reproduce**
1. git pull latest **master** branch
2. download **medley-230815-701a642f-loadups.tgz** release and extract files into **loadups** directory.
3. Open Ubuntu shell in home directory (~)
4. launch medley as background process: m &
a. alias m defined as: alias m='/mnt/e/Interlisp/medley/run-medley -full -noscroll -g 1920x1080 -sc 1888x1047'
5. medley window opens and displays error as shown.
6. **NOTE**: I do not have a personal, or site, INIT.LISP greet file.

**Expected behavior**
Continue sysout loadup to point of showing greeting.

**Screenshots**
![BugReport-medley](https://github.com/Interlisp/medley/assets/8261874/a7801435-12c2-429d-972d-45992240b784)

**Context (please complete the following information):**
 - OS: Windows 11 Home 
 - OS Version: 22H2 22621.2134
 - Ubuntu version: 20.04.4 (w/ WSL)
 - Host arch: x86_64 (AMD Ryzen 2700X)
 - Maiko version: commit d1f4653b9586b16997465e62dcfef39f6443defc
 - IL:MAKESYSDATE: 21-Aug-2023 02:03:49

**Comment by fghalasz** [comment]
This error is repeatable with Maiko version: commit d1f4653b9586b16997465e62dcfef39f6443defc (aka maiko-230607-d1f4653b).

It does not occur using a maiko built from the latest master.

I build a new release of Maiko (maiko-230809-7fce08f9) from the current master branch.  It is now available on github Maiko releases.

Closing.

**Comment by MattHeffron** [comment]
With the medley-230927-de4e5f5c-loadups.tgz files, and the local repository files at the medley-230927-de4e5f5c tag, the error still occurs.

**Comment by nbriggs** [comment]
@MattHeffron - which maiko commit were you at when it failed?

**Comment by MattHeffron** [comment]
I **thought** that had gotten the release when you fixed it **before** and verified it _then_.
Sorry.
