### ISSUE TITLE
Protection violation error when creating a file in a directory other than home

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1325]
**Describe the bug**
When in an Interlisp Online session I try to create a file in a directory other than the default `{DSK}<home>medley>il>` I get the error `Protection violation: {DSK}<home>medley>il>demo>MYFILE.;1`.

**To Reproduce**
1. sign into your Interlisp Online account
2. under `Initial Exec`, select `Interlisp`
3. click `Run Medley`
4. create a `demo` directory and `CD` to it
5. at the Exec, evaluate `(OPENSTREAM 'MYFILE 'OUTPUT)`

**Expected behavior**
The file is created with no error.

**Screenshots**
The full desktop with the error in the Exec:

![protection-violation-error](https://github.com/Interlisp/medley/assets/10342479/5f31c413-80c7-4af1-8d44-c53011e52e11)

**Context (please complete the following information):**
 - OS: chromeOS Stable
 - OS Version: 116.0.5845.210
 - Host arch: x86_64 (ASUS Chromebox 3)
 - Maiko version: not sure how to get it
 - IL:MAKESYSDATE: 15-Sep-2023 23:14:52

**Additional context**
Any other file creation or write access produces the same error, such as calling `MAKEFILE`.

**Comment by fghalasz** [comment]
@pamoroso  How did you create the "demo" directory?

**Comment by pamoroso** [comment]
It's an old directory I think I created with `mkdir` from the Linux shell (right-click menu > `Chat` > `No Login`). But now I can't reproduce the issue with a new, different directory created the same way: `(OPENSTREAM 'MYFILE 'OUTPUT)` creates the file with no errors.

Is it possible to create directories from the Medley environment? I haven't found any obvious way.

**Comment by nbriggs** [comment]
> Is it possible to create directories from the Medley environment? I haven't found any obvious way.

You can't create an empty directory, but if you open a file where directories on the path don't exist it will create them before creating the file.   Thus

```
(SETQ S (OPENSTREAM "{dsk}/tmp/newdir/foo.txt" 'OUTPUT 'NEW))
```
will create `newdir`

**Comment by masinter** [comment]
you can then DELFILE("{DSK}/tmp/newdir/foo.txt") and you will have created an empty directory.
This behavior is idiosyncratic but it's hard to come up with an obvious scenario.

 Does the problem still occur? only in online? Close if not.

**Comment by nbriggs** [comment]
If you create a directory with the "wrong" permissions (via the shell) then this (protection violation) is the expected result.  If we can get a reproducible case I'll look at it, otherwise I agree with Larry, it should be closed-not-planned.

**Comment by pamoroso** [comment]
The problem no longer occurs as now I'm creating directories from Lisp and not the Linux shell, e.g. by supplying an appropriate path when calling `MAKEFILE`. So this issue can be closed.

The directory where the issue occurred has the same permissions as Lisp-created directories, as well as the files they contain.

**Comment by pamoroso** [comment]
The problem occurs when uploading files with the noVNC File Manager, which sets the Unix owner to `root` and the group to `root`. But Medley can modify only files set as user `username` and group `medley`, hence the protection violation error. The noVNC File Manager also sets the execution permission for all but this has no impact on Medley's ability to read or write the files.

Medley can be granted write access to the uploaded files by executing from the Chat shell the command `sudo chown username:medley filename` and, when prompted, entering the password listed in the who-line.
