### ISSUE TITLE
Documenting SYSEDIT, MEDLEY-UTILS, loadup scripts and processes and other maintenance tools

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#134]
see

https://github.com/Interlisp/medley/pull/129#issuecomment-754840538

set LCASEFLG to NIL
CLISPIFYPRETTYFLG and CLISPIFTRANFLG  are set in SYSEDIT, while LCASEFLG is not included there. But SYSEDIT doesn’t need to be loaded for typical work on library and lispusers files.

**Comment by Anzus** [comment]
I think we need to document SYSEDIT and what's for. I would not be surprised if there's a lispusers file that would need it loaded in order to compile.

**Comment by masinter** [comment]
consolidating with #136
