### ISSUE TITLE
Move Bibliography.json file out of repo

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#1343]
**Is your feature request related to a problem? Please describe.**
The Zotero Bibliography update action can not push updates into the `main` interlisp.github.io branch.  Consequently, he Github Action will error when the Zotero bibliography changes.

**Describe the solution you'd like**
The `bibliography.json` file is not needed in the repository.  Move it out of source control.  The Github Action should be set up to check the version of the bibliography and if its changed since the last build pull the new version and rebuild the site.

**Describe alternatives you've considered**
The current strategy of pulling the `bibliography.json` file and only pushing an update if there were changes was implemented as a first step towards moving the `bibliography.json` file out of the repository.  It gives us the framework to build the next step.  It's time to build the next piece.

**Additional context**
Consider caching the `bibliography.json` file.  This could be useful when the file hasn't changed and there are other changes necessitating a build.

**Comment by MattHeffron** [comment]
Isn't that the issue at hand? The Github Action **cannot** push the updated `bibliography.json` file into the repo.
