### ISSUE TITLE
2023 Annual Report 

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1349]
we had an annual report in 2021 and 2022, and it's time to start preparing for our 2023 Annual Report.

The Annual Report includes significant milestones for people who don't follow the project from day-to-day or even month-to-month.

But I think we might prepare for the 2023 Annual Report in a different way: update the Interlisp.Org web site (and site map) to include the news that we will report, and then construct the Annual Report as mainly consisting of excerpts. This will give us updated web content, drive our strategy for updating the site.

The updated material should cover:
* Installers -- update documentation (both in web site and READMEs and other GitHub content)
* Online -- (minor updates)
* Building

* PDF
* GitHub integration

* External communications
* BALisp talk, Steve's talk
* What People are Saying

* Bibliography updates

* Modernization

* Donations

**Comment by pamoroso** [comment]
The report was [published](https://interlisp.org/project/status/2023medleyannualreport/), so I'm going to close this issue as done.
