### ISSUE TITLE
CommonLisp Functions on 'control' characters no longer work correctly.

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1353]
**Describe the bug**
The CommonLisp functions and read macros to create characters in the ASCII control character range now fail where they used to work.

**To Reproduce**
1. Run the "full.sysout"
2. In the XCL exec enter: `(CODE-CHAR 10)`
3. This returns a strange _pseudo-character_ representing the error message:
 `#\The value of SEQUENCE, IL:|Linefeed|, is not a LIST or a VECTOR.`
4. This also fails for the value 12 (^L, `IL:|Page|`), but works for the value 65 (A, `#\A`)
5. The same results happen using the read macros: `#\Linefeed` or `#\Page`

**Expected behavior**
This should return a character representing the Linefeed, or Page, character.

**Context (please complete the following information):**
 - OS: SL
 - OS Version: Ubuntu 22.04.3
 - Host arch: x86_64
 - Maiko version: 7fce08f9
 - IL:MAKESYSDATE: 16-Oct-2023 02:03:58

**Additional context**
I know that this **used to work**, because I have a file that contains the `#\Page` read macro in a function. (The file uses the "XCL" READTABLE.) I edited a different function, but it failed with the above error when I did the MAKEFILE. It also fails with that error if I attempt to edit the function containing the `#\Page` read macro. This file has been edited and compiled _earlier_ this year (its most recent IL:FILECREATED date: 6-Mar-2023).

**Comment by rmkaplan** [comment]
In trying to fix the filemap for CML SECHARACTER so I could look at CL:CODE-CHAR, I found that I couldn’t “SEE” the file.  SEE CMLCHARACTER breaks with an error in CL:LENGTH that the "value of SEQUENCE, Newline, is not a LIST or a VECTOR”.

I will add the fixed filemap to the CMLARITH PR, but I’ll also note that this is case where CLEANUP didn’t do the right thing.  There was a pre-existing LCOM, FILETYPE was CL:COMPILE-FILE, and it produced a DFASL, leaving the LCOM hanging around.  I’ll explicitly delete the LCOM in the other PR, migrate this to DFASL (with a better filemap).

**Comment by masinter** [comment]
fixed in recent merges
