### ISSUE TITLE
BICLOCK hasn't changed, but display of clock changed from 1 oct release

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1369]
in current release and back to 1 Oct the display of (BILOCK) at 1:04 or so is
![image](https://github.com/Interlisp/medley/assets/1116587/654f59c5-e1c3-4e4b-b005-4b5c88e929df)

Was there a change merged to CMLARITH?

**Comment by nbriggs** [comment]
According to the git log it was remade/recompiled on Saturday/Sunday September 23rd.
(cd medley/sources; git log CMLARITH)

What did your who-line clock say at the time?  BICLOCK isn't failing for me at 1:25 pm today, with a full.sysout I made yesterday.

**Comment by rmkaplan** [comment]
As far as I know, the only PR with CMLARITH has not been approved or merged.  But the only change to CMLARITH was to remake/recompile the file with an upgraded filemap, for DEFUNs and DEFMACROs.

**Comment by rmkaplan** [comment]
I note that the compiled file of CMLARITH has always been LCOM, but its FILETYPE is COMPILE-FILE.  So maybe the right compiler (FAKE-COMPILE-FILE ?) wasn’t chosen when I recomipled it?

**Comment by masinter** [comment]
Sorry biclock irrelevant 

As is sysout date. Needs more investigation

**Comment by masinter** [comment]
This problem has nothing to do with BICLOCK, CMLARITH, Sysout versions or anything from Medley.

There WAS something wrong with my WSL installation, doing
``sudo hwclock -s`` in WSL fixed it.
