### ISSUE TITLE
ptsname definition in stdlib.h needs _XOPEN_SOURCE=... in Debian 10

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#137]
**Describe the bug**
Warning during compilation of unixcomm.c

../src/unixcomm.c:297:17: warning: passing argument 2 of ‘strcpy’ makes pointer from integer without a cast [-Wint-conversion]
   strcpy(Slave, ptsname(res));
                 ^~~~~~~~~~~~

**To Reproduce**
Recompile unixcomm.c on Debian 10 -- note warning message (or not, if fixed)

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Debian 10 (buster)
 - Host arch: armv7l
 - Maiko version: commit a093d80fa5cdcdd98cfa297e25446a8033675d62

**Additional context**
The stdlib.h header on this OS contains:

#ifdef __USE_XOPEN_EXTENDED
[...]
/* Return the pathname of the pseudo terminal slave associated with
   the master FD is open on, or NULL on errors.
   The returned storage is good until the next call to this function.  */
extern char *ptsname (int __fd) __THROW __wur;
#endif

which depends on _XOPEN_SOURCE=500 (or 600, 700) being defined in order for the feature to be available.

**Comment by waywardmonkeys** [comment]
Interesting ... I had an issue like this briefly in a build and then it had gone away and I forget what I did.

There's a lot of interplay between some settings like `_XOPEN_SOURCE`, `_GNU_SOURCE`, `_DEFAULT_SOURCE`, `_POSIX_C_SOURCE` and more.

One way to figure out what's up is to try this:

```
gcc -std=gnu89 -dM -E /usr/include/features.h  | sort -u | grep -i source
```

That'll give us an idea of how the feature flags are getting set up ...

And now I see that this is also happening on Ubuntu for me on x86_64.

**Comment by nbriggs** [comment]
The Debian 10 system is, for `-std=gnu89` with gcc 8.3.0

> #define _ATFILE_SOURCE 1
#define _DEFAULT_SOURCE 1
#define _POSIX_C_SOURCE 200809L
#define _POSIX_SOURCE 1
 
and if you use -std=c89 you get nothing.
Exactly the same behavior on Ubuntu 20.04.1 on x86_64.

-D_XOPEN_SOURCE=500 gets you

>#define __USE_XOPEN 1
#define __USE_XOPEN_EXTENDED 1
#define _XOPEN_SOURCE 500
