### ISSUE TITLE
Extend "man" to Lispusers documentation 

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1372]
The "man" command currently gives information for items that are indexed in the (legacy) IRM, and it goes out to the commonlisp repository for information about commonlisp items.

But it comes up empty for items that belong to lispusers/ applications, even though many of those applications have associated lispusers/*.TEDIT documentation files.   Even if those files are not explicitly indexed, I think a simple hack can fill in the gap at least for items that appear in the WHEREIS database.

So, for an input "man XXX", if XXX is not otherwise document, it can be looked up in the WHEREIS to find what file contains that item, e.g. XFILE.  If XFILE.TEDIT exists, then man can bring that up in Tedit.  And maybe initialize the window by doing a TEDIT.FIND for XXX.  If XXX has multiple types in different files, a menu can be brought up to pick the file.

**Comment by masinter** [comment]
Try ``MAN H3LPSYS``. you should see.. I did this over a year ago. If there's a case that isn't working like you think it should.... 
```
(REPO.LOOKUP keyord)	[Function]

In addition, the lookup program has been extended to also look up functions and variables in Library and LispUsers packages, by looking up in the WHEREIS database and, if there is a TEdit or TXT file for that package, opening that.  This only wo...
```

Maybe we need a web page telling people about how to use 'man'

@skaisler1 was gathering a list of modernizations... @phantomics

**Comment by rmkaplan** [comment]
Yep, you beat me to it.  I didn't realize that this had been extended.

The only addition would be to to do a Find at start up, so that the file would be positioned at at least the first mention of the item, if it appears literally in the text.

**Comment by rmkaplan** [comment]
As noted in earlier comments, this was done.
