### ISSUE TITLE
-title not working on Mac under Sonoma

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1386]
I updated to the new macOS version Sonoma.

I will report separate a number of issues because of an implicit change in the shell that I was able to resolve with Nick's help.

But the -title parameter in run-medley is still not doing the right thing.  (That may have gone wrong before my update; I just noticed it now).

With MEDLEYDIR set to the release directory and connected to that directory(or the clone, doesn't matter), then command

./run-medley $screen -title Release-Medley  -full 

produces

sysout Release-Medley
running: lde   -g 1440x900 -sc 1440x900 -title "Medley Interlisp" -m 256  -g 1920x1036 -sc 1888x1004 -title /Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout

Note 2 -title's, neither of which is the one in my command.  The window shows up with the last one.

And note that the preceding line says "sysout Release-Medley", that seems to be where my explicit  -title ended up.

**Comment by nbriggs** [comment]
What was the value `$screen` when you did this?
Try doing
```
sh -x ./run-medley $screen -title Release-Medley -full
```
and post the text it prints, for example:
```
+ inferred_medleydir=false
+ '[' -z '' ']'
+++ dirname ./run-medley
++ cd .
++ pwd -P
+ export MEDLEYDIR=/Users/briggs/Projects/medley
+ MEDLEYDIR=/Users/briggs/Projects/medley
+ inferred_medleydir=true
+ '[' '!' -d /Users/briggs/Projects/medley/loadups ']'
+ prog=lde
+ pass=
+ mem='-m 256'
+ scroll=22
+ noscroll=
+ display=
+ title='Medley Interlisp'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ export LDEDESTSYSOUT=/Users/briggs/lisp.virtualmem
+ LDEDESTSYSOUT=/Users/briggs/lisp.virtualmem
+ '[' -z '' ']'
+ export LDEINIT=/Users/briggs/Projects/medley/greetfiles/MEDLEYDIR-INIT
+ LDEINIT=/Users/briggs/Projects/medley/greetfiles/MEDLEYDIR-INIT
+ '[' 2 -ne 0 ']'
+ case "$1" in
+ '[' -n foo-bar ']'
+ title=foo-bar
+ shift
+ shift
+ '[' 0 -ne 0 ']'
+ '[' -z '' ']'
+ '[' -f /Users/briggs/lisp.virtualmem ']'
+ export LDESRCESYSOUT=/Users/briggs/lisp.virtualmem
+ LDESRCESYSOUT=/Users/briggs/lisp.virtualmem
+ '[' -z '' ']'
+ geometry='-g 1440x900'
+ screensize='-sc 1440x900'
+ command -v lde
+ echo 'running: lde   -g 1440x900 -sc 1440x900 -title "foo-bar" -m 256  /Users/briggs/lisp.virtualmem'
running: lde   -g 1440x900 -sc 1440x900 -title "foo-bar" -m 256  /Users/briggs/lisp.virtualmem
+ echo 'greet: /Users/briggs/Projects/medley/greetfiles/MEDLEYDIR-INIT'
greet: /Users/briggs/Projects/medley/greetfiles/MEDLEYDIR-INIT
+ export INMEDLEY=1
+ INMEDLEY=1
+ lde -g 1440x900 -sc 1440x900 -m 256 -title foo-bar /Users/briggs/lisp.virtualmem
```

**Comment by rmkaplan** [comment]
echo $screen
-g 1920x1036 -sc 1888x1004

Here’s the printout (run-medley from the release tar file)

***@***.*** release-medley % sh -x ./run-medley $screen -title Release-Medley -full
+ inferred_medleydir=false
+ '[' -z /Users/kaplan/Local/medley3.5/release-medley/ ']'
+ '[' '!' -d /Users/kaplan/Local/medley3.5/release-medley//loadups ']'
+ prog=lde
+ pass=
+ mem='-m 256'
+ scroll=22
+ noscroll=
+ display=
+ title='Medley Interlisp'
+ '[' -z '' ']'
+ '[' -z /Users/kaplan/lisp/ ']'
+ export LDEDESTSYSOUT=/Users/kaplan/lisp//lisp.virtualmem
+ LDEDESTSYSOUT=/Users/kaplan/lisp//lisp.virtualmem
+ '[' -z '' ']'
+ export LDEINIT=/Users/kaplan/Local/medley3.5/release-medley//greetfiles/MEDLEYDIR-INIT
+ LDEINIT=/Users/kaplan/Local/medley3.5/release-medley//greetfiles/MEDLEYDIR-INIT
+ '[' 4 -ne 0 ']'
+ case "$1" in
+ pass=' -g 1920x1036 -sc 1888x1004 -title'
+ shift
+ shift
+ '[' 2 -ne 0 ']'
+ case "$1" in
+ echo sysout Release-Medley
sysout Release-Medley
+ export LDESRCESYSOUT=Release-Medley
+ LDESRCESYSOUT=Release-Medley
+ shift
+ '[' 1 -ne 0 ']'
+ case "$1" in
+ export LDESRCESYSOUT=/Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout
+ LDESRCESYSOUT=/Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout
+ shift
+ '[' 0 -ne 0 ']'
+ '[' -z /Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout ']'
+ '[' -z '' ']'
+ geometry='-g 1440x900'
+ screensize='-sc 1440x900'
+ command -v lde
+ '[' -z /Users/kaplan/Local/medley3.5/maiko/ ']'
+ command -v /Users/kaplan/Local/medley3.5/maiko//bin/osversion
+ oldpath=/Users/kaplan/Local/xle/bin:/Users/kaplan/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin
++ pwd
+ oldpwd=/Users/kaplan/Local/medley3.5/release-medley
+ PATH=.:/Users/kaplan/Local/xle/bin:/Users/kaplan/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin
+ cd /Users/kaplan/Local/medley3.5/maiko//bin
++ osversion
+ osv=darwin
++ machinetype
+ mct=aarch64
+ newpath=/Users/kaplan/Local/medley3.5/maiko//darwin.aarch64
+ PATH=/Users/kaplan/Local/medley3.5/maiko//darwin.aarch64:/Users/kaplan/Local/xle/bin:/Users/kaplan/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin
+ cd /Users/kaplan/Local/medley3.5/release-medley
+ command -v lde
+ echo 'running: lde   -g 1440x900 -sc 1440x900 -title "Medley Interlisp" -m 256  -g 1920x1036 -sc 1888x1004 -title /Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout'
running: lde   -g 1440x900 -sc 1440x900 -title "Medley Interlisp" -m 256  -g 1920x1036 -sc 1888x1004 -title /Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout
+ echo 'greet: /Users/kaplan/Local/medley3.5/release-medley//greetfiles/MEDLEYDIR-INIT'
greet: /Users/kaplan/Local/medley3.5/release-medley//greetfiles/MEDLEYDIR-INIT
+ export INMEDLEY=1
+ INMEDLEY=1
+ lde -g 1440x900 -sc 1440x900 -m 256 -title 'Medley Interlisp' -g 1920x1036 -sc 1888x1004 -title /Users/kaplan/Local/medley3.5/release-medley//loadups/full.sysout—

**Comment by nbriggs** [comment]
The problem is that when you use `$screen`, that gets passed down into the script as a single item, not broken up into the separate arguments "-g" "1920x1036" "-sc" "1888x1004" -- so when it tries to match the whole string "-g 1920x1036..." against known -arguments it doesn't match, so it falls into the "-*)" case and eats the whole `$screen` value as $1 and the `-title` as $2 leaving the actual title as the sysout name.

It works this way on my macOS BigSur system where I also have zsh as my shell.

Quick fix: in your zsh startup: `setopt sh_word_split` - which will make it work more like csh etc.

**Comment by rmkaplan** [comment]
That seems to work around it, thanks

**Comment by rmkaplan** [comment]
Done
