### ISSUE TITLE
DIRECTORY problems

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#140]
I'm not quite sure what the problem is, but I'm having
trouble calling IL:DIRECTORY or CL:DIRECTORY to get
a list of source files only in MEDLEYDIR/library

When I do (DIRECTORY (CONCAT (MEDLEYDIR "library") "*.;"))
i get all versions and all extensions in subdirectories.

This seems to also happen in lisp.venuesysout so lll

**Comment by nbriggs** [comment]
That doesn't happen for me in the full.venuesysout (using IL:DIRECTORY).

**Comment by nbriggs** [comment]
It *does* include the directories, though, with no files underneath them (e.g., LAFITE>) which I think is correct since the directory has no extension and no version.

**Comment by masinter** [comment]
LISP.VENUE has the problem
![Screenshot 2021-01-08 193801](https://user-images.githubusercontent.com/1116587/104082205-27174b80-51e9-11eb-83b0-02a8be112bd7.png)
full.venue doesn't
![FULL VENUE](https://user-images.githubusercontent.com/1116587/104082486-65156f00-51eb-11eb-9d99-9d8111671f3a.png)

**Comment by masinter** [comment]
I've narrowed this down to the difference in code (do `INSPECTCODE(\UFS.NEXTFILEFN)`  between lisp.venuesysout dated 10 April 2000 (which has the problem) and full.venuesysout dated 4 Nov 2003 (which doesn't).
\UFS.NEXTFILEFN is in the file UFS.  `pl UFS` shows the same filedates of 29-MAR-95, 

`find . -type f -name "UFS*" -mtime +7400 -exec ls -l {} \;`

**Comment by nbriggs** [comment]
I suspect it's the difference between UFS.~3~ and UFS.~4~

**Comment by masinter** [comment]
the file  UFSNFS (which is not in the medley repo, but *is* in /history/2020s/202011-lisp/library/UFSNFS)
contains an earlier version of \UFS.NEXTFILEFN (and a few other  \UFS functions).
It looks like UFS was edited by jds in 93 to pay attention to the SUBGENERATORS field of GENFILESTATE.

**Comment by nbriggs** [comment]
UFSNFS is in the venue full.sysout but not in the venue lisp.sysout.   This means the process of vetting files that were removed from the main repository was incomplete/incorrect and needs to be done again to ensure that we do not lose source for code that we are running.

**Comment by masinter** [comment]
After diving into the code and getting lost, I've come to some conclusions:
There was a change introduced between 91 and 93 to extend the variable FILING.ENUMERATION.DEPTH to apply to {DSK} and possibly other file system types beyond XNS servers. The implementation in UFS honors this change. The UFSNFS implementation is older -- even though the F.E.D = T (default, `MAN FILING.ENUMERATION.DEPTH`) means infinite depth.
Many of the lispusers/ and greetfiles INIT files set FILING.ENUMERATION.DEPTH. Setting it to 1 gives expected behavior.
F.E.D = T triggers a bug that the pattern (no extension, highest version) isn't passed down. That and the fact that this isn't documented behavior (unless it's in one of the user guides).

**Comment by masinter** [comment]
when FILING.ENUMERATION.DEPTH = T (infinite) lots of bad things happen -- it doesn't know about symbolic links, will enumerate "hidden" directories (like .git). The simplest fix for the problems at hand is to set it to 1 in SIMPLE-INIT
