### ISSUE TITLE
Request:  Add RMDIR to UNIX-UTILS

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1400]
This has come up a couple of times.  Medley implicitly creates a directory or subdirectory if that is specified in the name of a file that it needs to create.  But once a directly has been created, there is no way to remove it from inside Medley.

So this is a request to add a RMDIR function, presumably in UNIX-UTILS, that tests to see if the directory exists and has no files, and if it meets those conditions, executes an appropriate rmdir Shell command.

**Comment by nbriggs** [comment]
I think extending the `DELETEFILE` method for `DSK` and `UFS` FDEVs to delete an empty directory given as the filename argument would be a better approach.

**Comment by nbriggs** [comment]
Author: Nick Briggs <nicholas.h.briggs@gmail.com>
Date:   Fri Mar 18 18:20:35 2022 -0700

    Implement DELFILE for (empty) directories on the {unix} device (#409)
    
    If the argument to DELFILE represents a directory on the {unix} device
    either directly or through resolving to a full pathname via the connected
    host/directory, and the directory is empty, then the directory will be deleted
    and the deleted directory name will be returned.  Will error if the
    directory is not empty, and return NIL if the argument does not name a directory
    or file.
