### ISSUE TITLE
Landing page and goals

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1402]
The title should go back to "The Medley Interlisp Project" with subtitle "a retrofuturistic software system".   Maybe regenerate the image with the current logo visible inthe upper right hand corner and remove it from the left-hand side.

Reasoning: the home apge slash screen isn't about retrofuturistic. People don't know the word and it's not mentioned or addressed anywhere in the site and is only positive for a small subset of our target audience.

We have several audiences with differing (but not conflicting) goals:

1.  Historians, archivists, instructors teaching computing history and software evolution. For these, our gGoal is to illustrate the advantage of "revival" of older software systems to be able to glean much more than you can get from watching old demos. It's the reason for calling it a "revival". It's part of the reason for wanting older versions also available.   
2.  Software developers and those making tools for them: to illustrate what seems to be missing from modern software tools.  
3. Computing enthusiasts and hobbyists. Individuals who want to learn the lessons of 1 and 2 but also have fun and explore.  It would be great to have someone build a system using Medley embedded.

4. Common Lisp developers. A small community of iconoclasts, but most likely to be helpful in addressing the audience above.

It's possible to meet those needs with the same introductory text, but requires some care.

Here are a couple of AI generated rewrites (from Bing):

---

Interlisp, a programming language and environment, was developed at Xerox’s Palo Alto Research Center (PARC). This work influenced the development of modern graphical user interfaces. Interlisp formed the basis for Medley, a graphical software environment that extended PARC’s design principles and also supports Common Lisp.

Medley was a commercial product in the 1990s but became largely unavailable. The Medley Interlisp Project, led by some original developers and newcomers, has revived the system on modern computer systems. The project aims to preserve the Interlisp language, tools, and applications.

For those interested in retro-computing, software history, or modern software tool design, this project offers a unique opportunity to explore a significant piece of computing history. A glossary is available to help understand the terms associated with the project.

---

Welcome to the epicenter of a computing revolution! Interlisp, a programming language and environment, was conceived at Xerox’s Palo Alto Research Center (PARC), the birthplace of the modern graphical user interface. This groundbreaking work at PARC has shaped the graphical operating systems we interact with today.

Interlisp was the cornerstone for Medley, a graphical software environment that encapsulated the forward-thinking design principles of PARC. Medley, once a commercial product in the 1990s, faded into obscurity and remained largely inaccessible until now.

Today, we’re witnessing a revival of this classic. Thanks to the tireless efforts of some original developers and passionate newcomers, Medley is back in action on contemporary computer systems. The Medley Interlisp Project is not just a nostalgic trip down memory lane, but a journey to rekindle the Interlisp experience - the language, the tools, and the myriad applications, experiments, and playful creations that were crafted in and for it.

For those of you who are retro-computing enthusiasts, software historians, or modern software tool designers, this is a treasure trove of knowledge and inspiration. Dive into our glossary to familiarize yourself with the terms associated with our project. Join us as we explore the past, present, and future of Interlisp.

--- 

Welcome to the home of Interlisp, a programming language and environment born out of the innovative work at Xerox’s Palo Alto Research Center (PARC). PARC is renowned as the cradle of the modern graphical user interface, and its influence permeates the graphical operating systems of today. Interlisp, a brainchild of this pioneering environment, laid the foundation for Medley - a graphical software environment that encapsulated the design ethos of PARC.

In its heyday, Medley was a commercial product that gradually faded away in the 1990s and remained largely inaccessible until recently. Today, thanks to the relentless efforts of some of the original developers and enthusiastic newcomers, Medley is experiencing a renaissance on contemporary computer systems.

The Medley Interlisp Project is a tribute to the Interlisp legacy. Our mission is to resurrect the Interlisp experience - the language, the tools, and even some of the applications, experiments, and playful creations that were crafted in and for it.

Are you overwhelmed by the jargon? Don’t worry, we’ve got you covered. Check out our glossary to get up to speed with the terms associated with our project.

**Comment by staypufd** [comment]
I agree.  That adds a lot to the description and helps people see it as much more.

**Comment by masinter** [comment]
I was going to submit a PR but I can't decide. Here's another rewrite

<header>
  <h1>The Interlisp Revival</h1>
</header>
<p>Interlisp, a software development environment and programming language, evolved over the 1970's and 1980's at Xerox’s Palo Alto Research Center (PARC).
PARC is remembered mainly as the birthplace of the modern graphical user interface. Interlisp grew into Interlisp-D, development spun out to a separate company, and was renamed "Medley". </p>

<p>Medley's life as a commercial product ended in the 1990s, and until recently  it was unavailable. The project aims to extend the Medley environment so that applications, tools, experiments written with it can continue to be developed, using modern computing infrastructure. With modern hardware, Medley can run Interlisp applications and development tools 1000 times faster. With the combined efforts of some of the original developers and interested newcomers. Our goal is to revive the tools, applications, and experience to the point where development of both aOur goal is to revive Interlisp in language, environment and spirit through the Medley Interlisp Project.</p>

**Comment by pamoroso** [comment]
On Thu, Nov 9, 2023 at 6:55 PM Larry Masinter ***@***.***>
wrote:

> I was going to submit a PR but I can't decide. Here's another rewrite
>
It sounds good: clear and concise.

-- 
Paolo Amoroso <https://paoloamoroso.com> | Blog
<https://journal.paoloamoroso.com> | Mastodon
***@***.***>

**Comment by masinter** [comment]
I was in the middle of an edit and stopped, so the last sentence is garbled. 
I think we want to run Common Lisp applications too.
It should say 1000 times faster on a Raspberry Pi than it did on a Dorado.
Or should it? 
 The history of the spin-out and so on is complicated and I didn't want to get too deeply into it while not saying things that are untrue, or that I don't want to get into here in the summary.
For example http://top2bottom.net/medley.html

**Comment by nbriggs** [comment]
Seems OK.  I'd fix "that applications, tools, experiments written with it" to be "that applications, tools, and experiments written with it"

**Comment by pamoroso** [comment]
Concerning performance, what about "three orders of magnitude faster on a Raspberry Pi..."?

**Comment by masinter** [comment]
I meant to say "than on a Dorado in 1985" but I don't really know.
See https://github.com/Interlisp/medley/issues/1067

**Comment by phantomics** [comment]
I've made these changes to the front page along with my own edited paraphrase of the text drafts you created.

**Comment by phantomics** [comment]
This is resolved.
