### ISSUE TITLE
bottom Icons and their associated texts, order

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1404]
I think in the previous pe-merge web site, the three stacks

The Project Try Medley -/ History of Interlisp -

Shouldn't the order match the top?

History // The Project // Try Medley

I find it disconcerting that the buttons are different than the stack titles ... History of Interlisp vs History, Try Medley vs. Running Medley, The Project vs Get Involved.

And because the text under "Try Medley" is one more line, the buttons don't line up.

Maybe for now we should abandon the stack? 

if we put just a little more context into the explanation, it will shorten the navigation.

* "History"  The history of Interlisp and Medley development, and applications written in and for it, with an extensive bibliography of published and original documents, documentation, photos, brocures. 

* "Project" -  Who we are, what we've done, our plans for the future, ways you can get involved.

* "Try Medley":  How to run Medley "in the cloud" (on our servers) or install it on popular platforms, or build it for new ones.

**Comment by phantomics** [comment]
This is resolved.
