### ISSUE TITLE
Tweaking the "credits" page

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1409]
I think it's important to give credit where due, especially in a project of (almost) all volunteers.
And the place to do that is the credits page.   I've tried rewriting this several times, and given conflicting directions.  Here's a take where I have forgotten Peter / ecraven's name (contributed the SDL port) and devhawala (Dodo network and crucial patch to allow cygwin-based Windows), and probably a few others.

I think we could add a hyperlink to each name, linking to their github personal page; that would be uniform and you have complete control over how much privacy you want.

---
title: Credits
weight: 80
type: docs
---
Interlisp was a joint effort of many people -- perhaps a hundred -- from its initial beginnings through its heyday to its virtual disappearance. There are more than we can enumerate or name. There were contributions by employees of BBN, Xerox, and Fuji Xerox and later, employees of Envos and Venue. There are initials in the source code with date of last edit, but who wrote what is sometimes a mystery. We do have a list of those we remember who are no longer with us [In Memoriam](/medley/history/in-memoriam).

The Medley Interlisp Project had its origin in an effort by Nick Briggs and Ron Kaplan to get the virtual machine emulator (Maiko) to run on a newer MacOS; the goal was to let Ron continue to use it for linguistics research. Joined by Larry Masinter in 2020, the project evolved. Starting with a mailing list, private GitLab repository, DropBox folder, occasional emails. The project has grown and evolved, and continues to gain momentum. The modern contributors are also difficult to enumerate, but a list of contributors should include at
least these names:

Larry Masinter, Ron Kaplan, Nick Briggs, Frank Halasz, Herb Jellinek, Steve Kaisler, Wayne Marci, Paul McJones, Bruce Mitchener, John Cowan, Arun Welch, Michele Denber, Blake McBride, Abe Jellinek, Bill Stumbo, Matt Heffron, Eric Kaltman, Paolo Amoroso, Andrew Sengul, as well as pseudonymous ecraven and devhwala.

---
Another way of looking at contributors is to look at statistics for the [Medley](https://github.com/Interlisp/medley/graphs/contributors), [Maiko](https://github.com/Interlisp/maiko/graphs/contributors), [online](https::/github.com/Interlisp/online/graphs/contributors), and [website](https://github.com/Interlisp/Interlisp/Interlisp.github.io/graphs/contributors) repos.

**Comment by nbriggs** [comment]
I fixed Ron's name in the list of contributors.

**Comment by phantomics** [comment]
The last thing to be done here is to link people's names to their Github profiles, Larry is sending me their names formatted for Markdown.

**Comment by masinter** [comment]
[Abe Jellinek](https://github.com/AbeJellinek)
[Arun Welch](https://github.com/Anzus)
[ecraven](https://github.com/ecraven)
[Eric Kaltman](https://github.com/ekaltman)
[Frank Halasz](https://github.com/fghalasz)
[Herb Jellinek](https://github.com/hjellinek)
[Larry Masinter](https://github.com/masinter)
[Matt Heffron](https://github.com/MattHeffron)
[Nick Briggs](https://github.com/nbriggs)
[Paolo Amoroso](https://github.com/pamoroso)
[Andrew Sengul](https://github.com/phantomics)
[John D. Corbett](https://github.com/pictographer)
[Paul McJones](https://github.com/pmcjones)
[Ron Kaplan](https://github.com/rmkaplan)
[Steve Kaisler](https://github.com/skaisler1)
[Bill Stumbo](https://github.com/stumbo)
[Bruce Mitchener](https://github.com/waywardmonkeys)
[Wayne Marci]()

**Comment by masinter** [comment]
fixed a while ago

**Comment by masinter** [comment]
fixed a while ago
