### ISSUE TITLE
INTERPRESS odd initialization

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1415]
It's been there since the KOTO release (From the PARC CHM archives):

KOTO

![image](https://github.com/Interlisp/medley/assets/1116587/f394252f-9e59-4f45-a388-4654db04d040)

1993
![image](https://github.com/Interlisp/medley/assets/1116587/8de7235a-c839-441f-99c9-76977c40c13c)

1999

![image](https://github.com/Interlisp/medley/assets/1116587/c2e441cf-36dd-491e-bc6a-caccafc13eba)
QQW

**Comment by rmkaplan** [comment]
Doesn't surprise me.  I think the empty entries are no-ops.  Some of the mappings were not correct, MATH wasn't there.  I cleaned it up in the PR I just put out. #1413

**Comment by rmkaplan** [comment]
INTERPRESS defines two mappings from Ascii font characters to NS characters (in the function \INTERPRESSINIT)

\ASCIITONS
\ASCIITOSTAR

The code commends:
;; "Map from ASCII to wedged OSD screen & .WD file character coding (alleged to be XC2-x-x, soon to come).  The difference [between \ASCIITONS and \ASCIITOSTAR] is that `-' maps to itself for width purposes."

\ASCIITONS maps hyphen (45 called "neutral" in the table) to 41,176 (called hyphen), \ASCIITOSTAR leaves it alone, 45 says at 45.

If I map 45 in Gacha, Timesroman, Helvetica, to 41,176 I see black boxes in the PDFproduced from the postscript.  So, is \ASCIITOSTAR really the right mapping to use?
