### ISSUE TITLE
Grouping related PDFs into subfolders in Google Drive storage area

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1437]
**Is your feature request related to a problem? Please describe.**
The file storage area on the shared Medley project Google Drive holds lots of documentation files in PDF format under [Interlisp > medley-pdfs](https://drive.google.com/drive/folders/10ZBQty5gEwdBnZHtEbXfe5f1dHGziGZG?usp=drive_link) and its subfolders.

While many such documents are available as single PDF files, several are split into dozens of related PDF files such as the chapters of a manual. For example, under [Interlisp > medley-pdfs > loops-pdfs](https://drive.google.com/drive/folders/1unq6LRNsiNe8JfRH0CmMGC-gGVSs7oax?usp=drive_link) the *LOOPS Library Modules Manual* is split into the series of files named `doc-library*.PDF` and the *LOOPS Reference Manual* into the files `doc-REFMAN*.PDF`. Likewise, under  [Interlisp > medley-pdfs > medley-pdfs](https://drive.google.com/drive/folders/1z6Uh021UA9gKLmMi8e-JYT0h0KsKkLZI?usp=drive_link) the *LISPUSERS’ MODULES MANUAL* is split into the files `lispusers-*.PDF`.

This makes it impractical to link to a specific document as a unit. The folders that hold the files typically contain hundreds of PDFs, thus making it difficult for someone unfamiliar with the project to figure which files belong to which document.

**Describe the solution you'd like**
I propose to create a subfolder for every document that is split into multiple parts and move all the related PDFs into the subfolder. For example, for the *LOOPS Library Modules Manual* I'd create a subfolder Interlisp > medley-pdfs > loops-pdfs > loops-library-modules and move all the `doc-library*.PDF` files to the loops-library-modules subfolder.

This would make it possible to link to the loops-library-modules subfolder to refer to the whole document, for example from the documentation catalog or the project site, and the subfolder would unambiguously group all the relevant files.

Easier and faster browsing of the folder hierarchy would be an additional benefit.

**Describe alternatives you've considered**
An alternative is to produce the documents as individual PDF files containing all the relevant parts, but this is a longer term solution that requires more work.

**Additional context**
We discussed the issue in the Medley External Weekly meeting of November 29, 2023 and @masinter suggested that I open this issue.

**Comment by pamoroso** [comment]
Automating the document production and storage to a permanent location is a better medium to long term solution, so I'll tag this issue `wontfix` and close it.

**Comment by masinter** [comment]
it should be possible to cite a document in a way that can access either the latest or a particular version, depending on the needs of the citation.
