### ISSUE TITLE
FONTCREATE fails on font in FONTSAVAILABLE

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#144]
even on case-insensitive file systems.

The weird problem I’m having with them is that 
(FONTSAVAILABLE ‘PALATINO 9 ‘MRR 0 ‘DISPLAY T) returns the expected
((PALATINO 9 0 (MEDIUM REGULAR REGULAR) DISPLAY))
but
(FONTCREATE ‘PALATINO 9 ‘MRR 0 ‘DISPLAY ) returns the NIL instead of a font descriptor, and therefore none of the TEDIT files with that font will load.

_Originally posted by @Anzus in https://github.com/Interlisp/medley/issues/142#issuecomment-757409414_

**Comment by masinter** [comment]
I'm having trouble getting FONTSAVAILABLE to return anything. Want to know more about your setup @Anzus did you move/rename any font files from the current master branch? what is DISPLAYFONTDIRECTORIES in your init?
There's a FLG that controls how fonts are found (somethingOLDsomethingFLG).

**Comment by Anzus** [comment]
I've got DISPLAYFONTDIRECTORIES set to  '("{DSK}~/interlisp/medley/fonts/displayfonts/"
"{DSK}~/interlisp/medley/fonts/adobe/")). 
Now that the fonts are in c0, I uppercased the filenames, and both FONTSAVAILABLE and  FONTCREATE are working correctly.

**Comment by nbriggs** [comment]
The program text works best in these comments if you use backquotes around it... `'("{dsk}/foo/bar/baz")`

**Comment by Anzus** [comment]
Ah, dang, I forget. Fixed.
