### ISSUE TITLE
register article after Steve's talk 

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1452]
### What type of entry?

Other

### Link to entry

https://www.theregister.com/2023/11/23/medley_interlisp_revival/?td=rt-3a

### Additional information

pointer to follow up groups

**Comment by pamoroso** [comment]
The article was [linked from the project site](https://interlisp.org/project/comments/#news-articles-and-reporting), so the issue may be closed.

**Comment by pamoroso** [comment]
Closed as completed.
