### ISSUE TITLE
grammar errors in Interlisp.github.io pages

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1453]
The following files include `. And` and should be rewritten.

```
./content/ol/medley/using/running/running-on-win.md
./content/ol/medley/about/comments/stories.md
./content/ol/medley/project/vocabulary/_index.md
./content/ol/medley/project/_index.md
./content/en/software/install-and-run/running-wsl.md
./content/en/project/stories.md
./content/en/project/_index.md
./content/en/history/glossary/_index.md
```

**Comment by masinter** [comment]
something got lost in your message... what is it they include?
I see `<backquote> <period> <space> <caoital letter A> <letter n> <letter>d <backquote>`
(which I had to write with backquotes and preview carefully.

The ol files should go away

**Comment by nbriggs** [comment]
Nothing was missing.  Those are files that contain the text: period, space, capital A, lowercase n, lowercase d.   Sentences should not start with the word "And".

**Comment by masinter** [comment]
fixed in [website PR 185](https://github.com/Interlisp/Interlisp.github.io/pull/185](https://github.com/Interlisp/Interlisp.github.io/pull/185)
