### ISSUE TITLE
Basics documentation not found

### ISSUE THREAD

**Issue by vinc** [Interlisp/medley#1471]
I'm logged in as guest, when I click on the "BASICS" button for the documentation I get a link to this page: https://interlisp.org/docs/medley/orientation/

![Screenshot 2023-12-21 at 14-16-38 Interlisp Online](https://github.com/Interlisp/medley/assets/305625/2b3fd9e1-e52f-4f91-90eb-4b13df0e5985)

But the page is not found:

![Screenshot 2023-12-21 at 14-18-25 404 Page not found](https://github.com/Interlisp/medley/assets/305625/839e07bc-69f4-4c62-b768-acc0b92394c3)

**Comment by pamoroso** [comment]
Until the issue is fixed, as a workaround you can access the same documents here:

* [Basics](https://interlisp.org/software/using-medley/cl-using)
* [Primer](https://interlisp.org/documentation/Medley-Primer.pdf)

**Comment by vinc** [comment]
Thanks!

**Comment by masinter** [comment]
I fixed the web site to redirect from the old location to the new.
I submitted a PR to update ONLINE-INIT to use the new location.
https://github.com/Interlisp/online/pull/45
