### ISSUE TITLE
Failure when running loadup-full.sh

### ISSUE THREAD

**Issue by blakemcbride** [Interlisp/medley#1472]
**Describe the bug**

I cloned the latest maiko and medly repos.  Maiko built fine.  I then tried to run the loadup-full.sh script as follows:

```
[blake@i9-tower medley.git]$ scripts/loadup-full.sh 
>>>>> START loadup-init
sysout /home/blake/Backup/Medley/medley.git/internal/loadups/starter.sysout
running: lde   -g 1042x790 -sc 1024x768 -title "Medley Interlisp" -m 256  /home/blake/Backup/Medley/medley.git/internal/loadups/starter.sysout
greet: /tmp/loadups-369295/loadup-init.cm
+++++ SUCCESS +++++
..... files created .....
-rw-r--r--. 1 blake blake 4316160 Dec 21 18:57 /tmp/loadups-369295/init.dlinit
-rw-r--r--. 1 blake blake 118312 Dec 21 18:57 /tmp/loadups-369295/init.dribble
-rw-r--r--. 1 blake blake 4169728 Dec 21 18:57 /tmp/loadups-369295/init.sysout
-rw-r--r--. 1 blake blake 55806 Dec 21 18:57 /tmp/loadups-369295/RDSYS
-rw-r--r--. 1 blake blake 42971 Dec 21 18:57 /tmp/loadups-369295/RDSYS.LCOM
-rw-r--r--. 1 blake blake 89163 Dec 21 18:57 /tmp/loadups-369295/I-NEW
-rw-r--r--. 1 blake blake 70635 Dec 21 18:57 /tmp/loadups-369295/I-NEW.LCOM
<<<<< END loadup-init

>>>>> START loadup-mid-from-init
sysout /tmp/loadups-369295/init.dlinit
Could not find 'lde' on PATH
nor MAIKODIR with 'bin/osversion' (to look for it)
----- FAILURE -----
..... files created .....
ls: cannot access '/tmp/loadups-369295/init-mid.sysout': No such file or directory
<<<<< END loadup-mid-from-init

----- loadup-full.sh: FAILURE -----
[blake@i9-tower medley.git]$  cd /tmp/loadups-369295/
[blake@i9-tower loadups-369295]$ ls -l
total 8664
-rw-r--r--. 1 blake blake   89163 Dec 21 18:57 I-NEW
-rw-r--r--. 1 blake blake   70635 Dec 21 18:57 I-NEW.LCOM
-rw-r--r--. 1 blake blake 4316160 Dec 21 18:57 init.dlinit
-rw-r--r--. 1 blake blake  118312 Dec 21 18:57 init.dribble
-rw-r--r--. 1 blake blake 4169728 Dec 21 18:57 init.sysout
-rw-r--r--. 1 blake blake       0 Dec 21 18:58 loadup.timestamp
-rw-r--r--. 1 blake blake   55806 Dec 21 18:57 RDSYS
-rw-r--r--. 1 blake blake   42971 Dec 21 18:57 RDSYS.LCOM
[blake@i9-tower loadups-369295]$ 
[blake@i9-tower medley.git]$ echo $PATH
/home/blake/bin:/home/blake/bin:/home/blake/.local/bin:/home/blake/bin:/usr/local/bin:/usr/bin:/bin:/home/blake/.local/share/JetBrains/Toolbox/scripts:/usr/local/sbin:/usr/sbin:/home/blake/.dotnet/tools:/opt/plan9port/bin:/opt/icon/bin:/opt/groovy-4.0.12/bin:/home/blake/.local/share/JetBrains/Toolbox/scripts:/opt/plan9port/bin:/opt/icon/bin:/opt/groovy-4.0.12/bin:/home/blake/Backup/Medley/maiko.git/linux.x86_64
[blake@i9-tower medley.git]$ ls -l /home/blake/Backup/Medley/maiko.git/linux.x86_64
total 2176
-rwxr-xr-x. 1 blake blake  212080 Dec 20 02:48 lde
-rwxr-xr-x. 1 blake blake 2014816 Dec 20 02:49 ldex
[blake@i9-tower medley.git]$ 
```

**To Reproduce**
1. shown above

**Expected behavior**

The creation of a full sysout.

**Screenshots**

Output shown above.

**Context (please complete the following information):**
 - OS: Fedora Linux
 - OS Version: 38
 - Host arch: x86_64
 - Maiko version: d933ba88b7abaf02a25527ade4960a514832f70a
 - IL:MAKESYSDATE: latest git update
 - 
**Additional context**

It is saying "Could not find 'lde' on PATH" but it is as I show above.

**Comment by nbriggs** [comment]
Setting of PATH ? Did all of lde, ldex (or ldesdl) and ldeinit get built?  (./makeright x (or sdl) and ./makeright init)

**Comment by blakemcbride** [comment]
Maiko built fine as far as I can tell.  When I run load-full.sh medley comes up and runs a bunch of the script.  It just doesn't complete.

**Comment by blakemcbride** [comment]
I saw the PATH error after my original post.  I corrected it but got the same error.

**Comment by nbriggs** [comment]
Ah, no `ldeinit` - if you're doing loadups then you need to do (in the maiko.git/bin directory) `./makeright init` as well as the `./makeright x`.

**Comment by blakemcbride** [comment]
Thanks, Nick!  I wasn't aware of the `./makeright init`.  That fixed it!

**Comment by blakemcbride** [comment]
One think I did notice during the build was the following two cross-line errors.  (/tmp and medley are on the same mount.)

```
<<<<< END loadup-full-from-lisp

>>>>> START copy-full
ln: failed to create hard link '/home/blake/Backup/Medley/medley.git/loadups/full.sysout' => '/tmp/loadups-370907/full.sysout': Invalid cross-device link
Added full.sysout to loadups
ln: failed to create hard link '/home/blake/Backup/Medley/medley.git/loadups/lisp.sysout' => '/tmp/loadups-370907/lisp.sysout': Invalid cross-device link
Added lisp.sysout to loadups
ln: failed to create hard link '/home/blake/Backup/Medley/medley.git/loadups/init.dribble' => '/tmp/loadups-370907/init.dribble': Invalid cross-device link
Added init.dribble to loadups
ln: failed to create hard link '/home/blake/Backup/Medley/medley.git/loadups/lisp.dribble' => '/tmp/loadups-370907/lisp.dribble': Invalid cross-device link
Added lisp.dribble to loadups
ln: failed to create hard link '/home/blake/Backup/Medley/medley.git/loadups/full.dribble' => '/tmp/loadups-370907/full.dribble': Invalid cross-device link
Added full.dribble to loadups
ln: failed to create hard link 'library/RDSYS' => '/tmp/loadups-370907/RDSYS': Invalid cross-device link
Added RDSYS to library
ln: failed to create hard link 'library/RDSYS.LCOM' => '/tmp/loadups-370907/RDSYS.LCOM': Invalid cross-device link
Added RDSYS.LCOM to library
<<<<< END copy-full

+++++ loadup-full.sh: SUCCESS +++++
```

**Comment by blakemcbride** [comment]
Actually, it didn't work:
```
[blake@i9-tower medley.git]$ find . -name '*.sysout'
./internal/loadups/starter.sysout
[blake@i9-tower medley.git]$ 
```

**Comment by nbriggs** [comment]
Hmm, could you attach the output of `df /tmp` and `df /home/blake/Backup/Medley/medley.git`  The scripts try to do a `cp` if it thinks they're not on the same file system and `ln` if they are.  Clearly it got it wrong!  (It's the `medley/scripts/cpv` script)

**Comment by blakemcbride** [comment]
Also:
```
[blake@i9-tower tmp]$ find /tmp -name '*.sysout'
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-systemd-oomd.service-Oavxkt’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-systemd-resolved.service-4zIXZD’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-dbus-broker.service-sDp7V5’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-chronyd.service-jrrvlt’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-rtkit-daemon.service-fVkLJR’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-switcheroo-control.service-x3iImm’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-systemd-logind.service-dgDYfJ’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-upower.service-jdjlNK’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-ModemManager.service-P1Oywj’: Permission denied
find: ‘/tmp/vmware-root’: Permission denied
find: ‘/tmp/systemd-private-9d1ad676205345fea698834841d90cd6-colord.service-J8q9WT’: Permission denied
find: ‘/tmp/runtime-root’: Permission denied
/tmp/loadups-369295/init.sysout
/tmp/loadups-370102/init.sysout
/tmp/loadups-370907/init.sysout
/tmp/loadups-370907/init-mid.sysout
/tmp/loadups-370907/lisp.sysout
/tmp/loadups-370907/full.sysout
```

**Comment by nbriggs** [comment]
Yeah, those are the sysouts you want -- that much worked, but when the `cpv` didn't figure out the cross-filesystem stuff the copy failed.  You can copy the new `lisp.sysout` and `full.sysout` to loadups and you *should* be good to go.

**Comment by blakemcbride** [comment]
```
[blake@i9-tower tmp]$ df /tmp
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
/dev/dm-0       2.3T  869G  1.5T  38% /
/dev/dm-0       2.3T  869G  1.5T  38% /home
/dev/nvme1n1p2  974M  324M  583M  36% /boot
/dev/sda        916G  607G  263G  70% /drive
/dev/sdb        2.7T  1.8T  774G  71% /run/media/blake/94cef597-6492-49e7-ab3e-b7530d37ad32
[blake@i9-tower tmp]$ df /home/blake/Backup/Medley/medley.git/
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
/dev/dm-0       2.3T  869G  1.5T  38% /
/dev/dm-0       2.3T  869G  1.5T  38% /home
/dev/nvme1n1p2  974M  324M  583M  36% /boot
/dev/sda        916G  607G  263G  70% /drive
/dev/sdb        2.7T  1.8T  774G  71% /run/media/blake/94cef597-6492-49e7-ab3e-b7530d37ad32
[blake@i9-tower tmp]$ 
```

**Comment by blakemcbride** [comment]
Yes.  Copying the two sysout files to loadups did work.  Medley is running now.  Thanks!

**Comment by nbriggs** [comment]
OK, that's weird -- `df /directory` should return ONLY the information for the device on which that directory is mounted, not all of them, e.g., (FreeBSD)
```
flap% df /tmp
Filesystem 1K-blocks Used   Avail Capacity  Mounted on
tmpfs        2955592 8664 2946928     0%    /tmp
flap% df /home/briggs
Filesystem   1K-blocks     Used   Avail Capacity  Mounted on
/dev/ada0s1a  53823292 43967160 5550272    89%    /
```
What OS is this?

**Comment by nbriggs** [comment]
I see back at the beginning you said "Fedora Linux" version 38.  I wonder what they've done to `df`.  Sigh.

**Comment by blakemcbride** [comment]
It's Fedora BUT I have two different drives that are treated as one by btrfs.

**Comment by blakemcbride** [comment]
```
[blake@i9-tower medley.git]$ pwd
/home/blake/Backup/Medley/medley.git
[blake@i9-tower medley.git]$ touch /tmp/abc
[blake@i9-tower medley.git]$ ln /tmp/abc .
ln: failed to create hard link './abc' => '/tmp/abc': Invalid cross-device link
[blake@i9-tower medley.git]$ 
```

**Comment by blakemcbride** [comment]
Looks like a bug/shortcoming of btrfs.

**Comment by nbriggs** [comment]
Uh oh - so it looks like one to `df` but when it tries to hard-link it still sees them as two.  That's awkward.

**Comment by blakemcbride** [comment]
Yea.  No telling what that'll break!

**Comment by blakemcbride** [comment]
I don't know what this is telling me:
```
[blake@i9-tower medley.git]$ mount |grep btrfs
/dev/mapper/luks-866874c0-6a2a-477b-992d-a7317dc28b80 on / type btrfs (rw,relatime,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/root)
/dev/mapper/luks-866874c0-6a2a-477b-992d-a7317dc28b80 on /home type btrfs (rw,relatime,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home)
[blake@i9-tower medley.git]$ 
```

**Comment by blakemcbride** [comment]
Perhaps it would be easiest of your script always copied the file and then, if you like, remove it from the source.  In other words, to be safe, always copy.

**Comment by nbriggs** [comment]
Ah, neither did I until seconds ago-- it's btrfs subvolumes, one at `subvolid=256` and the other at `subvolid=257` - and you can't make hard links between two subvolumes.

Leave this issue open, and we'll close it when we fix the script to do the right thing.

**Comment by blakemcbride** [comment]
Thanks!

**Comment by nbriggs** [comment]
@fghalasz - it's no longer the case that you can tell whether two directories are on the same file system by looking at the filesystem they're on - `btrfs` file systems have subvolumes with their own distinct inode space but the filesystem they're on appears the same, and you can't hardlink between subvolumes.

**Comment by fghalasz** [comment]
Fixed in PR#1497.  Didn't go the always copy route.  Instead changed cpv to just try hardlinking and if it fails then do a cp.  This avoids the buggy pre-determination of whether hardlinking will work or not.

**Comment by masinter** [comment]
Still problems first loadup in clean clone

**Comment by blakemcbride** [comment]
It worked for me, once I set PATH.

**Comment by fghalasz** [comment]
@blakemcbride  Just FYI, you can, but don't have to, mess with the PATH to get loadups to work.  Loadups use the run-medley script, which looks for Maiko (actually the lde & ldeinit executables) as follows:

1.  lde (ldeinit) on PATH

2.  In the <osversion>.<machinetype> subdirectory of the directory specified by $MAIKODIR

3.  In the <osversion>.<machinetype> subdirectory of the directory specified by $MEDLEYDIR/../maiko/

4. In the <osversion>.<machinetype> subdirectory of the directory specified by $MEDLEYDIR/maiko/

where $MEDLEYDIR is the directory from which you called the loadup script.

It looks like #3 & #4 won't work in your setup because you have the directories named maiko.git rather than just maiko.

**Comment by blakemcbride** [comment]
The documentation should be updated to reflect these requirements otherwise others who lay things out in ways that suit them won't work.

**Comment by masinter** [comment]
> Loadups use the run-medley script, which looks for Maiko (actually the lde & ldeinit executables) as follows:
> 
> 1. lde (ldeinit) on PATH
> 2. In the <osversion>.<machinetype> subdirectory of the directory specified by $MAIKODIR
> 3. In the <osversion>.<machinetype> subdirectory of the directory specified by $MEDLEYDIR/../maiko/
> 4. In the . subdirectory of the directory specified by $MEDLEYDIR/maiko/
> 
> where $MEDLEYDIR is the directory from which you called the loadup script.
> 
> It looks like #3 & #4 won't work in your setup because you have the directories named maiko.git rather than just maiko.

I'll update PR #1507
