### ISSUE TITLE
addendum to #1482

### ISSUE THREAD

**Issue by skaisler1** [Interlisp/medley#1483]
d

**Comment by skaisler1** [comment]
When I click on the window in the secind image in #1482, it expands to a full screen.
Then if try to click on one of the windows in Medley, I get the error below:
![run-medley-error](https://github.com/Interlisp/medley/assets/39410155/7f63fcdf-7d39-481f-8d7f-6c26bb8c28c7)

The only thing I can do is cancel the error window.
If I try to get the background menu, I can open Dinfo to show the IRM graph.
But, it takes a while for this behavior to manifest itself.

This does not affect Windows 10, but does in Windows 11.

There is no way to dynamically resize the screen window by dragging a corner. 
It would be a nice feature to add "Resize Screen" to the background menu as a capability.

There is a 'size' operation in the title bar menu, but it is grayed out. Perhaps that was planned for dynamically resizing the screen.

**Comment by fghalasz** [comment]
I am not sure what is going on here.  On my Win11 instances, double clicking anywhere in the Medley window does not maximize the Window and in fact maximize is greyed out in the title bar menu.  

The error dialog shown does not appear to be related to Medley as far as I can tell.

Right now Medley's internal screensize cannot change dynamically.  In X Windows based versions of Medley, you can resize the Window but this will just show more or less of the Medley screen and not actually change the Medley screensize.  This appears to be a bit different in SDL based versions, where the Window is not resizeable.  This difference between X and SDL is something that needs to be reconciled.

**Comment by masinter** [comment]
@skaisler1 We use issue tracking to organize the group work, because it doesn't work like a mailing list. If you have an addendum to a problem report or a new perspective, add a comment to the already submitted issue, rather than creating a new issue.
