### ISSUE TITLE
Medley doesn't treat Caps-Lock + Shift like Windows and Ubuntu do

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1486]
**Describe the bug**
Medley capitalizes letters if `Caps-Lock` is set **OR** _either_ `Shift` key is down. Windows and Ubuntu use an **XOR** between those, so that `Shift` _un-shifts_ if `Caps-Lock` is set. (And others? mac?)

**To Reproduce**
1. Clear the `Caps-Lock` mode on the keyboard.
2. Start a medley sysout.
3. Type `abc` in an Exec window.
4. Press the `Caps-Lock` key to set that _mode_.
5. Type `def` in the Exec window.
6. Press and hold either `Shift` key.
7. Type `ghi` in the Exec window.
8. Notice that the characters typed are entered as `abcDEFGHI`

**Expected behavior**
The characters typed would be entered as: `abcDEFghi`

**Context (please complete the following information):**
 - OS: Win 11 WSL Ubuntu
 - OS Version: Ubuntu 22.04.3
 - Host arch: x86_64
 - Maiko version: -not a maiko issue-

**Additional context**
This is in LLKEY in `\DECODETRANSITION`, as well as `SHIFTORLOCK` in the `BLOCKRECORD KEYBOARDEVENT`, and in `SHIFTDOWNP`.

**Comment by nbriggs** [comment]
I don't think that's a bug, I think it's the way Interlisp has always worked.  Shift does not turn into un-shift on the Mac (in any application) when caps-lock is on, either.

**Comment by nbriggs** [comment]
I wondered if it was in the keyboard hardware - but I think it's an OS thing, for the OS that is decoding the keyboard - a USB keyboard plugged in to my mac behaves as my builtin laptop keyboard (no un-shift), but plug the same keyboard into a FreeBSD 14.0 box and it does do un-shift.
It might be nice to have it as an option for those that are used to typing that way, but I wouldn't make it permanently that way.

**Comment by nbriggs** [comment]
BTW - when you were testing Ubuntu, were you doing it on a keyboard connected directly to the Ubuntu system, or ssh'd in from your Windows PC, or with WSL providing the Ubuntu?

**Comment by MattHeffron** [comment]
Making this optional should be pretty straightforward.
(Any suggestion on the name of the Lisp global variable to control this?)

I tested the Ubuntu **both** under WSL, and as the native OS on a laptop with the laptop's own keyboard.

**Comment by nbriggs** [comment]
`SHIFTXORLOCKFLG` ? NIL => old behavior, T => new behavior

**Comment by MattHeffron** [comment]
> `SHIFTXORLOCKFLG` ? NIL => old behavior, T => new behavior
What I went with (but could be changed) is `KEYBOARD.SHIFTXORLOCK` initialized to NIL

**Comment by nbriggs** [comment]
I don't think we have any other user-settable flag-type global variables that have a naming pattern like `KEYBOARD.SHIFTXORLOCK`, while we have a ton of `fooFLG`.  Common Lisp introduced leading/trailing `*` for globals, but this isn't Common Lisp related.
