### ISSUE TITLE
Build instructions #2

### ISSUE THREAD

**Issue by blakemcbride** [Interlisp/medley#1499]
**Errors happen. Please tell us the URL**

BUILDING.md

**What does it say?**

How to build a medley release

Originally done only with shell scripts:

./scripts/loadup-all.sh 

to make the loadups

./scripts/loadup-and-release.sh

to go on to make the tgz files and release them

**What should it say?**

To build medley:

./scripts/loadup-all.sh 

To build medley and create a release:

./scripts/loadup-and-release.sh

**Comments**

To me, a "release" is a package used to send to others.  To "build" means to build what I need to run it.  Sorry.  I just found it confusing.

**Comment by masinter** [comment]
we're not doing releases by hand any more -- all done with GutHub Actions. Once I got there, I realized I don't think I'd written down how the loadups are built and what's going on. So I started on that
PR #1507
