### ISSUE TITLE
cpv problems in loadup scripts

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1505]
pr #1500  isn't enough. If you start with a clean clone of medley (no loadups directory), it fails.
If there's already loadups and you're just doing another one, it works fine.

_Originally posted by @masinter in https://github.com/Interlisp/medley/issues/1500#issuecomment-1890558871_

**Comment by fghalasz** [comment]
@masinter I can't replicate your problem.  If I clone the latest master (ab818ff, which include PR#1500), then loadup-all.sh works fine the first time (when loadups dir doesn't exist) and every time thereafter (when loadups dir already exists).  Same for loadup-full.sh.

Can you send me a terminal transcript from your failed runs so I can track this down.

**Comment by MattHeffron** [comment]
Was this resolved?

**Comment by masinter** [comment]
can't reproduce, might have been pilot error. Closing.
