### ISSUE TITLE
Hyphenate file names in library/lafite/

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1509]
Except for LAFITE-INDENT, none of the filenames in the lafite subdirectory conform to the hyphenated filename convention uses by TEDIT, TMAX, and now SKETCH.

It appears that, as a consequence, the lafite files are not analyzed when the whole-system masterscope database is constructed.  And functions on them are not found by WHEREIS unless connected to that subdirectory.

The hyphen convention has proven to be useful and robust.  I propose renaming the Lafite files according to this convention.

**Comment by masinter** [comment]
i'm uneasy about this special rule ... but can we write it up in the README for the medley repo?

**Comment by rmkaplan** [comment]
Unless we come up with a better solution for organizing all the subfiles of a larger application, I think this is effective and good enough.  An additional important advantage of having all such files in a separate subdirectory is that you have a natural way of focusing the targets of FB, FINDCALLERS, EDITCALLERS.

**Comment by rmkaplan** [comment]
The file LAFITE has a variable LAFITEFILES that includes OLDNSMAIL as well as NSMAIL and NEWNSMAIL.

The files that Lafite actually loads are specified elsewhere, so this list may just be away of setting up a Lafite development environment.

But OLDNSMAIL doesn't appear to exist.  Is that just a hangover from an early phase?

**Comment by MattHeffron** [comment]
This looks like it has been done. (hyphenation of file names)
If so, please close as complete.

**Comment by rmkaplan** [comment]
Completed and closed

**Comment by nbriggs** [comment]
lispusers/UNDIGESTIFY was not updated to refer to LAFITE-DECLS instead of LAFITEDECLS.

**Comment by rmkaplan** [comment]
Oops, new pr makes the change.
