### ISSUE TITLE
commit ec04803 broke sunos5 sparc

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#152]
This is very peculiar -- I hadn't been able to build on Solaris 11.4/sparc for a while, but that functionality is now restored and testing today shows a failure on startup starting at ec04803 -- Switch `s_char` uses to `signed char`. Remove s_char alias. (#208) -- but it's really not obvious what's wrong with that change.

**Comment by nbriggs** [comment]
So here's the deal --

```
#include <stdio.h>
#include <stdint.h>

int main(int argc, char *argv[])
{
typedef char ByteCode;
typedef ByteCode *InstPtr;
register InstPtr pccache;

 char codestream[4]= "\000\177\200\377"; 
 #ifdef _CHAR_IS_SIGNED
 printf("char is signed\n");
 #else
 printf("char is NOT signed\n");
 #endif
 for (int i = 0; i < 4; i++) {
   pccache = &codestream[i];
   printf("%d %d\n", (* ((signed char *)(pccache))), (* ((int8_t *)(pccache))));
 }
}
```
and
```
briggs@hemlock:~/maiko/bin$ cc -o /tmp/test /tmp/test.c -O2
briggs@hemlock:~/maiko/bin$ /tmp/test
char is signed
0 0
127 127
-128 -128
-1 -1
```
however
```
briggs@hemlock:~/maiko/bin$ cc -o /tmp/test /tmp/test.c -O2 -funsigned-char
briggs@hemlock:~/maiko/bin$ /tmp/test
char is signed
0 0
127 127
-128 128
-1 255
```
and the misinterpretation of the int8_t happens because in /usr/include/sys/int_types.h
```
#if defined(_CHAR_IS_SIGNED)
typedef char                    int8_t;
#else
#if defined(__STDC__)
typedef signed char             int8_t;
#endif
#endif
```

**Comment by nbriggs** [comment]
/*
      * Basic / Extended integer types
      *
      * The following defines the basic fixed-size integer types.
      *
      * Implementations are free to typedef them to Standard C integer types or
      * extensions that they support. If an implementation does not support one
      * of the particular integer data types below, then it should not define the
      * typedefs and macros corresponding to that data type.  Note that int8_t
      * is not defined in -Xs mode on ISAs for which the ABI specifies "char"
      * as an unsigned entity because there is no way to define an eight bit
      * signed integral.
      */

**Comment by nbriggs** [comment]
And the `/usr/include/sys/isa_defs.h` says that for Solaris on SPARC, always `#define _CHAR_IS_SIGNED`.  So we need to remove -funsigned-char and deal with any fallout from that on a case-by-case basis.  I *think* that over time I have actually found all of them and and added explicit "unsigned" or "signed", but we'll need to keep an eye open for any cases I've missed.

**Comment by waywardmonkeys** [comment]
Not feeling sad about your change in the linked commit at all. :) I didn't like what we were doing with `-funsigned-char` and hoped we could do away with it one day.
