### ISSUE TITLE
Maiko/emscripten: unsupported syscall: __syscall_getrusage

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1537]
In the browser console when running emscripten maiko/medley, you get a message printed every second or so saying `unsupported syscall: __syscall_getrusage`.  At first glance this doesn't appear to affect any functionality - but it is probably slowing things down a bit.

![image](https://github.com/Interlisp/medley/assets/1251539/48c3f017-ffa4-4a1f-bf3d-d3ed290fa21f)

**Comment by nbriggs** [comment]
Closed by merge of interlisp/maiko#490
