### ISSUE TITLE
Tedit-4th-round: PUTing empty file results in break

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1577]
In 4th-round:  open new TEdit file (e.g., using (TEDIT)) then immediately PUT it  and answering Yes to question about putting an empty file.  It breaks.

![image](https://github.com/Interlisp/medley/assets/1251539/dae15b96-3453-474c-8b16-e5a04752e193)

**Comment by rmkaplan** [comment]
Fixed in new commit

**Comment by fghalasz** [comment]
Fixed with TEdit-4th round checkin
