### ISSUE TITLE
can't UNDO a simple edit

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1583]
in current Master, if I TEDIT(<a file name>) for some existing file, and type in 1 character, it gives me "There is no action whose undoing can be reversed."
but i didn't want to undo an undo.

**Comment by rmkaplan** [comment]
I don’t get that.  Some particular file, or empty?

Are you trying to undo (meta-u)?

I know that undo-undoing of a move isn’t yet quite right.

**Comment by rmkaplan** [comment]
I tried this again in a loadup I made from master.  Tedit of a random file, type in a character at the beginning, the meta-u to undo.  Works fine.

Something else going on?

**Comment by masinter** [comment]
Not sure why but problem went away

**Comment by rmkaplan** [comment]
I could never replicate.  Hope it doesn’t happen again.
