### ISSUE TITLE
add a donate via paypal link to our donate page 

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1619]
![image](https://github.com/Interlisp/medley/assets/1116587/2725c481-f4ee-4cec-ab1a-c0e4462ea45b)

you need a github account to donate without one or this.
need to fill out the form and decide where to add the button.

**Comment by masinter** [comment]
https://www.paypal.com/donate/?hosted_button_id=MCHS5GWLVYLUY

**Comment by pamoroso** [comment]
[PR #223](https://github.com/Interlisp/Interlisp.github.io/pull/223)  addresses this and prepares a template for adding more donation options such as [LiberaPay](https://liberapay.com/) (see an [example project profile](https://en.liberapay.com/Ultralisp.org)).

**Comment by pamoroso** [comment]
If [PR #225](https://github.com/Interlisp/Interlisp.github.io/pull/225) addresses your suggestion this issue may be closed.
