### ISSUE TITLE
PP Seems to have stopped working

### ISSUE THREAD

**Issue by keedon** [Interlisp/medley#163]
**Describe the bug**
The pretty print command now gives this error:
FIle not found: #.(PATHNAME "{DSK}<......>medley>loadups>system.hash;1")

**To Reproduce**
Run the PP command

**Expected behavior**
Pretty print a form

**Screenshots**

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Fedora
 - Host arch: x86_64
 - Maiko version: commit 3b25bc27eea860fe9a48eaf065558b6388e511b9
 - IL:MAKESYSDATE: 14-dec-2020 18:42:28

**Additional context**

**Comment by rmkaplan** [comment]
Larry removed system.hash, presumably whatever it contained is in the new where-is.hash. I had a reference in one of my greeting files that I had to remove.

**Comment by masinter** [comment]
First, thanks for the bug report! I removed the file from the repo after I was sure it was useless, but didn't think about the case where someone pulls a new repo but is still running an older sysout.

system.hash wasn't just old, it had bad data (picked up LCOMs).
* in future, I'll be more careful deleting files from the repo.
* short term workaround   edit the variable XCL::*WHERE-IS-CASH-FILES* and delete the system.hash entry
* another path would be trying to pull loadups/system.hash out from git history 88fac61a47a10165ad59bfe4e10760370bb35861 but I'm not sure how to do that.

**Comment by masinter** [comment]
@keedon if this isn't resolved satisfactorally, please reopen.
