### ISSUE TITLE
Stale or corrupted LCOM files (at least in linux tgz release)

### ISSUE THREAD

**Issue by MarceColl** [Interlisp/medley#1632]
**Describe the bug**

I found that deleting the `NCGUIDEDTOURCARD.LCOM` file fixed an issue (NoteCards tours not working).
It seems some of these files are either stale or corrupted.

**To Reproduce**
1. Load NoteCards and open NCTOUR notefile. Start the tour and press next, the system will break with error `TableTopEntry is an undefined function`.
2. Go to your interlisp installation, and head to notecards/library and delete or rename `NCGUIDEDTOURCARD.LCOM`
3. Close interlisp and reopen, repeat step 1. Now it should work.
![image](https://github.com/Interlisp/medley/assets/1399250/e46d5785-4645-4bed-81c7-a5d52d567d19)

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Linux nixos 6.6.18 1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:25:28 UTC 2024 x86_64 GNU/Linux
 - Host arch: x86_64
 - Maiko version: It's a tar release, don't have access to the git version afaik
 - IL:MAKESYSDATE: 25-Mar-2024 02:03:25

**Additional context**
I posted a thread with a bit more detail here: https://elk.zone/functional.cafe/@dziban/112176205118884318

It can also be reproduced at Online Medley, so it seems it's not a local corruption.

**Comment by fghalasz** [comment]
Fixed in Notecards PR#9 merged on 3/31.  Fix should show up in Medley weekly build on 4/1.

 Recompiled library/NCGUIDEDTOURCARD.  Not sure how it got out of sync.
