### ISSUE TITLE
In TEDIT.PUT missing TEXTOBJ arg in call to TEDIT.PROMPTPRINT

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1635]
TEDIT.PUT is missing TEXTOBJ arg in call to TEDIT.PROMPTPRINT.
![image](https://github.com/Interlisp/medley/assets/1251539/dc3334ef-43dc-4b24-8d3f-30f48e53520b)

**Comment by rmkaplan** [comment]
Fixed in #1857
