### ISSUE TITLE
Debian 10 (buster) cmake too old to build medley

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#164]
```
Package cmake
buster (stable) (devel): cross-platform, open-source make system
3.13.4-1: amd64 arm64 armel armhf i386 mips mips64el mipsel ppc64el s390x
```
but
```
PROJECT(maiko C)
CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
```
are there features that we depend on in 3.15 that can't be implemented with 3.13?

**Comment by waywardmonkeys** [comment]
It is probably safe to adjust that. The only issue is that we don't have a test env to make sure we don't break it. But try just changing it and running the build! I've looked at changelogs and think it'll be fine.

**Comment by waywardmonkeys** [comment]
`buster-backports` and `stretch-backports` both have `cmake` 3.16.x ... is that okay to use?

**Comment by nbriggs** [comment]
Works for me -- created `/etc/apt/sources.list/buster-backports.list` containing
```
deb http://deb.debian.org/debian buster-backports main
```
and installed the updated cmake with `apt install -t buster-backports cmake`
