### ISSUE TITLE
TEDIT Break with "ARG NOT LINEDESCRIPTOR" during SHAPEW of empty file

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1648]
This happens on both Master and rmk7---Names....

(TEDIT) - sweep out region.  When TEdit comes up immediately reshape the window (either by pulling a corner or by using the right button title bar menu).    Results in "ARG NOT LINEDESCRIPTOR" break within \FORMATBLOCK.

Note that if you type in just one character before reshape window - then no break.

![image](https://github.com/Interlisp/medley/assets/1251539/c1b47f19-39dd-4869-9ab1-594805995fb4)

**Comment by fghalasz** [comment]
Clarification: 
Enter one character then reshape window -> no break
Enter one character - then delete it (leaving empty file) - then reshape window -> break

**Comment by rmkaplan** [comment]
That doesn’t happen in my current working directory—it has some additional minor changes that I don’t want to commit until after the renaming rmk7 is merged.

**Comment by rmkaplan** [comment]
Fixed in #1857
