### ISSUE TITLE
TEDIT: Bitmaps in-line with text have width ignored in line formatting for PS printing

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1667]
**Describe the bug**
When printing a TEDIT document to PostScript (or PDF), a bitmap `IMAGEOBJ` in-line with text is being overwritten by following characters in the line and the right margin alignment is _off_ by the bitmap width.

**To Reproduce**
1. Using full.sysout
2. TEDIT("STRESSTEST.TEDIT")
3. Right click menu: Hardcopy > To a file
4. Specify the file name. (For me this defaulted to "STRESSTEST.PS")
5. Use separate application to interpret the PostScript. (Or view PDF directly)
6. Near the bottom of the first page, there is a line: "the left mouse button. The caret shape (^) will appear. Type". The ^ is a bitmap `IMAGEOBJ`. The ") will appear. Type" prints as if the ^ was not there (overwriting it) and causing the right edge to be a bit left of correctly aligned. See screenshot below.

**Expected behavior**
Print formatted consistent with TEDIT display.

**Screenshot**
![image](https://github.com/Interlisp/medley/assets/8261874/83c0cf93-186f-40ae-be3b-839a0c60bf7c)

**Context (please complete the following information):**
 - OS: Win 11 WSL
 - OS Version: Ubuntu
 - Host arch: x86_64
 - Maiko version: ce20acca
 - IL:MAKESYSDATE: [ date ]

**Additional context**
Here is the PostScript code for generated for that line:
```postscript
25800 9420 M (the) S
( left mouse button.  The caret shape \() 60 0 32 4 -1 roll widthshow
/bitbltsave save def 44290 9420 translate 1056.0 480.0 scale 11 5 true thebitimage
60C0
3180
1B00
0E00
0400

bitbltsave restore
(\) will appear.  Type the ) 60 0 32 4 -1 roll widthshow
```
Here is the full PostScript file: 
[STRESSTEST.PS.TXT](https://github.com/Interlisp/medley/files/15018035/STRESSTEST.PS.TXT)

Note that it does not set a new position (no: **X# Y# M**) after the **bitbltsave restore** before the following text.
I set a breakpoint on the `\SCALEDBITBLT.PSC` function and repeated the Hardcopy operation. From the Break I inspected `THISLINE` and found the `CHARSLOTS` with the correct bitmap width (1100) in the correct `CHARW` position for the `IMAGEOBJ`. I did some digging in the code and found that in `\TEDIT.HARDCOPY.DISPLAYLINE` is where an `IMAGEOBJ` is processed. It does update the `TX` with the `CHARW` but there is nothing to indicate that the `DSPXPOSITION` needs to be updated in the stream before more characters are output on the line. (Of course, if the bitmap were the last character of the line everything would appear to be correct.)

![image](https://github.com/Interlisp/medley/assets/8261874/a074f308-144d-43a5-bfb8-b72eb80818b8)

**Comment by MattHeffron** [comment]
I just tried printing that same file to PostScript using the **medley-32112-b2f750e5** release, and the problem **_doesn't_** occur, and there **is** the appropriate move action following the display of the bitmap, before the rest of the text.

Strangely, the corresponding page positions are not _exactly_ the same in the two PostScript files.

Here's the PostScript for the same text as above, as generated by the old release:
```postscript
25800 11620 M (Move the cursor to where you would like the text to be and press) 110 0 32 4 -1 roll widthshow
25800 10420 M (the left mouse button.  The caret shape \() 60 0 32 4 -1 roll widthshow
/bitbltsave save def 44291 10420 translate 1056.0 480.0 scale 11 5 true thebitimage
60C0
3180
1B00
0E00
0400

bitbltsave restore
45390 10420 M (\) will appear.  Type the) 60 0 32 4 -1 roll widthshow
```

**Comment by MattHeffron** [comment]
**Another note:** When opening the STRESSTEST.TEDIT file for the above, it displayed the error (warning?):
`Cannot read image object with GETFN SKIO.GETFN.2`
And then late in the file (about at Figure 38) there are HRULE errors and layout problems

**Comment by rmkaplan** [comment]
Thanks @MattHeffron for the careful diagnosis.  The Xposition is addressed in PR #1668.

I'm not sure about the unknown getfn problem.  That was dealt with some time ago, independent of Tedit, by the heuristic of using the whereis database to find the getfn and load the file that contains it.  So, if this appeared only in the older loadup but not newer ones, I think it can be ignored.  If it it appeared in the current loadup, and the file(s) containing the image object definition are known and are accessible (DIRECTORIES, LISPUSERSDIRECTORIES), then it is something to look at.

I don't have (or don't know where it is, if I have it) the file STRESSTEST.TEDIT, so I can't examine this particular case.

**Comment by MattHeffron** [comment]
The STRESSTEST.TEDIT is in the **envos** repository.
I've zipped and attached it:
[STRESSTEST.zip](https://github.com/Interlisp/medley/files/15044724/STRESSTEST.zip)

**Comment by rmkaplan** [comment]
Thanks.  When I open it, there is no issue with unknown image object getfns.  It loads all the Sketch files automatically, as expected.
