### ISSUE TITLE
scrolling TEDIT window when left side off-screen updates incorrectly

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1677]
Open a TEdit window on some file, move the window so that the left side is off-screen, use the trackpad or mouse wheel to scroll the window - the wrong portion updates.

https://github.com/Interlisp/medley/assets/8138841/5bb8dc0e-5337-475a-8ce8-0be588b9938f

**Comment by pamoroso** [comment]
Is this issue resolved by #1857?

**Comment by rmkaplan** [comment]
Should be

**Comment by rmkaplan** [comment]
Fixed in #1857
