### ISSUE TITLE
cygwin build broke

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#170]
with commit 987c38      Build .o files for executables separately. (#296)
```
clang -m64 -std=gnu99 -fno-strict-aliasing -L/usr/X11/lib -lX11 -lc -lm -lcrypt ../cygwin.x86_64-x/ldeboot.o ../cygwin.x86_64-x/unixfork.o -o ../cygwin.x86_64/lde
/usr/bin/ld: ../cygwin.x86_64-x/ldeboot.o: in function `main':
/cygdrive/c/Users/Larry/home/ilisp/maiko/bin/../src/ldeboot.c:101: undefined reference to `XOpenDisplay'
/cygdrive/c/Users/Larry/home/ilisp/maiko/bin/../src/ldeboot.c:101:(.text+0x9e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `XOpenDisplay'
/usr/bin/ld: /cygdrive/c/Users/Larry/home/ilisp/maiko/bin/../src/ldeboot.c:103: undefined reference to `XCloseDisplay'
/cygdrive/c/Users/Larry/home/ilisp/maiko/bin/../src/ldeboot.c:103:(.text+0xab): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `XCloseDisplay'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makefile-tail:159: ../cygwin.x86_64/lde] Error 1

```

**Comment by waywardmonkeys** [comment]
Interesting! I'll take a look.

**Comment by nbriggs** [comment]
Run the command by hand from the `bin` directory:
```
clang -m64 -std=gnu99 -fno-strict-aliasing -L/usr/X11/lib -lX11 -lc -lm -lcrypt ../cygwin.x86_64-x/ldeboot.o ../cygwin.x86_64-x/unixfork.o -o ../cygwin.x86_64/lde
```
to see it fail again, then try with the libraries after the object files and see if it works (or fails differently)
```
clang -m64 -std=gnu99 -fno-strict-aliasing  ../cygwin.x86_64-x/ldeboot.o ../cygwin.x86_64-x/unixfork.o -o ../cygwin.x86_64/lde  -L/usr/X11/lib -lX11 -lc -lm -lcrypt
```

**Comment by waywardmonkeys** [comment]
@nbriggs That's what I think it is as well. I moved the `LDELDFLAGS` and `LDFLAGS` and `LDEETHERLDFLAGS` variables and probably should not have.

**Comment by nbriggs** [comment]
@waywardmonkeys Do you have a cygwin to test on?  I don't, and if you don't then Larry @masinter is probably the only QA on the cygwin builds :-(   I'm sure someone has a good reason for it, but it's a little annoying that the Cygwin linker seems to behave significantly differently from the LLVM ld, GNU ld, and Solaris ld (IIRC the Cygwin style was how the SunOS 4 linker used to work)

**Comment by waywardmonkeys** [comment]
I've created Interlisp/maiko#313 pending @masinter saying this fixes things.

**Comment by masinter** [comment]
this problem fixed. now there's a different problem with tty


```
clang -m64 -std=gnu99 -fno-strict-aliasing -c -O2 -g3 -DAIX -DBYTESWAP -DLOGINT  -DXWINDOW -DRELEASE=351 -I../inc/ -I../include/ ../src/tty.c -o ../cygwin.x86_64-x/tty.o
../src/tty.c:54:85: error: use of undeclared identifier 'PENDIN'
      options.c_lflag &= ~(ECHO|ECHOE|ECHOK|ECHONL|ICANON|ISIG|IEXTEN|NOFLSH|TOSTOP|PENDIN);
                                                                                    ^
../src/tty.c:123:28: error: use of undeclared identifier 'EXTA'
  if (aBaud == 15) return (EXTA);
                           ^
2 errors generated.
make: *** [makefile-tail:691: ../cygwin.x86_64-x/tty.o] Error 1
```

**Comment by waywardmonkeys** [comment]
I'll submit a PR in about 10 minutes that fixes the `tty.c` compilation issue. It also fixes some other bugs with that file.

**Comment by nbriggs** [comment]
I think EXTA can be B19200 -- they're equivalent on FreeBSD and MacOS at least, I presume cygwin has that one (and it can always be #if defined(...)

**Comment by nbriggs** [comment]
Cygwin is closer to the original hardware -- the speed is a byte and the translation to the defined symbol is an identity operation.  From Cygwin termios.h:
```
[...]
#define B4800	 0x0000c
#define B9600	 0x0000d
#define B19200	 0x0000e
#define B38400	 0x0000f
```

**Comment by waywardmonkeys** [comment]
The whole mapping was wrong given what was in `CHARDEVICE`, so I have corrected it and submitted a PR.
