### ISSUE TITLE
CYGWIN install fail

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1704]
Downloaded 
medley-full-cygwin-x86_64-240502-9f047593_240211-ce20acca.exe
from
https://interlisp.org/software/install-and-run/windows/native/

and going through the dialogs got 

![image](https://github.com/Interlisp/medley/assets/1116587/09c8bcfb-6dcb-4d89-9b65-0ebfced56756)

**Comment by fghalasz** [comment]
Fixed in PR#1707
