### ISSUE TITLE
MANAGER doesn't print function definitions

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1719]
The MANAGER LispUsers module doesn't print function definitions. The output of the MANAGER command `File Manager` > *`FILE-NAME`* > `FUNCTIONS` > *`FUNCTION-NAME`* > `PrettyPrint` > `Function Def`  in the `Manager Command Activity` window contains only this header and the function definition is missing:

```
Function definition of [FUNCTION-NAME]:
------
```

This is similar to issue #1715 but located in the [function definition printing code](https://github.com/Interlisp/medley/blob/6c47d75ab94d6676bf3dad203031436c37424bf5/lispusers/MANAGER#L649). The cause of the bug, a "structural typo", is likely similar as well as the fix in #1716 by @MattHeffron.

**Comment by MattHeffron** [comment]
Fixed in PR #1726
