### ISSUE TITLE
PUPPRINT library is missing

### ISSUE THREAD

**Issue by sethm** [Interlisp/medley#172]
**Describe the bug**

The PUPPRINT library seems to be missing.

**To Reproduce**

To reproduce, open a new Interlisp exec, and load the PRESS library

    (FILESLOAD 'PRESS)

A warning that the file PUPPRINT could not be found is printed.

**Expected behavior**

Expected that the PRESS library should load cleanly.

**Screenshots**

![filesload-press](https://user-images.githubusercontent.com/7471/106961924-23e18380-66f3-11eb-987a-a0e5bd66941e.png)

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Linux Mint 20.1
 - Host arch: x86_64
 - Maiko version: f0a53302ce836aad075a168cb76e4a6b9e9fcd4f
 - IL:MAKESYSDATE: 1-Feb-2021 22:38:08

**Additional context**

Discovered when trying to load the BACKGROUNDIMAGES Lisp Users' Module and determining that it needed PRESS to be loaded first.

**Comment by masinter** [comment]
If you're interested in checking out what's there, see
[this sheet](https://docs.google.com/spreadsheets/d/1pn4UcS-9CgMLi_qeGZlOGGEusAKsNDKxz1XhLwQCgKw/edit#gid=0)
