### ISSUE TITLE
Build fails - can't find Maiko directory despite claiming to check the correct path

### ISSUE THREAD

**Issue by phantomics** [Interlisp/medley#1729]
I'm trying to build Medley using `time ./scripts/loadup-all.sh && time ./scripts/loadup-db.sh` but it fails each time. I get the error:

```
>>>>> START loadup-mid-from-init
ERROR: Cannot find the directory containing the Maiko emulator in either
"/home/user/src/lisp/medley/maiko" or "/home/user/src/lisp/medley/../maiko".
Please use the --maikodir argument to specify the correct Maiko directory.
Exiting.
```

When I run the process a Medley window spawns and prints many messages as it builds things until it fails displaying the text above. I have tried putting the `maiko` directory with a built Maiko binary (path `./linux.x86_64/ldex`) in both of these paths, both in the form of a symlink and as the actual directory. I got the same error message. I tried using the `--maikodor` argument as follows:

```
./scripts/loadup-all.sh --maikodir "/home/user/src/lisp/maiko"
```

When I do this, the `loadup-all.sh` process hangs at the command line, doing nothing until I stop it with `Ctrl-C`. It consumes about 2% of the CPU, noticeable on my system monitor chart, which is interesting. I tried running the command with `--maikodir` pointing to a directory that doesn't exist and the same thing happens, suggesting that this is what `loadup-all.sh` does when it can't find Maiko, silently hanging until forced to quit.

**Context**
 - OS: MX Linux 21.3
 - Linux Kernel: 5.10.0-26-amd64
 - Host arch: x86-64
 - Maiko version: 4becc6ad9368745ad53c6d8b08960462d9c77f42
 - Medley version: 9214a6335a9286cc836daadcac5647b3721d6b25

**Comment by nbriggs** [comment]
Did you makeright init as well as makeright x (or sdl)

**Comment by phantomics** [comment]
The `makeright init` was the key, thanks!

**Comment by phantomics** [comment]
Should instructions to do that be added to Maiko's readme file?

**Comment by nbriggs** [comment]
Probably, but the build scripts should also indicate what the problem is (can’t find ldeinit) rather than saying they can’t find the Maiko directory.

**Comment by nbriggs** [comment]
I set up the cmake builds to build everything-it might be ok to do that for the makeright builds too, it didn’t previously because most people wouldn’t do loadups, and if they did they knew how to do it.  That was 20+ years ago.

**Comment by fghalasz** [comment]
The can't find Maiko directory error message is actually coming from the medley.sh script and not directly from the loadup scripts (which call the medley.sh script).  I will change the medley.sh error message to be more informative.
