### ISSUE TITLE
The charitable deduction page should list the EIN and pointers to the official web sites.

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1732]
the irs.gov website 
the EIN
the email address of the group?

I think -- I need to look up the info  -- it's on the GitHub sponsor page but it isn't on the donate page yet.

**Comment by pamoroso** [comment]
By email address of the group do you mean the address of the treasurer, i.e. Ron? The EIN is on the [GitHub Sponsors page](https://github.com/sponsors/Interlisp).

**Comment by hjellinek** [comment]
@rmkaplan, I'll be happy to take this.
Is that OK with you?

**Comment by hjellinek** [comment]
(I believe this concerns the file `content/en/project/donate.md`.)

**Comment by rmkaplan** [comment]
Sure, I haven’t been involved in maintaining any of the web sites.

Do you have the EIN?

**Comment by hjellinek** [comment]
I do. I'm installing Hugo and will test my edits soon.

**Comment by pamoroso** [comment]
This was addressed by [PR #230](https://github.com/Interlisp/Interlisp.github.io/pull/230).

Is there anything else to do here, such as transferring the treasure's email address as @hjellinek [suggested](https://github.com/Interlisp/medley/issues/1732#issuecomment-2133851944)? Can this issue be closed?

**Comment by hjellinek** [comment]
All done
