### ISSUE TITLE
TEDIT feature:  Quiet variant of READONLY

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1738]
In Quiet mode, when the user tries to type into the document, Tedit would simply ignore the typein without putting up a warning message in the prompt window.

This would be useful for viewing applications, like @pamoroso hex dumper.  Also, DINFO man windows could be run with a Tedit process so that meta commands like meta-F (Find) etc. would go through, as in other windows.

**Comment by pamoroso** [comment]
Addressed by #1857.
