### ISSUE TITLE
Updating Organizational Partners on Interlisp.org

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1745]
@skaisler1 [suggested](https://groups.google.com/g/lispcore/c/IY8qLEFQaNA/m/WDe9RDSlCAAJ) updating the [Organizational Partners](https://interlisp.org/project/partners) page of the project site to reflect the collaboration with Prof. Kaltman and his students, Eleanor Young and Abhik Hasmain.

**Comment by hjellinek** [comment]
Merged changes.
