### ISSUE TITLE
Transfer interlisp.org to less expensive registar

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1758]
Larry Masinter — Customer Number: 26938517

Your domains are about to auto-renew.
Smart choice. As long as your payment info is still up to date, you can keep doing your thing. Not sure it's right? No problem. Just sign in to your account and find out.

Auto-renews on 7/13/2024 | Term: 2 Years

interlisp.org

+ .ORG Domain Renewal

$45.98**

**Comment by hjellinek** [comment]
Completed on June 18, 2024 by @masinter and @hjellinek.
