### ISSUE TITLE
Want better loadup / release method with Docker integration

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#177]
**Is your feature request related to a problem? Please describe.**

The Docker integration is a good demo of the idea, but the build stopped working with maiko not a subproject.

**Describe the solution you'd like**
1. Separate out 'building linux.x86_64 maiko container (which just needs a dev environment) from a minimal 'run medley' container
2. The run medley container should have more run-time files like fonts and dinfo
3. instructions on how to mount a folder in your file system if you're docker desktop host
4. ability to use a local X server as well as vnc

**Describe alternatives you've considered**
Maybe we'll be able to run in a browser rather than in the cloud

**Additional context**

**Comment by waywardmonkeys** [comment]
I've been learning Docker recently for other things and have some ideas on how we can improve upon this.

For item 1, we can do a multi-stage build where the first stage is a full image with dev tools, but then we copy the required build products to the second stage which is the actual image that gets deployed.

Items 2, 3, 4 are things I don't know about yet.

The alternative ... I'm working on it slowly.

**Comment by AbeJellinek** [comment]
Trying to decide how to proceed on this. Our current build file does use a multi-stage build, and it works (worked) well. The main issue is that a Dockerfile can only copy files from the directory that it is in into the container, i.e. `COPY ./foo.txt /` works, but `COPY ../other-dir/foo.txt /` doesn't. Now that Maiko is no longer a submodule, we're left with two options for how to run the build:

1. Have two Dockerfiles, one in `maiko`, one in `medley`. `maiko` will build with full dev tools, `medley` will copy only the relevant files out of the `maiko` image and build a final (slim) release image. Anyone wanting to build a new version of the Docker image will need to run two separate Docker builds in the right order - inconvenient and fragile.
2. Have one multi-stage Dockerfile [like we have now](https://github.com/Interlisp/medley/blob/master/Dockerfile). First stage builds the `maiko` image, second stage copies the built artifacts out of the `maiko` image and builds the `medley` image. To get around the Dockerfile directory issue, create a symlink in `medley` pointing to `maiko` that we clean up at the end. Better because we only need one Dockerfile and we don't have to tag the large intermediate (`maiko`) image, worse because it requires a wrapper script to create/dispose of the symlink, and because the symlink approach itself seems suboptimal. (But what is optimal here?)

@waywardmonkeys, curious to hear your thoughts about this.

**Comment by masinter** [comment]
Is there something special about the name Dockerfile? It would seem limiting to only allow one per repo.

**Comment by nbriggs** [comment]
It's like `Makefile` to make.  Documentation suggests that you can do  `docker build -f /path/to/a/Dockerfile` with an arbitrary name.

**Comment by masinter** [comment]
@AbeJellinek did you see the proposed fixes in #233? you file gave me some errors, for which i found work-arounds, mainly `ln -s ../maiko` plus updating .dockerignore.  I wonder if we can do releases with automation, including whatever is needed. Will we need something more complex?

**Comment by AbeJellinek** [comment]
I left a comment on your changes a while ago, but I guess it got lost! On my system, the code seems to create the wrong directory structure. I'll give it another try.

**Comment by AbeJellinek** [comment]
Hmm. I actually don't even get that far. The output:
```
[+] Building 16.3s (11/17)
 => [internal] load build definition from Dockerfile                                           0.3s
 => => transferring dockerfile: 681B                                                           0.0s
 => [internal] load .dockerignore                                                              0.5s
 => => transferring context: 121B                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                1.6s
 => [stage-0 1/6] FROM docker.io/library/ubuntu:focal@sha256:b4f9e18267eb98998f6130342baacaeb  0.0s
 => [internal] load build context                                                             13.9s
 => => transferring context: 1.27GB                                                           13.4s
 => CACHED [stage-0 2/6] RUN apt-get update && apt-get install -y make clang libx11-dev        0.0s
 => ERROR [stage-0 3/6] COPY ./maiko/ /build/                                                  0.0s
 => CACHED [stage-1 2/8] RUN apt-get update && apt-get install -y tightvncserver               0.0s
 => CACHED [stage-1 3/8] RUN mkdir -p /app/maiko                                               0.0s
 => CACHED [stage-1 4/8] WORKDIR /app                                                          0.0s
 => ERROR [stage-1 5/8] COPY ./* ./                                                            0.0s
------
 > [stage-0 3/6] COPY ./maiko/ /build/:
------
------
 > [stage-1 5/8] COPY ./* ./:
------
failed to compute cache key: too many symlinks: /maiko
```

All I did was `ln -s ../maiko`. Could it be a Mac-specific issue?

**Comment by AbeJellinek** [comment]
Interesting. This seems explicitly [*not* to work](https://stackoverflow.com/questions/31881904/docker-follow-symlink-outside-context)! Yet it works on your machine? Which folder are you building in?

**Comment by masinter** [comment]
I think the idea now is that the Docker build stage is unnecessary. All you need is a release and load the maiko.llinux and medley compressed tar files, into a kind of bare Docker distro.

**Comment by masinter** [comment]
Also #300 for a possible delivery of docker method

**Comment by masinter** [comment]
From PR #374 moving to this issue and changing title


> > ```
> > * not sure whether to approve or request changes.
> > ```
> 
> This is one piece of a larger puzzle - and as we build out the whole puzzle will likely change. As I see it we eventually will have an automated release process that consists of all of the following:
> 
> 1. Maiko test suite run on each push **Exists**
> 2. Build Maiko releases for supported environments
> 3. Medley test suite (this might be part of building the release)
> 4. Build Medley Release, which consists of building the sysouts and packaging it.  **Script exists to do this from a workstation**
> 5. Build a Docker image to support Medley on a variety of platforms.
> 6. Build a Docker image to support Docker in the Cloud (this may be an extension of the above, but that unclear).
> 
> Maybe building the Docker image isn't the right place to continue the process, the Maiko test suite exists, but from my perspective it's been useful in helping me understand how Medley is built.
> 
> Personally, I think getting any next piece in place and exercising it is a positive step.
> 
> > ```
> > * it looks like you're running X in the container and then tightvncserver, but xvnc contains both and only needs one process.
> > ```
> 
> This is an area that can be improved. The Dockerfile Abe created used tightvncserver so I kept with it. I played around with loading other X servers but found nothing that either worked or was supported by the various environments we want to support with Docker.
> 
> The whole how to connect to Interlisp running in a Docker Container is something that needs some work. It's non-obvious and took me a bunch of fiddling to get to work. I'd like this to be simple and bullet proof, we're no there yet.
> 
> > ```
> > * it would be good to find a smaller linux distro
> > ```
> 
> I started out using Alpine but found I was adding a lot to it, especially to get VNC working. I dropped that idea and went with Ubuntu. I would suggest finding a lighter distro is a good longer term goal.

**Comment by masinter** [comment]
In reply to

> * building maiko by `cd maiko/bin running './makeright x' and './makeright init' for the platforms we run on     
>   * that includes Mac OS 10 on x86 and Mac OS 11 on arm64
@stumbo wrote

> Building the Maiko Docker image and using it as the base for the Medley Docker image results in an image that will run on Windows, Linux, Mac and Pi in a Docker container. We can easily extend to any other operating system that support running Docker Linux containers.
It seems an (unnecessary) step backwards to _require_ Docker and Linux on systems that don't need it. As an extension it's great.
