### ISSUE TITLE
Create an uptime monitoring service

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#1773]
Hosts in the interlisp.org domain were unreachable owing to a DNS misconfiguration, and it was a couple of days before I found out and could fix it.

➡️ Set up a monitoring service that will alert us to similar problems in the future.

**Comment by hjellinek** [comment]
I set up a free account at `UptimeRobot.com` to monitor `online.interlisp.org` and `interlisp.org`.  We can add more, like `wasm.interlisp.org` when it's ready.

`UptimeRobot.com` will send notification emails to an email alias at our domain.

**Comment by pamoroso** [comment]
You may consider monitoring also `interlisp.org/src`, which right now yields a 404 error.

**Comment by pamoroso** [comment]
Never mind, the tool may not be well suited to catching 404s.
