### ISSUE TITLE
corrupted X display, scrambles when typing

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#178]
Peter (craven at gmx  net) reports

> When I start up the system, the display gets "scrambled". This works
itself out on a refresh (for example when scrolling the entire screen
with the right-most / lower-most scrollbar), but as soon as I type
anything, parts of the screen get scrambled again.
I'm running this on Arch Linux 64 bit, just compiled maiko a few hours
ago.    Xorg version is 1.20.10.

This is NOT the X display too large for the lisp display segment problem.
Sample screen snapshots are attached, along with the xdpyinfo and xwininfo output.

![scrambled](https://user-images.githubusercontent.com/8138841/107448477-95a43d80-6af6-11eb-9160-6fa703a5d30d.jpg)
![problem](https://user-images.githubusercontent.com/8138841/107448531-b076b200-6af6-11eb-8019-0a5a75401667.png)
[xdpyinfo.txt](https://github.com/Interlisp/medley/files/5955132/xdpyinfo.txt)
[xwininfo.txt](https://github.com/Interlisp/medley/files/5955134/xwininfo.txt)

**Comment by masinter** [comment]
is this an arch Linux problem or something that would show on other systems?

**Comment by masinter** [comment]
is this still a problem? I haven't seen anything like this in ages.
Reopen if so
