### ISSUE TITLE
Spelliing Errors in Using Medley

### ISSUE THREAD

**Issue by skaisler** [Interlisp/medley#1834]
In Using Medley re WSL, there are spelliing and unctuation errors.

Original paragraph:
[Using WSL](https://interlisp.org/software/install-and-run/windows/wsl/) (Windows Syswem for Linux). Medley on WSL requires the WSL subsystem to be installed on your Windows system. And when installing and using Medley on WSL you are working within a Linux environment. Some familiarity with Linux and the Linux command line is helpful. Medley on WSL is best for users who are running WSL anyway and/or prefer working in a Linux environment.

should be:
Revised Paragraph:
[Using WSL](https://interlisp.org/software/install-and-run/windows/wsl/) (Windows **System** for Linux). Medley on WSL requires the WSL subsystem to be installed on your Windows system. **And, when installing and using Medley on WSL,,** you are working within a Linux environment. Some familiarity with Linux and the Linux command line is helpful. Medley on WSL is best for users who are running WSL anyway and/or prefer working in a Linux environment.

**Comment by pamoroso** [comment]
Addressed by [PR #241](https://github.com/Interlisp/Interlisp.github.io/pull/241).
