### ISSUE TITLE
maiku doesn't build on openBSD since 3318e75

### ISSUE THREAD

**Issue by okflo** [Interlisp/medley#186]
Trying to build current maiko (makeright x) on OpenBSD current, fails with, see below.

commit, which built fine: 3318e75

> clang -m64 -std=gnu99 -fno-strict-aliasing -c -O2 -g3 -I/usr/X11R6/include -DXWINDOW -DRELEASE=351 -I../inc/ -I../include/ ../src/tty.c -o ../openbsd.x86_64-x/tty.o
> ../src/tty.c:32:8: error: unknown type name 'fd_set'
> extern fd_set LispReadFds;
>        ^
> ../src/tty.c:61:7: warning: implicit declaration of function 'FD_SET' is invalid in C99 [-Wimplicit-function-declaration]
>       FD_SET(TTY_Fd, &LispReadFds);
>       ^
> ../src/tty.c:75:5: warning: implicit declaration of function 'FD_CLR' is invalid in C99 [-Wimplicit-function-declaration]
>     FD_CLR(TTY_Fd, &LispReadFds);
>     ^
> 2 warnings and 1 error generated.
> *** Error 1 in /home/okflo/lisp/interlisp/maiko/bin (makefile-tail:691 '../openbsd.x86_64-x/tty.o')

**Comment by nbriggs** [comment]
Missing include of <sys/select.h> in tty.c

**Comment by nbriggs** [comment]
My OpenBSD system isn't available at the moment (and is sadly out-of-date anyway), could you try branch fix-tty-missing-include to verify the fix before we merge to master?

**Comment by okflo** [comment]
thanks for that fast reply. yes I can confirm, branch fix-tty-missing-include builds fine on OpenBSD current. (and medley starts fine).

cool - and thanks for your efforts to revive Interlisp! :)

**Comment by nbriggs** [comment]
I've merged the fix to master.  Thanks for pointing out the problem.
