### ISSUE TITLE
Windows installer doesn't escape spaces in file paths.

### ISSUE THREAD

**Issue by kotenok2000** [Interlisp/medley#1868]
**Describe the bug**
When i tried to install medley on Windows i have set install path to E:\Program files\interlisp
It installed cygwin to E:\Program
**To Reproduce**
1. Run https://github.com/Interlisp/medley/releases/download/medley-241022-5fef8528/medley-full-cygwin-x86_64-241022-5fef8528_240513-4becc6ad.exe
2. Use  install path cotaining spaces.
3. It installed cygwin to E:\Program and couldn't find bash.

**Expected behavior**
Interlisp handles file paths containing spaces without errors.
**Screenshots**

**Context (please complete the following information):**
 - OS: Windows 11
 - OS Version: 10.0.22631.4317
 - Host arch: x86_64
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

**Additional context**

**Comment by masinter** [comment]
probably should go through all the scripts and make sure parameters are quoted

**Comment by fghalasz** [comment]
Fixed in Pull Request #1880.

**Comment by nbriggs** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue
