### ISSUE TITLE
Improve CREATE formatting in SEdit

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1869]
The way SEdit formats `create` statements needs improving, most notably the alignment of field initialization clauses.

This feature request, which is related to #1631, was suggested by @hjellinek in the October 28, 2024 implementation meeting. For reference the SEdit formatting documentation is [here](https://files.interlisp.org/medley/docs/internal/sedit).

**Comment by rmkaplan** [comment]
Also #1490

**Comment by pamoroso** [comment]
I missed #1490. This is essentially a duplicate, so if you have no objections I'll close #1869.

**Comment by pamoroso** [comment]
Closed as duplicate of #1490.
