### ISSUE TITLE
Failing to Pass Norton Ultiimate Inspection

### ISSUE THREAD

**Issue by skaisler** [Interlisp/medley#1879]
Tried to Run the 11/11 version of the installer for Medley with Cygwyn.
Failed because Norton Ultimate noted a problem with the file
![Medley-NortonIssue](https://github.com/user-attachments/assets/a5a58ef3-bc1a-43c2-a72f-87f46df41e26)
Attached fil as reported by NOrton Ultimate.

**Comment by nbriggs** [comment]
What did the "See details" report?  What options are available under "More Options", and is something akin to "run it anyway" available?

**Comment by skaisler** [comment]
NIck:

The See Details was useless since their lab did not respond.

I added the install file to the exclusions under Norton Ultimate and was
able to run it and install Medley that.

However, it may be worthwhile to examine the build file and serif anythin
changed from the 10-122 version that might be unacceptable to Norton
Ultimate.

Steve K.

**Comment by hjellinek** [comment]
Can't duplicate/obsolete/workaround available.
