### ISSUE TITLE
Remove X link and logo, maybe replace with other social media

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#1887]
The Interlisp.org website footer links to what used to be called Twitter.  I'd favor removing that from the site because they're successful enough without our help.  I suggest we link instead to our Mastodon and Bluesky accounts - and if we don't have those, establish them.

@stumbo is the website guy, I think.
@pamoroso would know about the socials.

**Comment by pamoroso** [comment]
I agree to leave X for an additional reason, which was a major motivation for me to move to Mastodon prior to the earliest 2022 Twitter migrations: there's essentially no organic reach on X even for users with many followers such as 5-10K or more. And the algorithms penalize posts with links.

If we set up a Mastodon account, unless we self host which is a bit involved, it would make sense to join an instance focusing on retrocomputing such as these which are the best known:

• [Bitbang](https://bitbang.social/about)
• [Oldbytes](https://oldbytes.space/about)

Starting with a Mastodon account may not initially require a Bluesky one thanks to a [Mastodon-Bluesky bridge](https://lifehacker.com/tech/use-bridgy-feed-to-link-mastodon-and-bluesky).

I'd be happy to maintain a Mastodon account.

**Comment by tfeb** [comment]
For what it's worth (so, as someone who has contributed 0 to the project!) I strongly endorse this.  Not being on X has to be good.

**Comment by hjellinek** [comment]
Thanks, @pamoroso.  Given Fosstodon's technical and community resources and strong association with the FOSS movement, it sounds like the appropriate venue (ahem) for our project.

I gather that entrée to Fosstodon is by invitation, and further that we have project members who can issue just such an invitation.  What else is required to get set up there?

I volunteer to submit the PR to replace our Twitter link with our Mastodon link.

**Comment by pamoroso** [comment]
Here is what to do to join Fosstodon. I'll use my Mastodon account `@amoroso@fosstodon.org` and [profile](https://fosstodon.org/@amoroso) as an example.


## Pick a username

Mastodon handles have the format `@username@instance.example.com`. I recommend the `interlisp` username as, although other variations such as `medleyinterlisp` or `medleyproject` are possible, they are less easy to remember or deduce. In this case the full handle is `@interlisp@fosstodon.org`.


## Sign up for Fosstodon

@masinter and I can provide a Fosstodon invite, we only need an email address to send the invite to.

I recommend to sign up to Fosstodon using an interlisp.org address like info@interlisp.org or board@interlisp.org. From such email address follow the instructions in the invite, making sure to enter that address and create the `interlisp` username.


## Verify the account

Mastodon supports [account verification](https://joinmastodon.org/verification) which shows checkmarks next to the links to websites the user owns. See for example the checkmarks of the links in [my profile](https://fosstodon.org/@amoroso)

In practice, for us this involves adding an HTML snippet like this to the home page of interlisp.org:

```
<a rel="me" href="https://fosstodon.org/@interlisp">Mastodon</a>
```

Once the code is in place we need to enter https://interlisp.org in one of the extra fields of the Fosstodon profile. As an example, here is the verification section:

![mastodon-verification](https://github.com/user-attachments/assets/20997d6c-e0c3-4fb1-9522-fe84a0cb75eb)

and the extra fields of the profile of my Fosstodon account:

![mastodon-profile](https://github.com/user-attachments/assets/f81cda6e-5bc2-4640-bb82-7f7e4d3b6ef9)

## Share the credentials

At this point I need the Fosstodon credentials (an email address like info@interlisp.org and a password) to fill in the profile and report back for feedback.

**Comment by hjellinek** [comment]
Perfect, thanks.  I will reply by private email.

**Comment by hjellinek** [comment]
@stumbo, what file should I edit to add the `rel` link @pamoroso mentioned above?  It will look like this:

`<a rel="me" href="https://fosstodon.org/@interlisp">Mastodon</a>`

**Comment by pamoroso** [comment]
The code `<a rel="me" href="https://fosstodon.org/@interlisp">Mastodon</a>` goes in the body of the page and creates a link with anchor text `Mastodon`. An alternative that doesn't insert visible text in the page is to add to the header this other snippet:

```
<link rel="me" href="https://fosstodon.org/@interlisp" />
```

**Comment by hjellinek** [comment]
I'd prefer it in the `<head>`. We'll have a visible link in the footer.

**Comment by hjellinek** [comment]
@stumbo I was asking what file I should put the

````
<link rel="me" href="https://fosstodon.org/@interlisp" />
````

incantation in.
