### ISSUE TITLE
Remove unused field from FONTDESCRIPTOR

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1897]
FONTDESCRIPTOR has a bunch of fields that are not set or fetched in any code that the Masterscope database knows about.  It seems that these are left over from the days of fonts with only 8-bit characters (Altofonts?) and were not cleaned out when the information moved down into the per-character-set CHARSETINFO's.

The fields are
(FBBOX SIGNEDWORD)
(FBBOY SIGNEDWORD)
(FBBDX SIGNEDWORD)
(FBBDY SIGNEDWORD)
(\SFLKerns POINTER)
(\SFRWidths POINTER)

It is confusing to have those fields hanging around.  As a first step (which avoids needing to recompile all the clients), I propose to replace all those field-names with NIL so it is clear that they should eventually disappear.

There is a problem with kerning apart from the useless \SFLKerns field.  The CHARSETINFO has a LEFTKERN field, which is referenced only by \READACFONTFILE.  That would be useful if Tedit or anybody else wanted to do a better job of formatting.  But the function \FGETLEFTKERN takes an 8-bit code and a kern-vector as its argument, assuming that the caller has already landed on the kern vector by getting the CHARSET info for the character's high-order byte.  In that respect it is not parallel to e.g. \FGETCHARWIDTH.  \FGETCHARWIDTH takes a fontdescriptor and 16-bit code and does a 2-step retrieval. I think \FGETLEFTKERN should follow the same protocol (whether or not it is ever used).

**Comment by nbriggs** [comment]
There seems to be a bunch of commented out code that used to use these fields, so I agree that they're probably obsolete.  I wonder if we have sufficiently old copies of the font code that it would predate the introduction of the NS character coding for FONTDESCRIPTORs.

**Comment by masinter** [comment]
There are a huge number of cleanup tasks that would individually alone get us closer to the project goals, without risking introducing backward incompatibilities.

* For example, currently you CANNOT RELY on FULLER.DATABASE to tell you where a record field might be used. It's close, but it's not 100%. Fixing that would help. 
* Computing diffs of compiled code to insure that GLOBALVARS declarations vs. SPECVARS would help with insuring we can recompile every file without loss.
* There are a few records which have different definitions for the same record name -- these need to be eliminated to avoid unwittingly redefining the record at the wrong time.
* there are some files included in the loadup with 90% or 99% of the code unused and not useful. Sorting these out will remove some sources of conflicts. 

But removing the field names by itself doesn't seem to me to help much at all. 
Who benefits how from this change without more (unscheduled, no volunteer) effort?

**Comment by rmkaplan** [comment]
Well, first, this came up because these fields confused Herb when he started to work on the html stream. Second, we have to start somewhere.  Third, the kerning is totally broken.
