### ISSUE TITLE
TEdit - font used in char looks menu changes for no apparent reason

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1899]
This was in TEdit from

commit 3c96486c5ea0eecd25c6ac5af04ca6862ae1562f (HEAD -> rmk36--Tedit-fifth-round-2, origin/rmk36--Tedit-fifth-round-2)

I selected a line of text in a document and then opened the Expanded Menu > Char Looks and did a "Show".
![Screenshot 2024-12-09 at 5 56 18 PM](https://github.com/user-attachments/assets/4040ac18-19e7-4406-ac0e-f0b21318c6f6)

Then I selected the next line, and did a "Show".  Both were Modern 10 MRR fonts being shown, but the font used to display the font size changed by a pixel or two.
Compare the distance between the curly bracket in `Size: {10}` and the tip of the `1` in the two images.
![Screenshot 2024-12-09 at 5 56 45 PM](https://github.com/user-attachments/assets/bf196b28-643e-4063-b5cb-510b0e942ade)

**Comment by rmkaplan** [comment]
Fixed in #1857
