### ISSUE TITLE
FILLCIRCLE and DRAWCIRCLE on a window do not appear

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#1908]
**Describe the bug**
When you call `FILLCIRCLE` or `DRAWCIRCLE` on a window, the results do not appear.

Reported by @abhikhasnain1 , documented and reproduced by me.

**To Reproduce**
1. Load the [attached file.](https://github.com/user-attachments/files/18131873/bug.lisp.txt)
2. Call `(CIRCLE-BUG)`.  What, no circles?
3. After a few seconds, press a key in the exec.  The function moves the window by a single pixel and the circles appear.

**Expected behavior**
I expect to see the circles in the window immediately.

**Screenshots**

**Context (please complete the following information):**
 - OS: macOS Ventura 13.7.1
 - Host arch: Intel
 - Maiko version: a2f62159e96b4dde1c52f526f04f71e969ad3d90
 - SDL
 - IL:MAKESYSDATE: 6-nov-2024

**Additional context**
Other drawing primitives (e.g., `DRAWLINE`) do render immediately.  If calling one after DRAWCIRCLE or FILLCIRCLE, the circles appear along with the lines or whatever you drew.

I ran under SDL, @abhikhasnain1 ran under X.  The problem occurred in both.

![Before moving window](https://github.com/user-attachments/assets/0815f77f-f0e6-4769-bb5a-ed5c77d88907)
![After moving window](https://github.com/user-attachments/assets/12c1873a-3144-4f3f-a393-0d3d693fffe6)

**Comment by nbriggs** [comment]
Hmmm... also 13.7.1, XQuartz 2.8.6_beta2 -- I see your pictures, but when I run it under XQuartz I get this

https://github.com/user-attachments/assets/9d84db6c-8510-4fb8-bb4d-79c437990b2c

while under SDL it fails -- you can also get it to redisplay by waving another window outline over the top of the circle window.  It is supposed to be tracking the screen area where there has been any damage to the screen bitmap and redisplaying only that after the screen bitmap has been updated.  I'm not sure why it's not managing to flush the changes correctly, but I know where to instrument the maiko SDL code to see what it's doing.

**Comment by hjellinek** [comment]
It's hard to tell from the video, but is it taking a few seconds for the circles to draw?

That aside, Abhik found this while working his way through the Primer, calling graphics functions one at a time in the Exec.  Basically,
1. Create a window, `(SETQ W (CREATEW))`
2. Call `DRAWCIRCLE`, passing the window
3. No circle!
4. Eventually he called `DRAWLINE `and _clipped_ circles appeared.

There are certain to be multi-second delays between some of these steps.

He said he's using X, and I'm guessing he's using Windows.  But I'm not sure.  @abhikhasnain1, can you describe your software setup?

**Comment by nbriggs** [comment]
The configuration is important for this kind of issue!

Yes, there are a number of seconds before the circles appear, which happens all at once.
By "and *clipped* circles appear", do you mean that the circles only appeared within the enclosing rectangle of the two endpoints of the line drawn by `DRAWLINE`?  That would be consistent with a failure to get the screen bitmap region touched by the circle/ellipse correctly flushed to the display - drawing the line creates a new damage region, previously written things are still there and get displayed.

**Comment by hjellinek** [comment]
Yes, I observed that the circles only appeared within the enclosing rectangle of the two endpoints of the line drawn by `DRAWLINE`, as you perfectly described it.  I'm pretty sure that's what I saw on Abhik's screen too.

**Comment by nbriggs** [comment]
I think the problem comes from the way that some of the drawing primitives (but not DRAWLINE) bottom out in calling `\PILOTBBT` (it's a microcode instruction)  to smash bits into the screen bitmap - and I don't think we have code in the opcode implementation to determine that this is in fact the screen bitmap and calculate the damage for the screen update - so the changes happen in the Lisp screen bitmap, but then aren't visible until some other operation triggers the update to the real display.

I'll see if I can fix this without undue overhead.

**Comment by nbriggs** [comment]
[Edit: the opcode is named `\PILOTBITBLT`\
