### ISSUE TITLE
Add a field to the GitHub issue template

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#1916]
To the *Context* portion of the issue template below, I propose to add "Display/window system" field:

**Context (please complete the following information):**
 - OS: [e.g. Mac/Linux/Cygwin]
 - OS Version: [e.g. High Siera/Ubuntu 18/Raspbian]
 - _Display/window system: [e.g. X, SDL, VNC]_
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

Existing template:

**Describe the bug**

**To Reproduce**
1. Files loaded '...'
2. Form to eval and/or menus to click '....'
3. What happened? '....'

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Mac/Linux/Cygwin]
 - OS Version: [e.g. High Siera/Ubuntu 18/Raspbian]
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

**Additional context**

**Comment by masinter** [comment]
is "VNC" a "window system"? I wonder if we could implement bug reporting
using TEdit and turn the AR interfaces into GitHub clients. The we could
compute what to fill into the form.


https://LarryMasinter.net  https://interlisp.org

**Comment by hjellinek** [comment]
It's more of a "display system," but in suggesting CNC as a candidate I was trying to choose a word that would describe things from the perspective of an online.interlisp.org user.
I realize now that "Web browser" would be more appropriate for that case.

**Comment by hjellinek** [comment]
> If it's a display/input related problem then it's useful (often necessary) to know exactly how the system is being run - is it X11 to the same machine? X11 to same machine Xvnc with remote input via a VNC client? SDL remote to an X11 server (SDL uses different backend drivers depending on what it can detect), SDL to a VNC display with in-browser VNC client, ...

Indeed.  How can we sum that up in a succinct prompt or two?  For most of those cases we'll need more info that doesn't fit into a neat scheme.  So how about something like this for the high-level info?:

- Display/window system: [e.g. X, SDL, VNC, Web browser]
- If remote display, what client? [e.g. XQuartz, TigerVNC, Firefox]

An Interlisp-based AR system would be cool, but it presumes no serious input or output problems, and for openness we'd want issues to show up in GitHub anyway, right?

**Comment by nbriggs** [comment]
Perhaps the high-order bit is whether it was online.interlisp.org or not.

**Comment by nbriggs** [comment]
We should make sure that `(IL:PRINT-LISP-INFORMATION)` has as much of the information that we need reports to contain as possible.  Lisp knows what display subsystem (X11 or SDL) it's running with.  What it can't detect is the client display info.

**Comment by rmkaplan** [comment]
In terms of getting the information out of Lisp and into the Issue, if PRINT-LISP-INFORMATION writes it in the clipboard, you could just paste it in.

**Comment by hjellinek** [comment]
> In terms of getting the information out of Lisp and into the Issue, if PRINT-LISP-INFORMATION writes it in the clipboard, you could just paste it in.

SDL doesn't support copy-paste, as far as I know.  (Please correct me if I'm wrong!  I'm dying for this to work.)

So, how's this?  GitHub messed up the formatting:

**Context (please complete the following information):**
- Are you using online.interlisp.org? [yes / no]
- OS: [e.g. macOS/Linux/Cygwin]
- OS Version: [e.g. High Sierra/Ubuntu 18/Raspbian]
- Display/window system: [e.g. X, SDL, VNC, Web browser]
- Host arch: [e.g. x86_64, arm7l, arm64, SPARC]
- Maiko version: [e.g. commit ID from `git log | head` ]
- `IL:MAKESYSDATE`: [ date ] or `(il:print-lisp-information)`: copy-paste or screenshot this

**Comment by nbriggs** [comment]
If you're running on macOS, copy-paste works with SDL.  It'll be option-C and option-V *within* Lisp, but command-C and command-V outside Lisp.

**Comment by nbriggs** [comment]
That'll do for now.  We can improve on it later.

**Comment by hjellinek** [comment]
> If you're running on macOS, copy-paste works with SDL. It'll be option-C and option-V _within_ Lisp, but command-C and command-V outside Lisp.

Fantastic!  It seems to have started XQuartz running, but it did work.

**Comment by rmkaplan** [comment]
Is option-C/V vs command-C/V within Lisp in macOS specific to SDL, or is it just how the meta key happens to be bound.

I have meta bound to Command in X/Mac, would I have to use Option in general if I were runnng SDL?

**Comment by hjellinek** [comment]
> That'll do for now. We can improve on it later.

I made the change, see PR #1925

**Comment by nbriggs** [comment]
@rmkaplan - It's on the meta key, but SDL doesn't have the command key wired up, so you can't even say your meta key is the command key.  I should fix that, but all changes there got stuck behind doing something more reasonable with the keyboard handling.   @hjellinek - it should have been using pbcopy/pbpaste rather than xclip (use of which is probably what started XQuartz) - what is (UNIX-GETENV "OSTYPE") in your Medley?

**Comment by hjellinek** [comment]
`(UNIX-GETENV "OSTYPE")` returns `NIL`.

**Comment by hjellinek** [comment]
I set/exported `OSTYPE` in my `.bash_profile`, and now meta-C/meta-V work as expected under SDL.  Thanks!
Incidentally, the value of `OSTYPE` on this machine is `darwin22`.

We can continue this in a discussion.  The issue for which I opened this is now fixed, and I will close it.

**Comment by hjellinek** [comment]
Fixed, approved, merged.
