### ISSUE TITLE
Bug (regression) in TEdit fifth round, PR #1857

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#1923]
**Describe the bug**
I pulled the PR branch `origin/rmk36--Tedit-fifth-round-2`, built `loadup-all.sh -apps`, ran it.

**To Reproduce**
1. Open a new TEdit document
2. Open the Character Looks menu
3. Type some text
4. Select a word
5. Click "Superscript".  If "distance: {}" contains a value, clear it.
6. Click "Apply"

You can perform the operation with an integer value in "distance: {}"; the result is the same.

**Expected behavior**
The word should be moved up a couple of points above the baseline of the surrounding text.  *This works as expected in the standard Medley loadup.*

**What Actually Happened**
- A break window opens.

**Screenshots**
See attached: "distance: {}" with and without a value.

**Context (please complete the following information):**
 - OS: macOS
 - OS Version: 13.7.1
 - Host arch: Intel
 - Maiko version: `55d8504060d0d40505a2ddc39daca12f9ecb0303`
 - IL:MAKESYSDATE: Dec 18, 2024

**Additional context**
![screenshot_731](https://github.com/user-attachments/assets/db1b19af-6d84-4304-bd3d-809dcade15ed)
![screenshot_730](https://github.com/user-attachments/assets/756050c9-a828-4b70-a6ad-16a4c32fee9f)

**Comment by rmkaplan** [comment]
Rebuild and try again

**Comment by hjellinek** [comment]
I pulled the branch, rebuilt and repeated both tests ("distance" with and without a value) and it worked fine.
