### ISSUE TITLE
FILEBROWSER:  Remove "fast" subcommands of of see

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#202]
The "see" command of the filebrowser has two "fast" subcommands:
        fast SEE pretty
        fast SEE unformatted
And then it has "see scrollable and pretty"

The first 2 commands are carry-overs from another time and place, where things were slow and and so faster trade-offs were provided as alternatives to obviously desirable functionality.

I think there is no need to retain those commands with modern speeds.  In fact, the faster versions are a trap that actually slows things down.  You mistakenly click on one of those, then realize it isn't what you want, close the window, go back, and click the scrollable version.

I think the fast commands should be removed.  See on a file should automatically do scrollable and pretty, and see on a directory should automatically do filebrowsing.  See doesn't need to have subcommands.

**Comment by masinter** [comment]
I'd like a singlr mrnu that would preview a .TEDIT and other file extensions also. While we are wishing.

**Comment by rmkaplan** [comment]
Poking around, as a first approximation this would be an easy change, just modify the value of FB.MENU.ITEMS.  But it does need to discriminate between files and directories, so that it can call FB.EDITCOMMAND on files (scrollable/pretty if a text file) but a recursive call to FILEBROWSER on subdirectories.  Is there an official predicate that tells whether a filebrowser entry identifies a subdirectory and not a file?

**Comment by nbriggs** [comment]
DIRECTORYNAMEP ?

**Comment by nbriggs** [comment]
Otherwise, perhaps FB.IS.NOT.SUBDIRECTORY.ITEM ?   But when I try that it doesn't seem to give the result I expect.

**Comment by rmkaplan** [comment]
DIRECTORYNAMEP seems close enough.  The other one is somehow only used in FB sorting.

**Comment by rmkaplan** [comment]
I fixed FILEBROWSER so that it does the best SEE and EDIT that it can surmise from the top-level, submenu items still available to be more specific.
At the top-level, SEE of a Lisp file does (readonly) scrollable and pretty, SEE of a TEDIT file does readonly TEDIT, SEE of a directory brings up another filebrowser, SEE of anything else also does TEDIT.  EDIT of a Lisp asks about loadfrom and editing its coms, other wise edits.

I'm closing this.
