### ISSUE TITLE
FILEBROWSER can't be saved and compiled

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#203]
**Describe the bug**
FILEBROWSER was last made and compiled in 2001.

When I tried to make a change to the file and recompiled, I got a bad compiled error on loading the compiled file.
**To Reproduce**
1. Full sysout
2. Load EXPORTS.ALL)
3. LOAD(FILEBROWSER PROP)
4. MAKEFILE(FILEBROWSER)
5. TCOMPL(FILEBROWSER)
6. LOAD(FILEBROWSER.LCOM)
It stops with a bad-compiled function error.

**Context (please complete the following information):**
 - OS: Mac
 - OS Version: Big Sur

**Comment by nbriggs** [comment]
Have a look at the source that was written (outside Lisp) -- there's a CR embedded in the middle of the copyright notice, and that matches up with exactly where things went downhill in the LCOM.  The "bad compiled function: 2021" that it's complaining about is the 2021 in the copyright notice that seems to have been copied through into the LCOM.

**Comment by nbriggs** [comment]
And, if I delete the extra CR in the copyright notice (in an external texteditor) and then TCOMPL the file it works to produce a well-formed LCOM.

**Comment by rmkaplan** [comment]
Terrific, can you just send me the fixed file?

There is some goofiness with TABLEBROWSER also.  It has 2 different companion files for its declarations, TBDECLS and TABLEBROWSERDECLS, with slightly different (but maybe harmlessly so) declarations.  TABLEBROWSER itself uses one, but FILEBROWSER uses another. I’m going to synchronize.

**Comment by nbriggs** [comment]
I was doing that on the original FILEBROWSER file -- the error is in what the file package writes for the new source.  I don't have your modified source file -- but I can show you what you'd need to edit in your newly written version:
it should be:
```
^M; Copyright (c) 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1993, 1994, 1999, 2000, 2001, 2021 by Venue & Xerox Corporation.  All rights reserved.^M
```
rather than
```
^M; Copyright (c) 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1993, 1994, 1999, 2000, 2001,
^M 2021 by Venue & Xerox Corporation.  All rights reserved.^M
```
(where ^M represents an embedded carriage return)

**Comment by rmkaplan** [comment]
Thanks to Nick's sleuthing, this has been identified as an ancient bug in the function (PRINTCOPYRIGHT1 in PRETTY) that prints the copyright dates.  The bug shows up when you have a lot of years in the list (as FILEBROWSER does) and the readtable is a commonlisp readtable with semi-colon enabled.  Lines were overflowing because LINELENGTH was exceeded when they shouldn't have.

This is fixed in a new version of PRETTY.

**Comment by masinter** [comment]
If you load SYSEDIT (which,  in turn, loads EXPORTS.ALL) you'll get a couple more FLG's set.
I'll raise an issue about not adding new dates to old copyright.

**Comment by nbriggs** [comment]
The sysouts should probably have a new default copyright owner, representing whoever we think we are... "Interlisp.org"? It should presumably maintain the original copyright owner notices and add entries for the updated one going forward.

**Comment by rmkaplan** [comment]
I think that COPYRIGHTFLG is set to NIL in our sysouts, which means that copyrights with the origina owner (typically Venue and Xerox) and original years  (plus adding on the currentyear) for files that have a current copyright.  But copyrights will not be created for new files.

So you want a mode where it tacks on a new owner to the original ("Venue and Xerox and Interlisp.org <http://interlisp.org/>”) when it adds a new date, and just Interlisp.org <http://interlisp.org/> when a new file is created?

**Comment by masinter** [comment]
I'm not sure what the right thing should be. For now, it would be sufficient to just leave COPYRIGHT alone. We don't want to change assertions of copyright. I think Interlisp.org is just a website, which will get you to the LICENSE file and context.

**Comment by masinter** [comment]
i did make a new issue #207

**Comment by rmkaplan** [comment]
Copyright moved to an new issue.  This problem with FILEBROWSER is fixed.  Closing
