### ISSUE TITLE
don't add new dates (> 2003) to old copyright

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#207]
When following normal development in Interlisp, it will add a new year (2021) to the existing COPYRIGHT property.
I think the practice with maiko was to leave copyright, it was OK to remove license terms, but not to add any more copyright notices automatically.

**Comment by nbriggs** [comment]
If you don't record any information to the contrary, I believe that [copyright ownership automatically resides with the author](https://www.copyright.gov/title17/92chap2.html), whether the notice is there or not.  It's a lot easier if it is recorded.

**Comment by nbriggs** [comment]
I agree that we shouldn't be adding new years to the Venue/Xerox/other notices.  My comment on #203 was that if the current copyright owner info is not the same as the existing copyright owner info in a file, we should not add the new year to the old list but rather add a new copyright statement with the new owner and the new year.  If the copyright owner is not set, or the mechanism is turned off, then obviously the code shouldn't do this.

**Comment by masinter** [comment]
Copyright dates are still being added -- see #348    we can write copyright Interlisp.org

**Comment by rmkaplan** [comment]
Should we make this condition on seeing Xerox, Venue, or Envos?  That is, if the copy right is one of those and we are making a change, change the copyright to Interlisp.org?  (

**Comment by masinter** [comment]
The guidelines I'd like to follow are:
* Do not **delete** any copyright notice or date
* Shortening ranges is OK
* It is OK (and preferable) to delete license statements or claims "All Rights Reserved" 
* I'm not sure about whether to turn off any modification of copyright properties, but i think it's best
* I suggest we add a NOTICE.md about copyright ownership and link it from LICENSE.md

**Comment by stumbo** [comment]
Apache has a tool, [rat](https://creadur.apache.org/rat/) that is used to validate copyright notices in files.  Maybe we can harness something like this to validate files are correctly copyrighted.  

If we can wire it up, we could have part of the approval of a PR require passing an audit.

**Comment by nbriggs** [comment]
Interlisp is already managing the copyright notices, in a more sophisticated manner than rat does, when one edits the files.

**Comment by johnwcowan** [comment]
Updating copyright dates has no legal effect in practice.  Who cares if our code goes into the public domain in 2073 or 2110?  It may serve a *social* function in that people may assume anything with a copyright date less than a few years ago is abandoned, but that's not our target audience, I trust.

My recommendation: "Add a copyright date when a file is created; leave it alone after that."
