### ISSUE TITLE
Cannot load DANCEROBJ.LCOM, Bad compiled function DANCERMENU.CLOSEFNA0001

### ISSUE THREAD

**Issue by ecraven** [Interlisp/medley#210]
**Describe the bug**
I wanted to load `internal/test/GC/Hand/DANCEROBJ.LCOM` in order to look at `internal/test/Library/TEDIT/hand-aux/AR10063.TEdit` (which uses an image object `DANCEROBJ.GETFN`).
For both the file mentioned above and `internal/test/Library/TEDIT/hand-aux/DANCEROBJ.LCOM` I get the error:
```
compiled on 20-Apr-88 05:13:42
File created 20-Apr-88 05:11:42
Bad compiled function
DANCERMENU.CLOSEFNA0001
```

**To Reproduce**
```
(LOAD "{DSK}<path>to>medley>internal>test>GC>Hand>DANCEROBJ.LCOM"}
```
**Expected behavior**
No errors

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Arch Linux
 - Host arch: x86_64

**Additional context**
Probably not a very urgent problem (if relevant at all), just wanted to note it here.

**Comment by masinter** [comment]
internal/test has some files from Medley 2.0 for testing Medley implementation. Most of the .LCOMs aren't compatible. I haven't finished inventory  of what we have, for #52

**Comment by masinter** [comment]
this is now in the separate (test) repo.

**Comment by rmkaplan** [comment]
I recompiled the file, now loads, and Dancer imageobjects do display (if Dancer font is also available)
