### ISSUE TITLE
SIGSEGV in xrdopt.c read_Xoption

### ISSUE THREAD

**Issue by sethm** [Interlisp/medley#212]
**Describe the bug**

Running `ldex` now causes a SIGSEGV in the first call to `XrmGetResource()` in `read_Xoption()` (xrdopt.c:169 in master).

**To Reproduce**

Compile the usual way (`cd bin && ./makeright x`) and attempt to execute the `ldex` target executable, with or without any command line arguments.

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Mint 20.1, Kernel 5.4.0-65-generic
 - Host arch: x86_64
 - Maiko version: 0129b50127fa03f98cd3e4894924905d9c29cb04 and later
 - IL:MAKESYSDATE: N/A

**Additional context**

It looks like the crash was introduced in Maiko simply by moving the `XrmDatabase` variables from global to local scope. I do not yet understand why this would cause any issues, it doesn't make any sense to me, but it looks like the culprit.

**Comment by nbriggs** [comment]
Weird.  Doesn't happen on a Mac.  I'll look into this.

**Comment by nbriggs** [comment]
Oops.  Global variables are initialized to NULL.  Locals are not required to be.

**Comment by nbriggs** [comment]
@sethm, I've checked this on an Ubuntu system (same problem as your Linux Mint) -- would you like to check that the branch (fix-uninitialized-X-variable) fixes it for you?

**Comment by sethm** [comment]
> @sethm, I've checked this on an Ubuntu system (same problem as your Linux Mint) -- would you like to check that the branch (fix-uninitialized-X-variable) fixes it for you?

That fixed it, thanks! I assumed that XrmParseCommand initialized commandlineDB, but apparently not.

**Comment by nbriggs** [comment]
It merges if the db is not NULL.  I’ll merge the PR shortly.
