### ISSUE TITLE
FILEBROWSER:  SEE and EDIT windows don't come up on top

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#216]
**Describe the bug**
Maybe this is a feature request, but I think it's a bug.  It certainly doesn't conform to the Medley DWIM spirit.

When you click on the SEE or EDIT menu items in the FILEBROWSER, it now does what you mean in terms of bringing up the selected information in the most useful way--a scrollable file, and pretty for a Lisp source file.

Presumably, however, the reason that you clicked SEE or EDIT is that you meant to see or edit the file as your next action.  That's fine if the window region is outside of the FILEBROWSER window.  But if the region you pick overlaps with the browser window, the filebrowser immediate jumps on top.  So you have to do some more clicks to continue your work.

I think the problem is in the menu interaction:  the see/edit item is greyed out while the see/edit window is created (on top), as desired.  But then the action of ungreying the menu causes the filebrowser to pop to the top.

**Comment by rmkaplan** [comment]
I was able to smooth this out by reshading the menu before the edit/see window comes up.  Improved behavior in a new FILEBROWSER, closing this issue

**Comment by masinter** [comment]
I think you should leave issues open until someone else reviews it is fixed in a new loadup (once makeinit7 is merged)

**Comment by nbriggs** [comment]
You can have github automatically [close the issue when the PR is merged](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)
