### ISSUE TITLE
SYSOUT returns wrong value when resuming

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#227]
**Describe the bug**
SYSOUT seems to return a (non LISTP) non-existant version when resuming

**To Reproduce**
make a sysout. LOGOUT and restart it
The SYSOUT call returns the name of a new (non-existent) version

**Expected behavior**
return a list of the name of the restarted version

**Screenshots**
![image](https://user-images.githubusercontent.com/1116587/110214261-a7a8a000-7e58-11eb-986e-3548e6a72270.png)

![image](https://user-images.githubusercontent.com/1116587/110214336-fa825780-7e58-11eb-97f4-f989eb421e7a.png)

**Comment by nbriggs** [comment]
What files exist on disk at the time?

**Comment by masinter** [comment]
I started with no sysouts, called SYSOUT) twice. when I restarted WORK.SYSOUT (which was linked to `WORK.SYSOUT.~2~`) i got the result WORK.SYSOUT;3 which didn't exist.

**Comment by masinter** [comment]
Ron changed SYSOUT on ADIR to make a new version back 3-4 years ago... that's where i'd look :)
