### ISSUE TITLE
add Postscript to xlisp.sysout, remove interpress output (leave it in library)

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#26]
It turns out that the ancient Lisp sysout that we try to update (until we can do a MAKEINIT) contains Interpress but does not contain Postscript.  Which seems a little retro--are there any Interpress printers left in the world?

I propose at least to include postscript in the updater that makes the lisp.sysout, and to remove Interpress (and its fonts) from the load-up that we will use when we can build from scratch.

**Comment by masinter** [comment]
I think the world we're trying to shoot for, people can build their own sysouts, and we just provide some defaults.
 We can provide a fuller sysout with both ip and ps printing, diagnostics, benchmarks, demos loaded

**Comment by masinter** [comment]
the problem with just removing files is that there are lingering dependencies.
Making postscript be the default would be OK but there's another issue.  feel free to reopen
