### ISSUE TITLE
SIMPLE-INIT is not closed after greeting

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#267]
**Describe the bug**
Starting up with Lisp or Full, the file SIMPLE-INIT remains open when the greeting has completed.
**To Reproduce**
1. Files loaded '...'
2. Form to eval and/or menus to click '....'
3. What happened? '....'

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: Mac
 - OS Version: Big Sur
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: 12-mar-2021 12:24:04 (full.sysout)

**Additional context**

**Comment by nbriggs** [comment]
Given that the loadup process was implemented as a GREETFILE... this is probably the same fundamental problem.  I'd look at the GREET implementation to see what got broken.

**Comment by nbriggs** [comment]
Fixed by PR #273
