### ISSUE TITLE
Missing image object for manual:  HRELE

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#268]
**Describe the bug**
Clicking on the first *function* option for "man litatom" shows an unknown image object HRELE.GETFN

In the master full.sysout

**Comment by Anzus** [comment]
Interesting. Looks like file corruption, that’s supposed to be an HRULE image object. Editing CHAPCONTROLFNS.TEDIT in the Dinfo directory to replace HRELE with HRULE fixes it, I’ll upload a new version.

**Comment by masinter** [comment]
fixed by PR #391
