### ISSUE TITLE
WHEREIS hash:  PF TEDIT.PUT gives invalid argument error

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#269]
**Describe the bug**

**To Reproduce**
1. full.sysout  12-Mar
2. PF TEDIT.PUT
3. SETFILEPTR:  Invalid argument; 1480938554

**Comment by rmkaplan** [comment]
This seems to have wider undesired consequences:  not just PF, but ED seems to go thru WHEREIS and trip over this.  It does TYPESOF, even though it has been prompted with (FNS FUNCTIONS) and even if the symbolic definition is actually loaded and in the function cell

**Comment by masinter** [comment]
It's a bit fragile. `(SETQ XCL::*WHERE-IS-CASH-FILES* NIL)`` will turn off the file hash. 
I could debug why hash-files stopped working, but perhaps it would be better to just load everything,
(I'm assuming cash vs, cache was a joke? )

**Comment by nbriggs** [comment]
"cash" has annoyed me since day 1 of the XCL hash files implementation!  You find both CACHE and CASH in the code.  I suspect it was intentional as the "cache of the hash file"

**Comment by nbriggs** [comment]
It may be worth asking -- there are two kinds of hash files, the ones made by "HASH" and the ones made by "HASH-FILE" -- are we perhaps making it with one of them and trying to use it with the other?  I think WHERE-IS uses HASH-FILE, and WHEREIS uses HASH, but I haven't traced through it all.

**Comment by masinter** [comment]
Resetting the variables that depend on MEDLEYDIR gave me trouble on the loadups, because they have to change when you resume. 
![image](https://user-images.githubusercontent.com/1116587/111099734-658bf800-8503-11eb-9f56-adc1fbfd5d3d.png)
WHERE-IS uses HASH-FILE _and_ CASH-FILE.
I wish it were as simple as version-mismatch.

**Comment by rmkaplan** [comment]
It’s (SETQ XCL::*WHERE-IS-CASH-FILES* NIL)

with asterisks.

Loading everything is not a solution for quick in-and-out work.  Too many things (like record field names) trash other things.

**Comment by masinter** [comment]
just given the function names, you can assume that it works incrementally, trying to avoid a huge working set.
So going out to make the file consistent every time 'notice' finished processing a file. 

This may be tied to the files left open problem, i noticed earlier that Lisp buffers outputfiles, if you don't close them them, they'll not complete writes.

**Comment by masinter** [comment]
i made a whereis.hash the old fashioned way (without a script) and that seemed to work better so I pushed a new whereis.hash for people to use while looking for the cause.

**Comment by rmkaplan** [comment]
Seems to work, thanks.

**Comment by masinter** [comment]
This issue got fixed a while ago
