### ISSUE TITLE
Loadup-all should stop when one phase fails

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#271]
The loadup-all scripts invokes a sequence of scripts for the different phases.  The script doesn't notice and stop when a phhase  fails and doesn't produce its intended output to feed into the next phase.  If there is a preexisting artifact in the tmp/ directory that the next phase depends on, it just goes ahead and uses that.  And if it can't get all the way through, the final artifacts (lisp.sysout and full.sysout) are not created, and previously existing ones masquerade as if they were new ones that were just built.

For example, my loadup failed just after the makeinit because I apparently don't have an ldeinit (./makeright x apparently doesn't make it).  But the loadup went on, scrolling an enormous amount of stuff in various sysouts (a lot of it having to do with the whereis), and all of it goes away, can't be scrolled.

When I went to test my new features (just in the full, didn't depend on anything else, but the scripts unfortunately at this point are oriented towards making everything from scratch), it took me quite awhile to figure out that I was still looking in an old sysout, the loadup had failed.  Scolling back just in the terminal window is where I found a message about the absent ldeinit.

If the loadups are chained in this way, the different phases should have a way of posting error codes.  And it shouldn't be required that a complete loadup is necessary to work on just the lisp and full sysouts, even though speed is not an issue on current hardware.

**Comment by nbriggs** [comment]
I think this should be a Makefile encoding the dependencies so you don't have to build everything every time.
I'm not sure that we currently have a way for Lisp to exit while returning a normal (Unix) process exit code that scripts can easily interrogate, but I see no reason we couldn't implement it.

I'm looking at whether we can dispense with a separate ldeinit, or at least build it without compiling everything twice and always build it if lde/ldex is built.

**Comment by masinter** [comment]
The problem originally reported has been fixed by touching a 'loadup.timestamp' file. A makefile would be better if there were some reasonable way to create dependencies
