### ISSUE TITLE
Y2K "problem" in Filebrowser

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#29]
when I use Filebrowser on a directory that has dates in the 80's and 90's and also some after 2000, the columns don't align. At least the dates aren't **wrong**.

(Also, the filebrowser seems to start with depth = infinity rather than 1. For running in unix, "hiding" files starting with . would be better with an option to show them all (an enhancement)

**Comment by hjellinek** [comment]
Another issue, which I will turn into its own ticket when I come up with a repeatable test case:
Invoking the FileBrowser on a directory or directory hierarchy with > 65535 files takes a long time, and ends in disappointment: an error message.

**Comment by masinter** [comment]
The problem in the issue title was fixed long ago.
other problems (filing.enumeration.depth default to infinite, uninterruptible directory list) should get separate issues.
