### ISSUE TITLE
Version numbers and default extension for SYSOUT and MAKESYS

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#291]
**Describe the bug**
The recent revision to SYSOUT and MAKESYS reverted to the undesired behavior that sysout and makesys overwrite previous most recent versions, because the internal subroutine \COPYSYS happens below the level at which version numbers are simulated.

If you give it a file name with an explicit version number, e.g. SYSOUT(XXX;2), you still end up with the previous XXXX.SYSOUT being clobbered.

If call SYSOUT(XXXX), with no extension, it defaults to XXXX.SYSOUT (which is good).  But if you give it XXXX;2 (just tack on a version number), the file is XXXX (the 2 is tossed and the extension doesn't default).

**Comment by masinter** [comment]
this was fixed in https://github.com/Interlisp/medley/pull/277 which is still open, can you review it?

**Comment by rmkaplan** [comment]
I tried to make a full with loadup-all.sh, it fell into URAID at the dlinit.

**Comment by masinter** [comment]
fixed I think in #296
