### ISSUE TITLE
unexpected *Error* contextsw(): MP9316 / Enter the URaid

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#301]
**Describe the bug**
irrecoverable error when restarting sysout

**To Reproduce**
1. Files loaded
   This sysout had every lisp source loaded (PROP) and every function masterscoped. with some difficulty.

2. Form to eval and/or menus to click '....'
     SYSOUT(MSALL)
3. What happened? '....'
    

**Expected behavior**
![image](https://user-images.githubusercontent.com/1116587/113495057-75b04b00-94a3-11eb-8dd2-2dd7fd813b49.png)

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Mac/Linux/Cygwin]
 - OS Version: [e.g. High Siera/Ubuntu 18/Raspbian]
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

**Additional context**

**Comment by nbriggs** [comment]
It has mangled the stack somehow.  Have you saved the sysout it produced?  Can you attach it to this problem report?

**Comment by masinter** [comment]
it was too big to attach. here's a share
https://drive.google.com/file/d/16kuJGTWcPHDHCnVw6N3JkD4CZqlvwdFw/view?usp=sharing

**Comment by nbriggs** [comment]
Not sure what you zipped it with, but it won't unzip on my Mac ("End-of-central-directory signature not found").  Can you gzip it instead?

**Comment by masinter** [comment]
https://drive.google.com/file/d/16kuJGTWcPHDHCnVw6N3JkD4CZqlvwdFw/view?usp=sharing

uncompressed (nominally)

**Comment by masinter** [comment]
you should let me look at the changes i made to sysout.
I didn't understand how the IFPage values played a part in setting up the stack so .....

**Comment by nbriggs** [comment]
OK.  You can't make any changes to the IFPage layout without the corresponding changes in the C structure declarations.  As far as I know, the C code pays attention to the _values_ of the various fields that control placement of different parts -- but it's entirely possible that certain pieces "know" where things are.

**Comment by nbriggs** [comment]
What branch of medley was the failing sysout built on?  I'm seeing any commit log entries documenting that there were any IFPage changes on any of the branches I've looked at.

**Comment by masinter** [comment]
it's possibly some field unset? in \COPYSYS (formerly on MOD44IO now on ADIR)
I'm looking now

**Comment by nbriggs** [comment]
Doing a stack-check in URaid:
```
< c 
set CURRENTFX->nextblock in debugger. But it will be reset after this check 
BXBXBXFFBXBXBXFBXBXBXFBXBXBXF
WARN: StackCheck:!=STK_NOTFLG 
content:0xa000      <<<< this looks like a free-stack-block flags value??!!

WARN: CheckBF:Stack-bits set in IVAR 
BF doesn't point TopIVAR:0x129e4
BFBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXFFBXBXBXBXBXBXBXBXBXBXBXBXBX
WARN: StackCheck:!=STK_NOTFLG 
content:0x412c

WARN: CheckBF:Stack-bits set in IVAR 
BXBXBXBXBXBXBXBXBXBXBXBXBXBXBXBXFBXBXBXBXBFBXBXBXBXBXBXBXBXFBXBXBXBXFFBXBXBXBXBXBXBXBXBXFBXBXBXBXBXBXBXBXFFBXBXBXBXBXBXBXBXFF
BIG FSB(s):
Offset: 0x1876 , Size: 0x5c6
Offset: 0x1ec8 , Size: 0x364
Offset: 0x22b8 , Size: 0x36c
Offset: 0x26aa , Size: 0x336
Offset: 0x2e9a , Size: 0xc76
Offset: 0x4bf2 , Size: 0x3ce
Offset: 0x55a2 , Size: 0x8f2
Offset: 0x6056 , Size: 0x24a8

Stack Check done
```

**Comment by masinter** [comment]
Too old
