### ISSUE TITLE
MAKESYS doesn't clear all user state

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#316]
MAKESYS of the full sysout doesn't clear out user state -- when I make the FULL sysout, Iron sees Larry in the who-line, while it greets me with "Hi, Ron" when I start a full made by Ron.

There's a little protocol that MAKESYS before it makes the sysout tries to clear all the state, and rebuild them when it's started. (Including settings of MEDLEYDIRS).
SYSOUT does the same dance but it's assumed that the GREET was done and just issues a warning. GREET is supposed to be undoable. The last GREET is remembered in a special cache to enable this.
@rmkaplan this is what I think is going on.

**Comment by rmkaplan** [comment]
I think the loadup code should be able to run without greeting, i.e. the LOADFULL.LCOM should be the greetfile. to do the loadup.  Is that not what’s happening?

**Comment by masinter** [comment]
the loadups steps don't run user greet (except I suspect loadup-aux might).
What I think is happening is that USERNAME or something needs to be cleared.
