### ISSUE TITLE
Hardcopy to a file in TEDIT:  Asks for PUP host number

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#326]
**Describe the bug**
When I click hardcopy to file in a Tedit window, there is a long delay before I get a pop up asking me for my pup host number

**To Reproduce**
New full Master sysout on a mac
TEDIT(file)
right click hardcopy in title bar, selected "to a file"

**Expected behavior**
No delay, no pop up.

**Screenshots**

**Context (please complete the following information):**
 - OS:Mac
 - OS Version: [e.g. Big Sur]
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

**Additional context**

**Comment by masinter** [comment]
any  chance your init sets DEFAULTPRINTINGHOST?

**Comment by rmkaplan** [comment]
Yes, it sets it to the empty string.

It sets DEFAULTPRINTERTYPE to POSTSCRIPT

It also loads lispusers/SETDEFAULTPRINTER (dated June 1993).

**Comment by rmkaplan** [comment]
The request for the Pup host comes from \CANONICALIZE.PUP.HOSTNAME, called from under CANONICALHOSTNAME under PRINTERTYPE

**Comment by rmkaplan** [comment]
I took SETDEFAULTPRINTER out of my INIT, but it seems that it is still included separately in the full loadup.

**Comment by masinter** [comment]
the long delay is also a problem. There is something missing as far as trying to run PUP even if the network isn't turned on (which it isn't in the regular maiko). Type a control-B when you first start

MAKESYS on startup calls \DEVICEEVENT(AFTERMAKESYS) which calls \ETHEREVENT

**Comment by nbriggs** [comment]
Somewhere it should probably be calling (SUBRCALL ETHER-AVAILABLE) before trying to do network related things.

**Comment by masinter** [comment]
The problem reported is fixed b #327 . The problems of PRESS and INTERPRESS printing were noted in a separate issue #328
