### ISSUE TITLE
PUTCLIPBOARD is now a no-op...unless break or help

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#335]
**Describe the bug**

**To Reproduce**
1. CLIPBOARD loaded in FULL (Master)
2. Open a Tedit window, type something, select it, type meta-C (copy to clipboard), then meta-V (in Tedit or Exec)
3. You should see your selection.  Instead, you will see what happened to be previously in the clipboard (e.g. from another application)

This happens whether PUTCLIPBOARD (the actual function that opens the clipboard copy stream and prints the selection using PRIN3) is compiled or interpreted.

However, if you (BREAK (PRIN3 IN PUTCLIPBOARD)) and then do the meta-C, you get a break.  In the break window you type OK to continue...and it works properly.

Similarly, instead of breaking PRIN3, you edit PUTCLIPBOARD to put a call to HELP *before* the PRIN3, and simply type RETURN in the break window, it also works.

It also works if you put the call to HELP *after* the call to PRIN3.

**Context (please complete the following information):**
 - OS: Mac 
 - OS Version: Big Sur 11.3
 -    XQuartz 2.8.1 (xorg-server 1.20.11)
 - Host arch: x86_64,
 - Maiko version: commit 91fe7d51f9d607bcedde0e78e435ee188a8c84c0
             Date:   Wed Apr 14 09:38:11 2021 -0700
 - IL:MAKESYSDATE: [ 6-May 2021 15:26:52]  (full in current Master)

**Comment by nbriggs** [comment]
It also happens for me when I start medley on a remote Solaris machine with the display on my Mac w/ Xquartz -- the Command-V pastes what was last picked up by Command-C on the Mac outside of medley.

**Comment by masinter** [comment]
That sounds like a different situation. As I understood it, copy and paste run on the machine running medley; the X server;s part was to (possibly) share it's host's paste-buffer if possible.
Does the solaris support copy/paste?

**Comment by nbriggs** [comment]
Nope.  It used to work fine.  `xclip -in` (which is what it executes on Solaris) talks to whatever X server you're running and updates one of the X copy/paste buffers (you can select which one), then `xclip -out` reads back the buffer.  The X copy/paste buffers are also synchronized with the MacOS copy/paste pasteboard -- so if you command-C in a Mac application other than Xquartz the Xquartz copy/paste will be updated.

**Comment by nbriggs** [comment]
One solution seems to be, in the Xquartz preferences, toggle "sync" off and on again.  According to the Xquartz bug reports you might need to do this any time a new version of Xquartz is installed, and it sometimes just happens spontaneously, and they don't quite know why.

**Comment by rmkaplan** [comment]
WIth Medley running, I brought up the Xquartz Clipboard panel, but didn’t click on anything.  And the meta-C worked.  But I don’t know if there is something I had done in this sysout that made it worked.

I also updated to Big Sur 3.1, but I don’t now remember whether this started working after that.

For whatever reason, right now I’m pretending to be happy.

**Comment by rmkaplan** [comment]
This problem seems to have magically disappeared.  I'm closing the issue.

**Comment by rmkaplan** [comment]
Another observation:  This happened again on the Mac, and I did a little exploration.  I restarted the Xserver, didn't help.  But when I rebooted the machine, the problem went away, the clipboard worked as expected.

I didn't try the intermediate position of just logging out and logging in.  If it happens again, I'll try that before rebooting

**Comment by rmkaplan** [comment]
PUTCLIPBOARD is now failing almost consistently (works every once in awhile) on my Mac (Monterey 12.0.1).

I tried restarting a separate Medley, in a separate terminal, after restarting the Xserver, after logging out and logging in, after restarting,  Can't get it to work.  Below is a test function.  I put in a loop to see whether it fails over repeated calls, but it always fails the first time.  (If you put "1" in the clipboard in another application, it fails the second time.)

(DEFINEQ
(CLIPTEST
  [LAMBDA (N)   
    (FOR I GET FROM 1 TO (OR N 100)
       EACHTIME (CL:WITH-OPEN-STREAM (s (CREATE-PROCESS-STREAM "pbcopy"))
                       (PRIN3 I s))
             [SETQ GET (MKATOM (CL:WITH-OPEN-STREAM
                                (s (CREATE-PROCESS-STREAM "pbpaste"))
                                [SETFILEINFO s 'ENDOFSTREAMOP
                                       #'(CL:LAMBDA (s)
                                                (RETFROM (FUNCTION READCCODE)
                                                       NIL]
                                (CONCATCODES (BIND C WHILE (SETQ C (READCCODE s)) COLLECT C]
       UNLESS (EQ I GET) DO (HELP I GET])

**Comment by nbriggs** [comment]
There's something weird going on -- it's not actually executing the `pbcopy` command, as far as I can see -- I tried doing the `CREATE-PROCESS-STREAM` with a script that just logs that it has been called, and unless I do a `TERPRI` on the stream after the `PRIN3` it's not happening.  `(FLUSHOUTPUT s T)` doesn't help.

**Comment by rmkaplan** [comment]
That’s interesting.  Maybe some of the selections from SEDIT (done by PRINTDEF) end with a TERPRI, while other selections don’t.  And PRIN3 never does for simple strings.

**Comment by nbriggs** [comment]
I'm trying to track down where the bytes from the Lisp stream actually make it into the Unix pipe that connects the processes -- then I should be able to see more of what's going on.

**Comment by nbriggs** [comment]
The way the "unixcomm" stuff works is suspect, to say the least.   There are a number of operations implemented to control the process creation, write/read, and shutdown.   The way it does shutdown (which is what happens when medley closes the process-stream) is to terminate the process (kill -9) _and then_ close the pipe over which it was communicating.  The result seems to be that it feeds some characters to `pbcopy`, then terminates the process before `pbcopy` sees the end-of-file on the input, so nothing gets copied.  How it *ever* worked I don't know.   I'm looking at reversing the kill/close order for the shutdown to see if it will work any better!

**Comment by nbriggs** [comment]
@rmkaplan -- try it with the lde/ldex you can build from the maiko 335_fix_process_stream_again branch and see how it works for you.   It's pretty ugly.  I've changed the order it does things so that it always tries to `close()` the pipe to the process, then it wait for up to 0.1s for it to cooperate and exit, if it doesn't then it sends a SIGKILL to take it down and waits up to another 0.1s for it to exit.   I can run `(CLIPTEST 100)` without any problems now -- but it can't do more than about 14/second.  The timing is pretty arbitrary -- I loop at 0.01s checking status and `pbcopy` seems to respond in 0.02-0.05s to the `close()`.  There's no way to determine a priori whether some process will respond to its input/output pipe being closed, by exiting so we're rather stuck here.

**Comment by rmkaplan** [comment]
Looks good so far.

I wonder if there is also an inside-Medley process race condition that was causing the SEDIT processes not to be deleted in the side-by-side examination windows.  The lispusers package EXAMINEDEFS, that I just put out, has a kludge to kill the errant process the next time the function is called, so that there can be at most one dangling SEDIT process.  That’s the best I could do.

**Comment by nbriggs** [comment]
I've merged the new changes to master, so I'll close this again.

I haven't looked at how SEDIT handles the process deletion.
