### ISSUE TITLE
Why so many "Warnings:  Comment not stripped"? when using the DFASL compiler?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#336]
When I compile MASTERSCOPE, the screen fills up with these messages, obscuring anything useful that the compiler might be printing out.

Why is it printing this out?  And more specifically, does this mean that something is wrong with the file so that it isn't being compiled properly?  Do the comments hang around in the compiled file, in an unoptimal way?

If this is innocuous, then the warning message should be removed.

**Comment by masinter** [comment]
These warning messages don't seem to happen now when I cl:compile-file(masterscope)
