### ISSUE TITLE
Can no longer type into window after switching away to another application and back

### ISSUE THREAD

**Issue by meatpi** [Interlisp/medley#337]
**Describe the bug**
Key presses are no longer accepted by medley after switching away to another desktop (Gnome under Fedora). This is intermittent, but once it's happened, medley has to be restarted

**To Reproduce**
Steps to reproduce the behaviour:
1. Type some things into a window
2. Switch back & forth between desktops (several times usually)
3. Can no longer type into medley

**Expected behavior**
Typing should still work

**Screenshots**
N/A

**Context (please complete the following information):**
 - OS: Fedora
 - OS Version: 33
 - Host arch: x86_64
 - Maiko version: 10e3916e7e369c1a55604e0b0465dc66b7f8aaa9
 - IL:MAKESYSDATE: 6th-May-2021 15:26:52

**Comment by masinter** [comment]
Are there any console messages from where X or medley were started?

**Comment by meatpi** [comment]
I'm afraid not

**Comment by nbriggs** [comment]
I think it has got itself confused about whether X events are locked out, or not.

**Comment by masinter** [comment]
On WSL under windows, using Vcxsrv, the X server sometimes crashes or the connection closes -- there are numerous messages printed. Not just for medley but sometimes for emacs started in WSL too.

did you build maikko lde/ldex or did you use one from releases? 10e3916 seems to be a medley version?

Anyway, whatever the cause, would it be useful to be able to restart the X session? Or at least a "SaveVM" ?

**Comment by nbriggs** [comment]
You could attach your favorite debugger to the ldex process and see if it is hung up, as in this instance:
```
(lldb) bt
* thread #1: tid = 0x8456f, 0x97d0b422 libsystem_kernel.dylib`__psynch_mutexwait + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x97d0b422 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x9a819c62 libsystem_pthread.dylib`_pthread_mutex_lock_wait + 99
    frame #2: 0x9a81712b libsystem_pthread.dylib`pthread_mutex_lock + 120
    frame #3: 0x001cb25a libxcb.1.dylib`xcb_writev + 35
    frame #4: 0x000d2f88 libX11.6.dylib`_XSend + 321
    frame #5: 0x000d2de9 libX11.6.dylib`_XEventsQueued + 59
    frame #6: 0x000c7d1b libX11.6.dylib`XPending + 49
    frame #7: 0x00057250 ldex`getXsignaldata(dsp=0x00097c68) + 32 at xwinman.c:186 [opt]
    frame #8: 0x0004d7f7 ldex`getsignaldata(sig=<unavailable>) + 199 at keyevent.c:340 [opt]
    frame #9: 0x97be179b libsystem_platform.dylib`_sigtramp + 43
    frame #10: 0x97d0d3e7 libsystem_kernel.dylib`__writev + 11
    frame #11: 0x001ca5b3 libxcb.1.dylib`_xcb_conn_wait + 681
    frame #12: 0x001cb2d0 libxcb.1.dylib`_xcb_out_send + 61
    frame #13: 0x001cb27f libxcb.1.dylib`xcb_writev + 72
    frame #14: 0x000d2f88 libX11.6.dylib`_XSend + 321
    frame #15: 0x000d36cf libX11.6.dylib`_XFlush + 32
    frame #16: 0x000bad85 libX11.6.dylib`XFlush + 31
    frame #17: 0x00056420 ldex`set_Xmouseposition(x=836, y=224) + 160 at xlspwin.c:324 [opt]
    frame #18: 0x0003e3f2 ldex`DSP_SetMousePos(args=<unavailable>) + 146 at dspsubrs.c:193 [opt]
    frame #19: 0x0002c2f2 ldex`OP_subrcall(subr_no=<unavailable>, argnum=<unavailable>) + 2818 at subr.c:291 [opt]
    frame #20: 0x00020d34 ldex`dispatch + 3956 at xc.c:657 [opt]
    frame #21: 0x0003aa63 ldex`main(argc=<unavailable>, argv=<unavailable>) + 1315 at main.c:542 [opt]
    frame #22: 0x913876ad libdyld.dylib`start + 1
```
This is on macOS, where, as with Linux, we don't lock X updates, and it seems to have taken a SIGIO during the `XFlush()` which caused it to try to pick up any additional X events and then it deadlocks (I think) in `XPending()`.   This didn't use to be a problem on macOS with older versions of XQuartz, but now it has been updated we're probably seeing the same issues that Xorg servers on Linux distros see.

It should be possible to add -DLOCK_X_UPDATES to the compiler options in the makefile.linux... fragment for your system and see if it still happens.  I'm experimenting with that on macOS/XQuartz 2.8.1 (xorg-server 1.20.11)

**Comment by masinter** [comment]
@nbriggs didn't you fix this with the new IO regime? Reopen if not

**Comment by nbriggs** [comment]
@masinter I believe this to be fixed.
