### ISSUE TITLE
Read table with multiple PACKAGEDELIMS

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#340]
The INTERLISP readtable (I don't know about others) has 3 characters registered as PACKAGEDELIM:  Colon, ctrl-^, and the section-character (code 167).

This seems like a bug.  In some files you see the ^^, others you see section, others you see :.  So if you are searching (or maybe even WHEREIS) for a qualified name, it's kind of a crap shoot.

This seems like a bug.  Is there any motivation for this? If not, is there any way of slowing unwinding back to just colon for system-defined tables?

**Comment by nbriggs** [comment]
The NS section symbol was for compatibility with Lyric beta files, ctrl-^ was the new choice -- per comment in sources/ATBL.

I don't know why ctrl-^ was chosen for file writing/reading over colon, but it was a conscious choice.  I suspect there's an issue with life before packages get turned on, probably during bootstrapping a new system?

--  Nick

**Comment by rmkaplan** [comment]
So maybe there was some motivation. But the downstream consequences are that there is no consistency in files.  And it may be even a little bit random which of the 3 candidates is used when.

Do fetches and replaced still CLISPIFY in that way?  When I do (CLISPIFY ‘(fetch (FOO FIE) of FUM)) I get 
  (FUM %: FOO.FIE), not packed together.  That DWIMIFYs back to the original.

**Comment by masinter** [comment]
WHEREIS seems to work with package-qualified functions; I haven't looked how but I imagine it prints things unambiguously.

So I'm not sure what the bug is. What doesn't work? Some files need : because they use packages. Some files need some other character and control-^ seems as good as any. If you're using grep you can make a regexp; if you're using Lisp you have the choice of readable to guide your filepos.

**Comment by rmkaplan** [comment]
Well, one thing that is troublesome is trying to make sure you can decode the file-info expressions, where you are looking at keywords that might be marked in different ways.

**Comment by rmkaplan** [comment]
I now see that this breaks down into separate issues:  what is the package-delim in the define-file-info expression vs. what is the package encoding for anything lower down in the file that happens also to use the same readtable.  This mistake was in not seeing that these are 2 completely different contexts and that somehow they should use exactly the same read table

The functions that write and read the fileinfo expression can use a different readtable set up just for that purpose:  it includes all of the current characters (: ^^ section) when it reads, for backward compatibiility, but it should use colon for printing going forward.  The old interlisp file readtable, if that's the default for the rest of a legacy file can do whatever it used to do.

There is no need to see magical black boxes on the first line of an Medley source file when you look at it from outside Medley, particularly now that we can have unicode character encodings.  (The blackboxes that show up in some Mac editors have an actual purpose.)

**Comment by nbriggs** [comment]
That makes sense.

**Comment by rmkaplan** [comment]
Is it safe to assume that, if a DEFINE-FILE-INFO expression is on a file, then it will be the first expression on the file?

Some code makes that assumption, some code (e.g. LOAD) doesn't.

**Comment by nbriggs** [comment]
There's no case, in 1800+ lisp source and compiled files we have, where there is a DEFINE-FILE-INFO expression on the file where it is NOT the first expression.  Presumably we're not going to create any such files going forward either.

**Comment by rmkaplan** [comment]
It’s not a bug, as far as we know, although it is spread out enough that there are likely to be more corner cases than I have so far encountered.  But it’s an architectural confusion that may lead to future bugs.

It’s also confusing, if you look at a file in an external editor (or in TEDIT) that you see black boxes  for some but not all package delimiters and you can’t tell the difference between those and font change controls (in some editors all the control characters are suppressed, so you don’t even see a semantically meaningful distinction).
