### ISSUE TITLE
MASTERSCOPE fails on the file RECORD

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#341]
. ANALYZE ON RECORD
causes Masterscope to think that various system record names are actually file names, and for some reason it tries to find those files, and fails.

It isn't clear why Masterscope should ever try to go to a new file in the middle of analyzing a function (or even all the functions on a file), let alone mistake a record name for a file name.  Perhaps it has a provision for loading files that are mentioned in FILES commands in the COMS, and that is somehow getting perverted for RECORD?

This may be an interaction with other things in the environment, my recollection is that this worked at one point and now does not.

**Comment by rmkaplan** [comment]
Larry mentioned that the problem might be a confusion betwen RECORD as the name of the file and RECORD as a keyword in the query language.  I put RECORD in quotes, and that seemed to solve the problem--the analysis goes all the way through

**Comment by masinter** [comment]
I don't think this can be fixed generally without major upheaval in the parser or worth it to patch when there's an obvious work-around.
