### ISSUE TITLE
Plan for early conversion to modified Unicode internally

### ISSUE THREAD

**Issue by johnwcowan** [Interlisp/medley#353]
This is a plan for converting Medley from internal XCCS to Medley Reduced Unicode (MRU), a new 16-bit character set closely based on Unicode. I think this should happen with fairly high priority (contrary to my past opinions). 

MRU contains all the characters of Plane 0 (the Basic Multilingual Plane) of Unicode with the same code points, but it also contains certain emoji and CJK characters of Planes 1-3, assigned to the Private Use Area (U+E000 to U+F8FF).  MRU is an internal code only, and is converted to UTF-8 for external use.

I have written down all the steps I can think of.

0. Discover more steps and add them (continuing effort).
1. Figure out which characters will be present in MRU and their codepoints (done, mapping table at [MEDLEY-UCS-2.TXT](https://github.com/Interlisp/medley/files/6859855/MEDLEY-UCS-2.TXT)).
2. Verify Ron's existing mapping tables at  [xccs-mapping.zip](https://github.com/Interlisp/medley/files/6859887/xccs-mapping.zip) and correct any errors (in progress, aeth has found some errors already).
3. Rearrange strike fonts to be in MRU layout based on the mapping tables.  ASCII-only strike fonts and strike fonts based on BDF aren't a problem as they are already Unicode.
4. Process our existing Tedit files, converting the XCCS in them to UTF-8.  (Presumably Lisp files are entirely in ASCII plus the control characters for font selection.)
5. Rewrite or abandon the I/O logic for writing XCCS files.
6. Entirely new logic for reading / writing UTF-8 files (translated using the table in step 1).  Characters outside the MRU set are mapped to and from  MRU's FFFD REPLACEMENT CHARACTER.

**Comment by masinter** [comment]
Lisp source files often contain ^ and _ for up-arrow / left arrow, shouldn't there be a plan for them to appear properly when translated to UTF-8?
Some TEdit files may have "private use" characters for "Xerox Private Data". I 'm not sure. There's a Xerox Logo font for E R O X in logo text.

**Comment by nbriggs** [comment]
The logo font also has Xerox Private Data stamps, I have a Trillium font with the Trillium logo (and I think the letters separated), and so on.  I'm not sure how that ends up represented in a TEdit file.

**Comment by johnwcowan** [comment]
> Lisp source files often contain ^ and _ for up-arrow / left arrow, shouldn't there be a plan for them to appear properly when translated to UTF-8?

That's a good question.  In Squeak it is left up to the font: Smalltalkers are now very used to reading `a _ b` instead of `a ← b` for assignment, although Algol/Pascal `a := b` is available as an alternative.  Most people find it hard to type ←, since there is no key on the vast majority of all keyboards for it.  Historically ↑ and ← were introduced in ASCII-1963 and changed four years later, but unfortunately the Teletype model 33, which had arrows (and no lower case), lingered on much longer.

 Squeak fonts use the [Mac OS Roman character set](https://en.wikipedia.org/wiki/Mac_OS_Roman), which has 256 characters; however, it uses the "generic currency symbol" ¤ at 0xDB instead of the euro symbol as Mac OS Roman does nowadays.

The ¤ is also problematic for Medley.  In the printed charts it appears in the 0024 position (which is $ in ASCII and Unicode), and $ is banished to 00A4 (the Latin-1 and Unicode position of ).  However, Ron's mapping shows both of these characters as being U+0024, suggesting that in Medley fonts $ appears at 24 and not ¤. 

(The ¤ character was originally introduced into ISO 646 (ASCII) in the variant ISO-646-IRV ("international reference version") supposedly at Soviet insistence; they did not want to see a purely national character in an international 7-bit character set.  Later the variants were abandoned with the dominance of 8-bit and larger character sets, and ISO 646 is now ASCII once again.)

**Comment by nbriggs** [comment]
In the "office" fonts, such as Modern, Classic, Terminal the ASCII `_` is rendered as an underscore, however in the regular (Alto) fonts such as Helvetica, Times Roman, Gacha the `_` is rendered as `←`, likewise the caret/up-arrow.   However, the dollar sign at 0x24  seems to be rendered as dollar sign in most/all the fonts we have.  The generic currency is present in (at least some of the fonts) up at 0xA4 and/or 0xA8(!)

**Comment by masinter** [comment]
I'm pretty sure all of the fonts we have predate the Euro sign

**Comment by masinter** [comment]
there may be code that assumes XCCS, e.g., TEDITHCPY "vars for Japanese Line Break"

**Comment by johnwcowan** [comment]
Attached is the proposed mapping table for Medley Reduced Unicode (MRU), a 16-bit encoding that can be used as Medley's internal encoding in place of XCCS.

We start with Plane 0, which we then enhance by occupying parts of the Plane 0 Private Use Area (U+E000–U+F8FF) so that we can represent all of the [Unihan Core 2020](https://www.unicode.org/L2/L2018/18279r-iicore-2020.pdf) character repertoire and all existing emoji.  Unihan Core 2020 is a region-agnostic subset of 20,000 Han characters in modern use.

The file specifies 1904 Unihan Core 2020 characters from Plane 2, which are mapped to MRU E000-E76F, and 3005 emoji characters from Plane 1, which are mapped to MRU E770-EBBA.  As more emoji are added to Unicode, we have plenty of room to represent them in MRU, as the Private Use Area has 6400 codepoints.

[medley-reduced-unicode.txt](https://github.com/Interlisp/medley/files/7206823/medley-reduced-unicode.txt)

**Comment by masinter** [comment]
I am (or was) familiar with the forces that led to increasing the code space beyond 32 bits, and the adoption of ugly utf-16/Big or Little Endian, with or without an (optional or mandatory) Byte Order Mark.
1. leave medley  using XCCS internally, fat or thin (plane 0)*
2. Use utf-16be in fat strings, plane 0 for thin
3. all internal strings are utf-8

If the point of MRU is to make more complete the round-trip from Unicode to Medley and back, that's great.

But we don't need to change the internal format in strings, 
Changing it to MRU doesn't help; we'd still need a mapping table with 'real' Unicode.

What am I missing?

**Comment by johnwcowan** [comment]
> I am (or was) familiar with the forces that led to increasing the code space beyond 32 bits

Beyond 16 bits, just for the record.

> 1. leave medley  using XCCS internally, fat or thin (plane 0)*

If we want to support more than just the few thousand characters of XCCS 2.0, we have two choices: extend XCCS or reduce Unicode.  Extending XCCS turns out to be difficult and laborious.  My MRU proposal is intended to reduce Unicode in a straightforward way.

> 2. Use utf-16be in fat strings, plane 0 for thin
> 3. all internal strings are utf-8

That's a question of how strings are represented below the character level.  What concerns me is the mapping between characters and character codes visible at the Interlisp level.  Making that close to Unicode simplifies a great deal.

> Changing it to MRU doesn't help; we'd still need a mapping table with 'real' Unicode.

True, but only a much smaller table is required: 3006 characters rather than 65536.

**Comment by masinter** [comment]
the 1, 2, 3 were meant as alternatives

4. Use MRU in fat strings, plane 0 in thin. 

Do we make a new MRU-compatible external format?

I've been thinking about using a new SUBR for "\DISPLAYLINE" as
a way of integrating outline fonts into Medley.
Input would be a UTF-8 or UTF-16be  byte sequence.
Output would be a (possibly color/grayscale) raster with baseline and width
written into a supplied bitmap.
width is possibly non-monotonic?  Or at least width(a) + width(b) neq width(a+b)

**Comment by johnwcowan** [comment]
> the 1, 2, 3 were meant as alternatives
> 
> 1. Use MRU in fat strings, plane 0 in thin.

Yes, provided you mean "U+0000-U+00FF" (ASCII and Latin-1) in thin strings.  That will make certain thin strings fatter.  Plane 0 is U+0000-U+FFFF.

> Do we make a new MRU-compatible external format?

I see no reason for it.   The external format should be UTF-8.

> 
> I've been thinking about using a new SUBR for "\DISPLAYLINE" as
> a way of integrating outline fonts into Medley.
> Input would be a UTF-8 or UTF-16be byte sequence.
> Output would be a (possibly color/grayscale) raster with baseline and width
> written into a supplied bitmap.

If we convert from XCCS to MRU we don't actually have to do this unless the string contains a character between E000 and F8FF.

> width is possibly non-monotonic? Or at least width(a) + width(b) neq width(a+b)

Yes.  That's what happens when you use combining characters, zero-width spaces, etc.

**Comment by masinter** [comment]
is there any case where width isn't "convex"? (where widt(a+b) < width(a) or width(b)?

**Comment by johnwcowan** [comment]
Yes. That can happen as a result of negative kerning, where two letters are pushed closer together than they would normally be, or of ligaturing:  ffi is wider than ﬃ.

**Comment by johnwcowan** [comment]
See #906 for further development.
