### ISSUE TITLE
prettyprinter doesn't seem to print comments in files correctly

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#364]
not sure if this is a bug related to EOL or somehing more ancient.
look in library/POSTSCRIPTSTREAM table of 
 ("356,356" SYMBOL "2,365")
                                                             (* ; "integralbottom")
        ("356,357" SYMBOL "2,364")

**Comment by nbriggs** [comment]
What I see (with printable control characters) is:
```
        ("356,356" SYMBOL "2,365")
                                                             ^F^C(* ; "integralbottom")^F^A
        ("356,357" SYMBOL "2,364")
```

**Comment by masinter** [comment]
yes, it  should be two lines, not three

**Comment by nbriggs** [comment]
Why is the documentation for POSTSCRIPTSTREAM in lispusers, but the code is in library?
