### ISSUE TITLE
don't just warn when EXPORTS.ALL is needed when compiling

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#365]
compiling is so fast no one will watch. Files that need other files to compile should just load them.

**Comment by rmkaplan** [comment]
What date is that file?  When I look in the merge-ron branch, I don’t see those anymore (as I shouldn’t).

(And probably this wouldn’t depend on EXPORTS.ALL if I added a functional interface for creating an externalformat so the record doesn’t have to be available.  And maybe the same for Unicode and Japanese.  I’ll do that on the next round.)

But generally, when working on low-level system code that may change macros or other declarations, I have discovered that you have to be a little careful about when exports.all gets loaded.  If it happens automatically you can trash your working environment.  These format creating files are much less low-level than they were, the format declaration may be the only vestige.

**Comment by masinter** [comment]
I was going through the "files changed" list for the Cleanup-interface... PR. I can't seem to find the file anymore.
What did you do if it doesn't warn you any more?

**Comment by masinter** [comment]
Not clear what the issue is
