### ISSUE TITLE
*EXTERNALFORMAT* doesn't belong in the READER-ENVIRONMENT

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#371]
it's a stream property.
see sources/CMLREAD DEFMACRO WITH-READER-ENVIRONMENT

where are the other variables declared SPECIAL? Why just the external format? Is this really at the right level? The other elements don't depend / vary when you change XCCS and UTF-8... they're EXTERNAL-FORMAT independent

**Comment by rmkaplan** [comment]
I don't know where the other variables are declared special, but I tested and discovered that they are.  (We don't have a WHEREIS that tells us about things like that.)

But as I think was mentioned in an email thread, binding the format variable here was from an earlier stage, before the format functions moved down into fields of the stream. This macro, unfortunately, does not take the stream as an argument, so it cannot locally interpret the format field of an environment, that has to be done with a separate call.  So it is misleading that this macro pulls out the format, it will be removed in the next round.

This macro binds things for higher-level interpretation of character codes in string and atoms, the format deals with the lower-level coercion from byte sequences to character codes.

**Comment by masinter** [comment]
Does "it will be removed in the next round" means you'll change it back to not bind *EXTERNAL-FORMAT* in WITH-READER-ENVIRONMENT?

**Comment by rmkaplan** [comment]
Yes

**Comment by masinter** [comment]
thanks
