### ISSUE TITLE
Rename current loadup-full.sh to loadup-full-from-lisp.sh, add new loadup-full.sh

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#375]
There is currently no simple script for just building a full.sysout without also doing the exports and whereis in the loadup-aux.sh

Current loadup-full.sh actually builds only on top of a lisp that was already made.

To follow the regular pattern established by the preceding scripts, the current full script should be renamed, the new full script should do everything in loadup-all prior to loadup-aux, and loadup-all should do the new loadup-full (which would package all of the steps) followed by loadup-aux.

Apart from being more rational, this would help if we decide not to automatically include sysouts in the repo but expect developers to build when they fetch changes.  The slow part of the process (particularly with the 5 second delay taken out) is in the aux.

**Comment by masinter** [comment]
Bill's been working on automating loadups and releases...  i'm asking for his review.

**Comment by rmkaplan** [comment]
Would the automatic process work on different development branches, or just the master and master-releases?
