### ISSUE TITLE
Can Medley see files on other git branches?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#376]
Suppose I am working in one branch, and I want to use Medley tools (COMPAREDEFS, PF, SEE...) to look over at something on another branch.  Presuming that the  files on the other branch are stashed away somewhere in the git universe, is it possible to have a Medley routine that would, given a filename and a branch name, produce a path to that file in that branch that OPENSTREAM and other file operations can work on?

Perhaps accessed through a separate {GIT} file device to ensure that such files can be opened read-only.

**Comment by masinter** [comment]
I'll work on converting restore-versions.sh to Lisp (with calls to ShellCommand("git" ...).  I think with some hacking you can do it.

(a) copy current version 
(b) do "git checkout branchname -- filename" (or commit tag, using unix file name)
(c) copy file to tmp/versions/filename 
(d) move (a) copy back


IF we had a web file system  {https:hostname}/url-path   we could make {http:github.com}<interlisp>medley> type references.

**Comment by masinter** [comment]
I think with GITFNS we have something that works pretty much.
Doing it more robustly (not having to cope with error messages in-band) or efficiently (not copying files, using the API, git plumbing) may not be worth it.
I think this issue is worthy of closing.
