### ISSUE TITLE
Should WRITEFILE allow for a DEFINE-FILE-INFO?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#389]
Current it just writes the file with the old-interlisp-file environment, so it apparently wasn't upgraded when the commonlisp stuff came along.

Is there any reason not to upgrade it?

**Comment by masinter** [comment]
I don't know about the backward compatibility issues. I don't see the argument for adding it as the default. And if it's a new feature, I don't think we should add new features without a clear use case and well-articulated requirements. Just to keep new features down.
Feel free to reopen.

**Comment by rmkaplan** [comment]
In the inherited code, READFILE interpreted the DEFINE-FILE-INFO if it was there, WRITEFILE didn’t write it.

READFILE assumes the old interlisp file environment if it doesn’t see a DEFINE-FILE-INFO.

One thing I see that needs to be done is to at least ensure that WRITEFILE imposes the format in the old-interlisp environment (:XCCS).  That will be fixed, if such files to not carry their own marking.
