### ISSUE TITLE
CHAPNUMBERS.TEDIT in docs/dinfo has a smashed font

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#405]
It has MODEBN instead of MODERN.  When I tried to use a Mac text editor to fix it, I got an error that size 13 doesn't exist.

So maybe a more significant smash.

**Comment by rmkaplan** [comment]
And another one: The description of the function DEFAULTFONT beings with Kanji

**Comment by masinter** [comment]
The files in docs/dinfo are not smashed -- if you type 'man log' at a command prompt, you will see the page rendered correctly. Rather, the files in doc/dinfo named *.tedit are not really tedit files. Some choices:
- [ ] change the file names to something else (CHAPNUMBERS.IRM ?) and fix DINFO to look for those
- [ ] fix TEDIT so it recognizes those files and processes them
- [ ] change DINFO / HELPSYS etc. so it doesn't require an incompatible format, and convert the files 
- [ ] live with the incompatibility and document it in a README or README-BEFORE-TRYING-TO-TEDIT file

**Comment by rmkaplan** [comment]
I believe that the man/IRM files have standard Tedit-file sections embedded in some extra indexing stuff.  The internal calls that Dinfo makes to Tedit specify starting and ending byte positions for the well-formed piece-tables of theTedit subsections.

So you can’t call TEDIT/OPENTEXTSTREAM directly on these files, without specifying the proper START and END byte positions, which DINFO knows how to extract from its own wrapping information.

For sure these should be given a non-Tedit extension to eliminate any suggestion that Tedit can interpret them directly (your first option).  I don’t think Tedit itself should be modified to know about the wrapping format.  

I can see a possible alternative approach that would allow Tedit to be the top-level opener but still without making Tedit itself even more complicated.  That would be to figure out an image object that contains the formatting and indexing information that DINFO requires, and embed that as, say, the first object in the file.  Its functions would execute invisibly when the window is opened after an ordinary call to TEDIT, and they could side-effect the window/textstream/textobj to support whatever DINFO needs to drive its special behavior.  If this could be done, it might be cleaner way of preserving modularity. But my bet:  changing the file extension is an easier thing to do.

**Comment by rmkaplan** [comment]
One other note:  I think that the original MODEBN vs MODERN  and the 13 font size was a smash, but that the fact that plain TEDIT can't open these files is not.

Also, as I noted elsewhere, the Kanji characters show up because of a bug in Tedit, that it doesn't do the right thing when a 2-byte character on the file crosses a 512-byte file-buffer boundary.  I have fixed that in my rework of the internals. (But a better fix is to deal with that at open-time:  if a character of a 2-byte piece crosses a boundary, split the piece into 3 parts:  a file-piece up to but not including the first byte of the offending character, a 2-byte in-memory string piece that contains just the offending character, and another file-piece that has the rest.  This would move the problem out of the inner BIN, BACKBIN, PEEKBIN functions, where the implementation is very tricky.)

**Comment by masinter** [comment]
does the IRM use any two-byte characters?

**Comment by masinter** [comment]
many duplicates ... will converge on this one. Look for references to follow.

**Comment by masinter** [comment]
Note that I think you *can* print the DInfo TEdit files if  you load the imageobject GETFN before you try to print. At least that's a theory worth pursuing.

**Comment by rmkaplan** [comment]
I think the rework of Tedit has eliminated all of the XCCS glitches  discussed here.  The 10/13 swap still affects certain files, in some cases those can be recovered by manual intervention, but those are separate one-offs.  I'm closing this issue.
