### ISSUE TITLE
Raspberry pi OS on 64 bit reports 'aarch64' as machine type, not armv7l

### ISSUE THREAD

**Issue by JTurco32** [Interlisp/medley#409]
Hello,

i was trying to use this on my raspberry pi 400 with the maiko armv7l package, and i keep getting a 'lde not found' error when trying to start the system. the OS is Raspbian 10 64 bit.

**Comment by masinter** [comment]
hi -- did you download both the medley and maiko tgz files? Did it say what file wasn't found?
A screen snapshot would help :smile:

thanks

**Comment by JTurco32** [comment]
thanks for responding. i have it setup like that and im still getting the "lde" not found.`pi@raspberrypi:~/Downloads/lisp/medley $ ./run-medley 
lde not found`

**Comment by masinter** [comment]
if you ls these directories you should see
|  medley    |         loadups/  greetfiles/  run-medley* |
| medley/loadups |   full.sysout |
| maiko |  bin/ linux.armv7l/ |
| maiko/bin |  machinetype* osversion* |
| maiko/armv7l | lde ldex |

if you 
```
cd maiko/bin 
./machinetype
./osversion
```
you should see 'armv7l' and 'linux' respectively

pi@pi1:~ $ ls maiko/linux.armv7l
lde  ldex ldeinit vdate 
pi@pi1:~ $ cd maiko/bin
pi@pi1:~/maiko $ cd bin
pi@pi1:~/maiko/bin $ ls
ChangeLog              machinetype                makefile-header               makefile-linux.x86_64-x    makeright
compile-flags          makefile-cygwin.x86_64-x   makefile-init-darwin.386      makefile-openbsd.x86_64-x  osversion
config.guess           makefile-darwin.386-x      makefile-init-darwin.aarch64  makefile-sunos5.386-x      README
config.sub             makefile-darwin.aarch64-x  makefile-init-linux.armv7l    makefile-sunos5.i386-x     test.vm
copyright              makefile-darwin.ppc-x      makefile-init-linux.armv7l~   makefile-sunos5.sparc-x    u2dnames.sed
dbxinit.txt            makefile-darwin.x86_64-x   makefile-init-sunos5.sparc    makefile-sunos5.x86_64-x   unix2dos.sed
environment-variables  makefile-dos               makefile-linux.386-x          makefile-tail
legacy                 makefile-freebsd.386-x     makefile-linux.armv7l-x       makeinitlde
pi@pi1:~/maiko/bin $ cd
pi@pi1:~ $ cd maiko/bin
pi@pi1:~/maiko/bin $ ./machinetype
armv7l
pi@pi1:~/maiko/bin $ ./osversion
linux
pi@pi1:~/maiko/bin $ cd
pi@pi1:~ $ cd medley/
pi@pi1:~/medley $ ./run-medley
running: lde -g 1440x900 -sc 1440x900 -m 256  /home/pi/lisp.virtualmem
greet: /home/pi/medley/greetfiles/SIMPLE-INIT

**Comment by masinter** [comment]
alternatively, try building your own maiko
```
rm -r maiko
git clone https://github.com/interlisp/maiko
cd maiko/bin
./makeright x

```
let me double check the latest release -- we haven't automated releases yet and I might have messed up when I made it

**Comment by JTurco32** [comment]
I may of found the issue and you provided a solution.
when i run ./machinetype it shows aarch64 (im running 64 bit raspberry pi
OS)

i did a build from souce for makio, and now all is well! Thank you very
much for your help! now i have to learn how to use this....

**Comment by masinter** [comment]
thank you for being a pioneer ... I'll retitle this issue

**Comment by nbriggs** [comment]
A Pi system installed with a 64-bit OS should report aarch64 -- but we're only building the 32-bit (armv7l) version.  I believe Raspbian runs the processor in 32-bit mode (and reports armv7l as the cpu type), but you can install a 64-bit OS if you want, which is apparently what happened here.

**Comment by JTurco32** [comment]
Not a problem. I found the manual to medley lisp in the repo. I'll give
that a look at. I'm also learning lisp as well so should be interesting.

**Comment by JTurco32** [comment]
@nbriggs exactly. I didn't realize i was using the 32bit binaries. Well we now know that it works on 64bit raspberry pi os, which they plan to make "public" sometime soon (its technically still in beta, but with the performance gains im getting it's a step in the right direction)

**Comment by masinter** [comment]
I thought we had some document which I needed to update, since I was initially confused on the point that the P400 (Pi4) was a 64 bit processor running a 32-bit OS,.

But I searched (grep -ir "raspb") in all our repos (web site, medley, maiko, wiki) and didn't see anything to update.

If you want to "learn" Interlisp, try (Steve Kaisler's book)[https://interlisp.org/docs/Interlisp-language-usage-sk.pdf].
 @skaisler1  is working on delivering volumes 2 and 3.    A P400 + a SD card that boots into Interlisp + ROoms + Notecards + Smalltalk  + Loops/Truckin  seems like a great way to givve the "Lisp Machine" experience.

**Comment by JTurco32** [comment]
thanks for the link. It seems like i should be learning lisp first before
getting into interlisp. im sorry to ask this here and derail the topic, but
could one not use interlisp in common lisp mode and "learn" that way
following for example "gentle introduction to symbolic computing"? or is it
better to use a interpreter like sbcl?

**Comment by masinter** [comment]
I think your plan is a great idea. We definitely need more users. 😸

**Comment by masinter** [comment]
i'm still not sure what to say where about the pi4.  Maybe in the release notes?

It does defy convention: "machinetype" changes and "osversion" stays "Linux".

**Comment by nbriggs** [comment]
What convention is it defying?  The config.sub (from the GNU collection) has
```
                # Recognize the canonical CPU types that are allowed with any                                                                                                       
                # company name.                                                                                                                                                     
                case $cpu in                                                                                                                                                        
               [...]
                        | aarch64 | aarch64_be \                                                                                                                                    
               [...]
                        | arm | arm[lb]e | arme[lb] | armv* \                                                                                                                       
```
so we end up with `armv7l` when it's presenting as 32-bit and `aarch64` when it presents as 64-bit -- and for the Pi that depends on how your (Linux) kernel was compiled.

**Comment by masinter** [comment]
in PR #476  I added some more information when it can't find lde -- it should tell you where it looked.

So now I can close this issue.
