### ISSUE TITLE
ARG not READERENVIRONMENT when LOAD or LOADFNS an empty file

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#410]
not sure how I wound up with a null file version, and when I was trying to LOADFNS or LOAD the file,
it gave an ARG NOT READERENVIRONMENT error.
Not sure what the error should be.

**Comment by rmkaplan** [comment]
A truly empty file?  I don't see that behavior with LOAD, only with LOADFNS.  LOAD seems to think it is a commonlisp file (the inherited test is whether or not it starts with a paren) and prints the true message that it read 0 bytes.

Presumably LOADFNS should behave as it would on a non-empty file that simply didn't have the specified function

**Comment by masinter** [comment]
It was an empty new version of a previously LOADed file (or I had loaded the .LCOM but was LOADing the source PROP).

I cant seem to reproduce the LOAD behavior, but I think if you have FOO;1 FOO;2 and then FOO;3 is empty etc.

Just quietly failing to LOAD anything is probably not appropriate.

**Comment by masinter** [comment]
New theory:  it isn't unsafe behavior -- it gives an error.
Might not be the right error, but if we don't know, it isn't a bug.
