### ISSUE TITLE
Trouble loading LOOPS sources

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#414]
This will probably spawn a number of independent issues.

Loading LOADLOOPS works OK, though it expects MAKESYSNAME to be :LYRIC or :MEDLEY (it's currently a string), so it doesn't attempt to load the expected compatibility patch file.

Executing `(LOADLOOPS "{dsk}<tmp>")` will fail if you don't have compiled versions of the files available, since it supplies `(COMPILED)` by default to `DOFILESLOAD`.

Executing `(LOADLOOPS "{dsk}<tmp>" 'SOURCE)` attempts to load parts of the Interlisp system sources (as source) which turns out to be a very bad idea (redefining pieces of the system that cannot/should not run interpreted, including the garbage collector and data type implementation).

Executing `(LOADLOOPS "{dsk}<tmp>" 'PROP)` either with or without  file `LOOPSSPEEDUPS` does unrecoverable damage to the sysout (resulting in errors such as `In CHECK-BINDABLE: Attempt to bind a non-symbol {}0#55`) as it tries to load file LOOPSDATATYPES.

LOOPS has a very delicate interface to and dependencies on the underlying system implementation, and if we're going to run it on current MEDLEY systems it will need some careful inspection and updating.

**Comment by nbriggs** [comment]
@skaisler1  -- FYI

**Comment by masinter** [comment]
1. ok on makesysname, I couldn't remember what it was for.
2. yes we should compile LOOPS. the Envos repo *and* the copy in the history REPO are all EOLSwapped (The TEDIT files want a size 13 font, which is a sign that CR (13) has been swapped with LF (10).
3. There is some maiko code for Loops support

I'm tempted to make another repo for Loops (like we did for notecards) just to separate development and not intermix the commits.  Alternatively we could dedicate a branch to "get loops working".

**Comment by masinter** [comment]
I think all the issues raised have been resolved; open new issues if any remain.
