### ISSUE TITLE
run-medley doesn't set -sc for the screen resolution

### ISSUE THREAD

**Issue by Kirtai** [Interlisp/medley#42]
Without setting -sc, the screen defaults to the full size of my display on Kubuntu 20.04. This is not good since I have multiple monitors and it sets the size if the Medley screen to the *overall* size of *all* monitors put together. There doesn't seem to be a way to pass in -sc to the script.

**Comment by masinter** [comment]
the run-medley script really needs an overhaul; tcsh script to /bin/sh.
. i just put lde and ldex into /usr/local/bin and call lde directly.
there's a maximum size of 2^21   check out the windows-setup.txt in the 'keep old versions' branch of medley
