### ISSUE TITLE
Remove phone numbers from usage text

### ISSUE THREAD

**Issue by hjellinek** [Interlisp/medley#43]
I ran the `bin/medley` script with `LDESRCESYSOUT` set to a bogus value and received this error message:

````
Coudn't find a sysout to run;
 ldex options:
 [...]

If you have any further questions, please refer to the manual or
call our tech support at (800)228-5325 or (510)763-0516.
````
Since this is unsupported software, we should remove that last couple of lines or replace it with something like
````
Please refer to the manual for further information.
````

**Comment by masinter** [comment]
missing some context;-- where did you find a bin directory?

 I tried to rename the 'medley' script to 'run-medley'.(but there is no longer a bin directory for what is available  in the 'keep-old-versions' branch of the GitHub interlisp/medley repo.
There are already scripts in the envos directories for installing and running medley (probably things John didn't necessarily share back with PARC to support Ron's LFG. I need to dig in..

**Comment by masinter** [comment]
fixed wording in maiko sources (not in bin/medley script). This is my first time closing an issue, I just pushed the fix to the master repo, but maybe i should have done a branch and a PR?
