### ISSUE TITLE
scripts/loadup-full.sh seems to just do the last part

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#431]
Is it equivalent now to loadup-full-from-lisp.sh?

I expected it to do everything in loadup-all.sh except for the auxiliary stuff.  I.e., start from the makeinit, but stop after the full.

**Comment by masinter** [comment]
I misunderstood. The name "loadup-full" was originally (before MAKEINIT) was for what it (once again) does now: take the released lisp and make a new full -- for use when you're only working on things loaded into full and not into library.

That's problematic if we're no longer committing builds.

**Comment by rmkaplan** [comment]
I’m looking for something that builds from scratch all the way up to full, but doesn’t spend the time on the aux stuff.

I think the loadup-full should be broken out of loadup-all.sh, which should then invoke it.

**Comment by masinter** [comment]
This is all of loadup-all.sh
```
#!/bin/sh
export MEDLEYDIR=`pwd`
if [ ! -x run-medley ] ; then
    echo run from MEDLEYDIR
    exit 1
fi
# set timestamp
mkdir -p ./tmp
touch ./tmp/loadup.timestamp

./scripts/loadup-init.sh && \
    ./scripts/loadup-mid-from-init.sh && \
    ./scripts/loadup-lisp-from-mid.sh && \
    ./scripts/loadup-full-from-lisp.sh && \
    ./scripts/loadup-aux.sh && \
    echo "**** DONE ****"
```

**Comment by rmkaplan** [comment]
Right, easy enough to pull it apart, except that I don’t know where/how the timestamp stuff would then be applied.

**Comment by nbriggs** [comment]
I just ignore the timestamp stuff and copy/paste this into a shell:
```
./scripts/loadup-init.sh && \
    ./scripts/loadup-mid-from-init.sh && \
    ./scripts/loadup-lisp-from-mid.sh && \
    ./scripts/loadup-full-from-lisp.sh
```

**Comment by masinter** [comment]
the timestamp checking was moved to the individual step, so it's even clearer.
marked as 'wontfix'
