### ISSUE TITLE
SYSEDIT should  (or should not) set DFNFLG to PROP

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#441]
I think the fact that it is NIL is why it has been unsafe to edit system code

**Comment by masinter** [comment]
The editors have some kind of heuristic about which functions are unsafe to redefine. The need some update.  I've been running with DFNFLG=PROP and it's a pain when I'm *not* editing system code. Of course if you'e "cross-compiling" for changed records you don't want this, but for other code a DFNFLG=COMPILE might mean "always compile on editor exit" (exit with control-C instead of control-X

**Comment by masinter** [comment]
The code in  UNSAFE.TO.MODIFY on file MACHINEINDEPENENT just checks a list called UNSAFE.TO.MODIFY.FNS which has a list of functions of questionable vintage. it's used by TRACE, ADVISE, BREAL and FNS.PUTDEF but not DEFUN?

Updating it to contain the functions that can't run interpreted... in the interpreter itself? Maybe run with a trace of function calls through just typing in a define and an undo?? Warn that things in the "SI" package or that start with "\".

Now it should be possible to SAVEVM and continue, and ask the question again

I'll try updating the checks

**Comment by nbriggs** [comment]
Watch out for references  to packages that could happen before the package system exists. Maiko already had to cope with that issue during INIT

**Comment by rmkaplan** [comment]
This needs more work, it has gotten very tedious.

  It now asks the redefine question (hanging in the far-away prompt window) every time I edit the function, even though I have already allowed it to be redefined, and it is now an expr.  If I have said "no", then it should notify me the next time that it isn't going to redefine, I need to do that manually (UNSAVEDEF) if I really want it to happen.

**Comment by rmkaplan** [comment]
Also DEFINQ((\XXX NIL NIL)) says that \XXX may be unsafe to redefine.  But it isn't defined yet.

One reasonable convention:  It should only ask if an expr would replace a compiled definition.  Otherwise, nothing bad can happen that hasn't already happened.

**Comment by rmkaplan** [comment]
I am backing out of this, in my own work environment.  It tends to scramble things.

The question/answer behavior is confusing, and there is no good answer.  If you say yes, you get the redefine you don't want.  If you say no, you get an error.

The question should be:  "It may be unsafe to redefine.  Do you want to do it anyway?"  Y/N

It should only ask when the Y answer would replace a potentially unsafe compiled function with an expr.

And should come up in the prompt window attached to the edit window not the global prompt window.  (Generally ASKUSER should be redefined in that way, not default to the global prompt.)

**Comment by masinter** [comment]
i think checking ccodep of \ functions makes sense. I agree that the prompt doesn't have an obvious good response.

**Comment by rmkaplan** [comment]
As I said, I think it should not repeat the question on a later edit, if the first answer was “No”.  Instead of asking, it should print a message like “X not redefined, use UNSAVEDEF if desired”.

**Comment by masinter** [comment]
The current setup works for newcomers and works for anyone who can override it in their init.
Based on that (opinion) I'll close this, but reopen or new issue if there's an improvement that will work for everyone.
