### ISSUE TITLE
Illegal stack arg: 2 while browsing stack

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#469]
While looking into #55 I got an error under  INSPECTW.CREATE

![image](https://user-images.githubusercontent.com/1116587/132955822-7297e2b5-dbbe-4d2e-bda2-a656e912b533.png)

In STKARGNAME
Illegal stack arg 2
trying to inspect the LET frame

Easy way to reproduce:
```
(LET(X)(HELP))
```
middle mouse in the titlebar of the HELP window and select BT!
Left-click on the 'LET' frame

you will get the error under

**Comment by nbriggs** [comment]
whoever called `STKARGNAME` is likely confused about how many arguments there are -- it's passing in (in my case) `#<StackP 152,12760/LET>` asking for arg N=2, but the LET only has one argument.   This problem occurs in a lisp.venuesysout as well as a lisp.sysout.

**Comment by nbriggs** [comment]
`(STKNARGS stack)` of the stack says 1, `(STKNARGS stack T)` says 6 (includes PVars) -- so it's adding in 5 from
```
 (fetch (FX FNHEADER NLOCALS) of FRAME)
```
The (FX FNHEADER) looks like
```
  0:    36 stkmin
  2:     1 na
  4:     2 pv
  6:    28 startpc
  8:  3000 byteswapped: NIL argtype: 3
  A:   8D9 frame name: LET
  C:     0 ntsize
  E:   500 nlocals: 5 fvaroffset: 0
Local args: 
 18:   0  0  0 4D   20:  IVAR 0: U
 1C:   0  0  0  0   24: 

----
 28:         6A               '0
 29:         40               IVAR      U
 2A:          1               CAR
 2B:         11 32  4         BIND       [pvar0] [pvar1]; [pvar2] [pvar3] [pvar4]
```
Does this all look reasonable to you?  What should it be doing for the names of the PVars?

**Comment by masinter** [comment]
the names were left anonymous (I think I saw something about trying to reduce the number of atoms used -- before going to 4-byte atoms). So the names it uses are "local variable N"
which is fine.
