### ISSUE TITLE
Remove the variable EXPORTFILES?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#470]
This variable is set in FILESETS, but is not referenced anywhere else in sources/, other than a comment in PRETTY that says it has to do an IMPORT of FILEPKG because FILEPKG is not on EXPORTFILES.

The MAKEINIT and loadup is myserious enough without a red-herring like this.  Is there any reason not to remove it from FILESETS, and remove the IMPORT from PRETTY?

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/132960966-bd01f593-25dd-47a5-bb2d-f7b9c085b43a.png)

**Comment by rmkaplan** [comment]
Ahh, over in internals/, where it is used to drive the gather export.

One question:  is it necessary now to have an explicit list of files to scan, as opposed to just scanning everything in SYSFILES?

Second question:  If it is, then I think the EXPORTS filepkg command should be fixed to cause an error if it is exporting to a file that is not already on EXPORTFILES.  The function \DUMPEXPORTS in FILEPKG seems to be the place for that test.

The trap, which I have run into, is putting in an export and then not knowing why it isn’t being respected—you have to go to a relatively obscure file (FILESETS) and do an update.

**Comment by masinter** [comment]
wouldn't it be better to have every file LOADCOMP the other files it needs to have loaded rather than EXPORTS.ALL?

If we're ever going to get a "compile everything" going these "optimizations" are a drag.

**Comment by rmkaplan** [comment]
I wonder whether all the EXPORT commands are under LOADCOMP’s, or whether we would have to gurantee that?

But there are lots of very primitive things that are broadly used but are spread around, each file might have to have a long list.  And, if something moved from one file to another, all the files that had loadcomped the original would have to be checked and updated.

Export had the property, which I think we should preserve, that it doesn’t rely on specifying and maintaining the pairwise dependencies. But it wasn’t clear to me that there is a shadow variable EXPORTFILES that this relied on.  Hence the proposal to get rid of that (scan everything—I assumed that’s what it did) or guarantee that it is always consistent with (or at least a superset of) actual export declarations.

**Comment by masinter** [comment]
I'm not sure what "everything" is. Does it include LLETHER? PRESS?
Files on LispUsers or Library? 

I like the idea of (maybe named, not numbered) filesets, and going back to using hem to control the loadup(s).

In the meanwhile, add a EVAL@COMPILE DONTCOPY (FILES (LOADCOMP) FILEPKG) and change the comment -- and avoid moving things around unnecessarily.

**Comment by rmkaplan** [comment]
FILEPKG is just a symptom of the fact that exports are not systematically managed, fixing that does not fix the problem that I'm worried about:  If you export a new declaration or macro to a file that was not previously on EXPORTFILES, then you haven't really exported that declaration or macro.  And you could spend hours/days trying to figure out what's going on if you hadn't read the (nonexistent?) documentation about the fact that EXPORTFILES on FILESETS has to be updated whenever a exports are added to a file not previously  included on that magical list.

I think you should be warned that you are falling into such a pit.  So here's a proposal: 

Along with the definition of the EXPORT filepkgcom on FILEPKG, add a variable EXPORTFILESVAR (initial value NIL) that may contain the name of the variable that will hold the files that your GATHEREXPORTS should consult.  Make \DUMPEXPORTS cause an informative error if that variable is not NIL and the current file is not on (EVAL EXPORTFILESVAR) when the file is dumped. Then fix it so that SYSEDIT (loaded when you want to work on system files) sets that variable to EXPORTFILES.

**Comment by masinter** [comment]
The proposed fixes seem messier than leaving things as is, and putting it in the Medley Developers Guide (which we need to write).
There's a variable EXPORTFILES in FILESETS. MAKE-EXPORTS-ALL (in medley/internal, called by loadup-aux.sh) uses that to control what goes in it. These files identify which macros and RECORD declarations are used by "low-level" code and not by ordinary Interlisp users. (There aren't very many of those but we should support them because that's part of the Interlisp Experience).

So I'd like to resolve this by marking this 'wontfix'. Reopen if you disagree

**Comment by nbriggs** [comment]
If it's "won't fix" then it should be "close as not planned" rather than "closed completed".

**Comment by masinter** [comment]
I didn't know that was an option
Certainly, it's an area for improvement, but not in a piecemeal fashion.

**Comment by nbriggs** [comment]
Under the ▼ on the Close button

![CloseNotPlanned](https://user-images.githubusercontent.com/8138841/181082223-c68edcb3-d0b5-4ab7-902c-73dad96b1001.png)
