### ISSUE TITLE
TEDIT buttonevent and scroll functions don't systematically call TOTOPW

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#492]
Suppose you have a Tedit window T that overlaps another window W, with the caret blinking in the non overlapping region of T.  If you click in W, it comes to the top.  If you then click in T, it stays underneath.  You have to click again to bring it on top. The problem seems to be that there are branches of the tedit buttoneventfn that don't call TOTOPW.

The Tedit scrollfn also doesn't call TOTOPW.  That may be the reason for the odd behavior of WHEELSCROLL (reported in #208) wherein if 2 TEDIT window overlap and you scroll in what appears to be the top one, sometimes the bottom one also scrolls (or scrolls instead).

**Comment by nbriggs** [comment]
I have a feeling that this was intentional so that you could move the input focus without bringing the window to top.  It makes for fewer windows jumping up and down when you're shift-selecting between two TEdit windows.  It might be in the TEdit documentation.

**Comment by rmkaplan** [comment]
But then, TEDIT is the only kind of window, as far as I know, that behaves in this way.  If you shift-select from an SEDIT window, for example, the window pops on top.

And here’s what the Tedit manual says (Activating a Tedit window in Getting Started):

A TEdit window is active, i.e., ready to accept typein when a blinking caret appears in the window. To put the caret into a TEdit window, move the cursor into the window and press any button. If the TEdit window is buried beneath any other windows when you activate it, it will "pop to the top."

**Comment by nbriggs** [comment]
Must be a bug then.

**Comment by masinter** [comment]
I saw some code I don't remember where which closed TEdit processes when the window was shrunk. So this is indicative of code that was patched. Perhaps in LiapUaers or Rooms?

A Interlisp D window can't update unless it is on top. It sounds like there might be some caching of screen windows. Is it the same in full.venuesysout?

**Comment by rmkaplan** [comment]
I poked around and found that TEDIT.DEACTIVATE.WINDOW was not treating readonly windows in the same way as editfinished windows, and therefore wasn’t stripping the process and all of the internals on the close.  I fixed that, that seems to have cured the opening of closed windows, either by wheel scroll or just by typing.

But it is still the case that 2 readonly windows fight with each other.  It may be that they are fighting for the interrupt characters, and that’s causing them to flip-flop.

If you do SEE from the file browser twice, to get 2 overlapping windows, then here is what I think I have observed:  If you click on one (presumably to give it the TTY for meta-F etc., even though it is readonly for editing), and wheelscroll over the overlap, everything is fine.

If you then go over to the exposed region of the bottom window (outside of the overlap) and only rotate the wheel or swipe your fingers (no clicking to move it to the top, give it the tty etc.), the window that was on the bottom comes to the top (as it should), but the window underneath flashes up and down very quickly, as you scroll.

If you then move the mouse in the top-window to the overlap region and scroll, then both windows start to move.

**Comment by masinter** [comment]
> So, what looks like the top window (for scrolling) and in fact is the top window (via TOTOPW) does not actually have the keyboard. 
"the keyboard" doesn't belong to a window, it's assigned to a process. The process gets interrupts and also keyboard input (while other processes wait until they get the keyboard AND there is input.

**Comment by rmkaplan** [comment]
I think TEdit and/or wheelscroll are now behaving reasonably--it comes to the top when you it has or is given the keyboard.

If the 2 windows overlap and the caret is blinking in the overlap region in one of them, that window is on top.  Scrolling with the mouse over any part of that window scrolls as expected.  If you move the mouse over the non-overlap part of the lower window and wheelscroll (or scroll bar), the window comes to the top and scrolls.  But scrolling doesn't give it the TTY, so the caret stays in the other window, and that window comes back to the top when the scrolling screen update is complete.

I'm going to close this.
