### ISSUE TITLE
common lisp?

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#5]
Bob said he last worked on common lisp and had a marked-up copy of CLTL2 at his office with all the problems.

So if we can, fixing 'up common lisp support is a good long-term goal, but just knowing what we have will be helpful.

**Comment by Anzus** [comment]
If Bob doesn't have it anymore I have an on-disk copy of a tape he sent me of his work to make Medley CLTL2 compliant. A big issue was the CL package nickname changed from LISP to COMMON-LISP.

**Comment by Anzus** [comment]
Oh, also this predates ANSI. So one question is whether we release CLTL1, CLTL2, or ANSI...

**Comment by masinter** [comment]
We release what we have. I’m just thinking about release notes

**Comment by Kirtai** [comment]
Re #47, I found more information int the Medley release notes (not in any manual I could find) and have added it here so it doesn't get lost.

CL is CLtL1.
The CL interactor uses the LISP readtable and the USER package.
The XCL interactor uses the XCL readtable and the XCL-USER package.
The LISP readtable is pure CLtL1
For XCL: 

> "This readtable is the same as LISP, except that the characters with ASCII codes 1 thru 26 have white-space (SEPRCHAR) syntax . This readtable is intended for use in File Manager files, so that font information can be encoded on the file"

They both accept commands like "undo" which doesn't quite match with the above.

**Comment by masinter** [comment]
What we have is called "Medley 3.5". we're not sure what changes were made while Venue was active (prior to 2009).
The Envos files we have are from 1993 and contains releases for Medley 1.0 and Medly 2.0 (and maybe a few in between).
Medley 3.5 wasn't officially 'released', though, so that's why we don't know what we have exactly and the "restore" part of the project is important. 1993-2009 seems like a long time, and a long time ago.

Can we build a Medley 3.5 Release with proper release notes?

**Comment by masinter** [comment]
> If Bob doesn't have it anymore I have an on-disk copy of a tape he sent me of his work to make Medley CLTL2 compliant. A big issue was the CL package nickname changed from LISP to COMMON-LISP.

That would be quite useful; if we can link up the dates on his notes to the dates of the common lisp implementation files.
