### ISSUE TITLE
Creating docker images on every push to master is unnecessarily frequent - should be on every release

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#515]
Currently docker images are created on every push to master.  Even before the exclusion of loadups from the github repo (see my previous bug report #514), this was a bit problematic since in most cases the source code and the loadup sysouts were out of sync (since new loadups were not necessarily being done on every push).

One solution is to run the loadup scripts as part of the docker build.  But it seems unnecessary to create a new Docker image for every push to master.  Why not just make docker image creation part of the release process - and hence get a new docker image based on the synced runtime and loadup tars that come with a release?

**Comment by masinter** [comment]
Now it is set up to only build docker on manual trigger.
that seems to solve the problem in the issue.
