### ISSUE TITLE
Tags on Docker Hub not very useful - would help a lot to add date-based tags

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#516]
The tags on the Medley docker images on Docker Hub are not very useful (they are the shortref to the corresponding github commit).  In particular, they contain no date information and DockerHub is terrible at showing you the dates of images (e.g., using "last month" for anything created more than 30 days and less than 60 days ago).

Our dockerhub repo would be a lot easier to use if we included a date in the tags.  Probably would make most sense to do a combo tag with date and short-ref since there are cases where you might indeed want to correlate the image with the github commit.  The date should come first in any combined tag to allow easy sorting by date.  

Could also multi-tag each image with the date and well as the short-ref.

**Comment by masinter** [comment]
The docker/releases process might be a little backward. We should build the releases first (and figure out what other release targets we need).    Releases have names that default to medley- or maiko- followed by the date in YYMMDD.
Releases have targets, one of wich is "Docker", one is  "GitHub User" and possibly Native Mac.

Docker releases should contain the release names of the medley and maiko's they contain.

**Comment by masinter** [comment]
I don't see an issue left here.
