### ISSUE TITLE
Storage overflow with ShellCommand?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#528]
In a first attempt to deal with git, I added to my WHO-LINE an entry for the Branch.  It updates the branch by repeatedly evaluating
      (CAR (GIT-COMMAND "git rev-parse --abbrev-ref HEAD"))
where GIT-COMMAND is defined as
(LAMBDA (CMD)
       (CL:WITH-OPEN-FILE (STREAM "{NODIRCORE}shell-dribble.txt" :DIRECTION :IO)
              (ShellCommand (CONCAT "cd " (GIT-REPO)  ";" CMD)   STREAM)
              (SETFILEPTR STREAM 0)
              (UNTIL (EOFP STREAM)  COLLECT (CL:READ-LINE STREAM :EOF-ERROR-P NIL :EOF-VALUE NIL))))
GIT-REPO is defined as
      (CONCAT "/" (CL:SUBSTITUTE #\/ #\> (MKSTRING (FILENAMEFIELD MEDLEYDIR 'DIRECTORY))))
and ShellCommand is defined in UNIXPRINT as
(CL:DEFUN ShellCommand (Cmd &OPTIONAL (Output T))
       (CL:WITH-OPEN-STREAM (s (CREATE-PROCESS-STREAM Cmd))
              (CL:TAGBODY (SETFILEINFO s 'ENDOFSTREAMOP #'(CL:LAMBDA (s) (GO OUT)))
                     (CL:LOOP (PRINTCCODE (READCCODE s) Output))
                     OUT))
       NIL)

This systematically eats up storage, until it runs out.  I presume that NODIRCORE streams get collected (that was the whole point of NODIRCORE).  Is the culprit in ShellCommand?  Should it be reusing the process, perhaps as a global resource?  Or something to do with the CL stuff?

**Comment by nbriggs** [comment]
I'm not sure where your storage is going, but in poking around I found that attempting to do
```
(PRINTOUT (CREATE-SHELL-STREAM) "date" T)
```
results in `\FILEOUTCHARFN is an undefined function` -- so there are things broken somewhere near the bottom of all this.

**Comment by rmkaplan** [comment]
Hmm, I don’t get that error for this particular function.  But I will recompile any of the LCOMS that grep shows as still referencing \FILEOUTCHARFN.  Those remaining calls don’t show up in the source files or in the ms database, because they are implicit default constants in the stream create.

Note:  there is a file lispusers/STREAMDECLS that only has a version of the stream declaration from 1987.  I assume that should be deleted.

**Comment by nbriggs** [comment]
sources/BSP.LCOM
sources/COREIO.LCOM
sources/COURIER.LCOM
sources/LEAF.LCOM
sources/LOCALFILE.LCOM
sources/MOD44IO.LCOM
sources/NSFILING.LCOM
sources/SPP.LCOM
library/CHARDEVICE.LCOM
library/UNIXCOMM.LCOM
lispusers/DATE
lispusers/PLAINTEXTSTREAM
lispusers/STREAMDECLS

**Comment by rmkaplan** [comment]
There is also a lispusers/DATE from 87 that has its own version of the STREAM and FONTCLASS declarations, which are inconsistent with the current ones (so, can’t load).  I will try to use Tedit to edit out the declarations and remake.  I don’t see a doc file for it, seems maybe to be producing a date imageobj.

**Comment by masinter** [comment]
You have to be careful about file name case when translating from Lisp file names to unix file names and running on a case sensitive file system.

And spaces in file names too

**Comment by rmkaplan** [comment]
Some of these need records that are not in EXPORTS.ALL.  SYSQUEUE and some PUP stuff?  Are we missing some exports?

**Comment by nbriggs** [comment]
SYSQUEUE is exported from LLETHER -- why would that not be in EXPORTS.ALL ?

**Comment by rmkaplan** [comment]
Because LLETHER is not on EXPORTFILES in FILESETS ? That’s what drives MAKE-EXPORTS.ALL.

Safe to add it to the list?

**Comment by nbriggs** [comment]
It used to be there --
```
       (FILESETS MODARITH LLPARAMS LLCODE AERROR AOFD APRINT ATERM LLARRAYELT LLDATATYPE LLNEW
              LLBASIC LLCHAR LLSTK PMAP LLGC ATBL FILEIO LLARITH LLFLOAT FONT LLKEY LLDISPLAY
              ADISPLAY AINTERRUPT PUP RENAMEMACROS HLDISPLAY WINDOW MACROAUX ADDARITH LLFAULT LLTIMER
              LLETHER IMAGEIO PROC LLREAD PASSWORDS INTERPRESS HARDCOPY CMLARRAY LLSUBRS)
```
and now we have
```
       (MODARITH LLPARAMS LLCODE AERROR AOFD APRINT ATERM LLARRAYELT LLDATATYPE LLNEW LLBASIC LLCHAR
              LLSTK PMAP LLGC ATBL FILEIO EXTERNALFORMAT LLARITH LLFLOAT FONT LLKEY LLDISPLAY
              ADISPLAY AINTERRUPT RENAMEMACROS HLDISPLAY WINDOW MACROAUX ADDARITH LLFAULT LLTIMER
              IMAGEIO PROC XCCS LLREAD PASSWORDS INTERPRESS HARDCOPY CMLARRAY LLSUBRS))
```

These files seem to have `(EXPORT (...` expressions in them (alphabetical order):

ADDARITH ADISPLAY AERROR AINTERRUPT AOFD APRINT ATBL ATERM CMLARRAY
DTDECLARE EXTERNALFORMAT FILEIO FILEPKG FONT HARDCOPY
HLDISPLAY IMAGEIO INTERPRESS JAPANESE LLARITH LLARRAYELT LLBASIC
LLCHAR LLCODE LLDATATYPE LLDISPLAY LLETHER LLFAULT LLFLOAT LLGC LLKEY
LLNEW LLPARAMS LLSTK LLSUBRS LLTIMER MACROAUX MODARITH
PASSWORDS PMAP PROC PUP RENAMEMACROS UFS WINDOW XCCS

So things that seem to have exports that aren't included in the current EXPORTFILES list and should be checked are:

DTDECLARE FILEPKG JAPANESE LLETHER PUP UFS

while LLREAD used to have exports and now appears not to.

**Comment by rmkaplan** [comment]
(Any reason not to alphabetize EXPORTFILES?  Does the order matter?)

**Comment by nbriggs** [comment]
I don't know whether there are any dependencies between the exports... I guess we'd find out if EXPORTS.ALL stopped loading!

**Comment by masinter** [comment]
the storage full problem doesn't happen any more
(RPTQ 100 (PRINTOUT (CREATE-SHELL-STREAM) "date" T)) doesn't allocate much.

However trying for 1000 I get a warning (on stdout)
![image](https://user-images.githubusercontent.com/1116587/236380794-bdcdb2c5-9b2f-4108-80f4-6d93792927ef.png)
and then the system freezes

it SHOULD fail with a Lisp error.

Closing this issue, will open one for the hang.
