### ISSUE TITLE
spurious "unbound variable" error when variable is bound to NOBIND (e.g., in MAPATOMS with interpreted fn)

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#55]
According to the IRM, MAPATOMS takes a function of one argument which is called
with each litatom in the system -- so
```
(LET ((FNCOUNT 0)) (MAPATOMS (FUNCTION
     (LAMBDA (FOO) (IF (GETD FOO) THEN (SETQ FNCOUNT (ADD1 FNCOUNT)))))) FNCOUNT)
```
should return the number of atoms with a definition.   Instead it fails with
```
FOO is an unbound variable
```
If you don't reference the lambda parameter it does indeed call the function 28000+ times successfully.

**Comment by masinter** [comment]
\INTERPRETER1 in LLINTERP  changes the stack frame of its caller to look like it's bound the "special" variable FOO, But the value is the symbol NOBIND which is 1 (?!). "There's a comment Note: area is initialize to NIL's (zero), so end of nametable already has its zeroes.d"

**Comment by nbriggs** [comment]
It's correct that NIL and NOBIND are the first two atoms at indexes 0 and 1 (while T is 0114Q), that's hardwired into the code.

**Comment by masinter** [comment]
I don't remember the convention that unbound atoms are bound to NOBIND? But this is' Broken As Designed because NOBIND is an atom and so FOO is bound to NOBIND.  (LET ((FOO 'NOBIND)) (LIST FOO)) gives the same error (Interlisp interpreter only -- the Common Lisp interpreter uses lexical binding and compiled code doesn't need to look up for the bindings on the stack

**Comment by nbriggs** [comment]
Ah, obvious when you point it out.  If you compile the (INTERLISP) function incorporating the above code it works fine, it's just the interpreted version that fails.   Thanks.

**Comment by masinter** [comment]
this is a fundamental of the Interlisp interpreter

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/132962243-0940a624-f468-43e4-ab0c-0d71baa094b2.png)
Implementation doesn't match documentation.

**Comment by masinter** [comment]
while it's a mystery why this choice was made....
