### ISSUE TITLE
Proposal to reuse regions for windows of a given type

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#552]
In our current set up there is no conventional way to prespecify the default region to be used or reused for a window of a given type.  Typically, you have to produce a ghost region every time.

The filebrowser is an obvious example: if you do FB *, you have drag out a region.  If you close the window and do FB * again, you have to drag out another region.  Similarly for SEE and EDIT windows from the filebrowser, and for the Tedit windows that my little lispusers package uses for command-line scrollable  PF and SEE.  All very clunky.

So here is a proposal:  introduce a WINDOWTYPE property on windows.  When you open a window with a specified type and don't provide an explicit region, pick a previously used but currently unused region for windows of that type, asking for a new region only if all previous windows are currently in use.  Closing a window of a given type will mark its region as available.

This can be done by a simple extension to CREATEW:  If the REGION argument is an atom X other than NIL (or if WINDOWTYPE X is on the PROPS list), then assume that X is a type specification and look it up in a global TYPED-WINDOWS-REGIONS list.  Then extend CLOSEW so that the region for a window with the WINDOWTYPE property is put back on the list under its type when the window is closed.  (Maybe with a submenu on Close that closes all windows of that window's type--clear out all the file browsers or SEE windows with one click)

A user's INIT could initialize TYPED-WINDOWS-REGIONS to a few preferred regions for built-in types, so that typically filebrowser, PF, etc. windows start out in canonical positions without doing the ghost region thing, until a region is needed that is not currently available for that type. The user could turn this behavior on and off for particular types (like FILEBROWSER) by putting a kind of different entry on the regions list.

So:  a conservative extension of CREATEW and CLOSEW.  Comments?

**Comment by masinter** [comment]
The places where modernize re-uses previous regions is pretty annoying when it's wrong.
Which is quite often, in my usage pattern. And the prompts in PROMPTWINDOW are often wrong.
Modern applications don't ask you to draw out a region: they guess and leave it up to you to adjust if the guess is wrong.   We could have a default guess width and height depending not on history but for the case in hand (TEdit SEdit, etc.), and choose a corner lower left position depending on where there is room. (leave room for scroll bars). 
Then FB could advertise its "shrink to fit" to start with. 
If there's no room on the screen, offer to cascade, or shrink those not active.

**Comment by rmkaplan** [comment]
I don’t think Modernize does anything special with respect to regions, other than allowing the left button to move and reshape when clicked in various places.  

Various programs have their own strategies for prompting for new regions or reusing old ones, all a hodge-podge.  Sedit is particularly idiosyncratic, tlispusers/TILED-SEDIT seems to be an early attempt at dealing with this.

In the current epoch I tried to provide some general underlying tools and conventions for attacking these issues, in lispusers/REGIONMANAGER.  It defines notions of typed regions (e.g. Tedit, FB…), relative regions, and constellations of regions (which are used to connect the prc-compare windows).

My hope was that this would be the basis for less noxious behavior, but at that time I didn’t take the risk of going into the various prominent applications to make them aware of this (e.g. to have the file browser pass the region-type atom FILEBROWSER instead of NIL when it goes to get a window-region.  If that is done, then its initial default regions could be set in advance, and new regions would be typed and reusable.

It would be even better to do more of this automatically, as you suggest.  Sedit could do a reasonable estimate of the region-size based on the size of the structure, Tedit could at least look at the margin-width, FB could look at the longest string in the filename column, etc.  And then maybe a search for empty space, given the estimated region size.

**Comment by masinter** [comment]
this is an area for experimentation. We need to add some abstractions.
the main impediment to adding more window management (auto-tiling, for example) is that too many windows aren't resizable without loss. And, in turn, that is mainly the fault of the exec windows not having a repaintfn. If we could save the tty T output for an event, we could use that to build tiling window manager.

it ins't a typescript it's better. The typescript could be recovered by writing to a dribble file and using that ...

=> discussion
