### ISSUE TITLE
DELFILE should work on directories as well as files

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#569]
Original report from @rmkaplan -- there's apparently no way to delete an empty directory from within Medley.

The only approach is via `(DELFILE ...)` and it gets an error if you try to delete a name on the {unix} device that is an empty directory instead of a file.  On a {dsk} device, it just returns NIL.

**Comment by masinter** [comment]
I'm not sure about this change. I think this is a flaw in Git and not in Lisp in this particular use case. What did NSFILLING or FTP devices do?

**Comment by rmkaplan** [comment]
This use case provoked it, but it has always been a problem

**Comment by masinter** [comment]
always for DSK? For which devices?

**Comment by rmkaplan** [comment]
I only remember it for DSK, other devices are a long time ago.

**Comment by nbriggs** [comment]
I thought, on an IFS, only the top level directory actually existed as an object and all the subdirectories only existed by virtue of being mentioned in a file name, so you couldn't have empty subdirectories.

I'm only making this change for the {unix} host -- because for other hosts it checks whether the name presented is recognized as a "file" before passing it to the DELETEFILE FDEVop.  There is no DELETEDIRECTORY FDEVop (and adding one would complicate a bunch of things, I think)

**Comment by rmkaplan** [comment]
On a Unix system {DSK} and {UNIX} point at the same underlying file system.  So, is the problem for DSK simply that the FDEV interface isn't set up for this extension?  Or is it that DSK can point to other underlying file systems on other architectures?  What would get complicated if we started by adding a DELETEDIRECTORY FDEV field and op, and then incrementally implemented it for the various devices?

BTW, rmdir doesn't always immediately work on what looks like an empty directory on the Mac--the .DS-Store file has to be explicitly deleted first, if it exists.

**Comment by nbriggs** [comment]
{DSK} and {UNIX} go through different code when they get to Maiko because {DSK} manages versions and case-independence and does a lot of internal bookkeeping which prunes out directories, so they never get as far as the "deletefile" method.  The {UNIX} code just passes the name straight down.

**Comment by nbriggs** [comment]
NSFILING allows one to delete a directory (only if it is empty) with the DELETE operation just as it would a file.  TCP FTP separates "delete file" and "delete directory".  The Alto FTP protocol doesn't appear to have a "delete directory" operation -- only "delete file".  Model44 disk file systems don't have subdirectories.  There's a NODIRECTORIES flag in the FDEV, which is set to T or NIL in various cases, but as far as I can see is never referenced!

**Comment by rmkaplan** [comment]
I see that this now works for {UNIX}..../foo/ directories, if foo is empty, thanks.

In terms of DSK, would it help to get uniform behavior by doing more work on the Lisp side, e.g. figuring out what the corresponding {UNIX} name of the directory is, and passing that name down?

**Comment by nbriggs** [comment]
I believe it may cause trouble in the DSK code if you were to sneak behind its back and delete things through the UNIX device that DSK is maintaining cached information about.

**Comment by rmkaplan** [comment]
So, does this cause a problem?  Basically, changing host DSK to UNIX when an empty DSK directory won’t delete, and then deleting it.

(DIRECTORYNAME T)
{dsk}<Users>kaplan>lisp>

(SETQ FOO (OPENSTREAM ‘FIE>FOO ‘OUTPUT ’NEW))
  (output stream on on {DSK}…FIE>FOO.;1)  
  This creates the subdirectory FIE>

(CLOSEF FOO)
  {DSK}<Users>kaplan>lisp>FIE>FOO.;1

DIR FIE>
  FOO.;1

(DELFILE ‘FIE>FOO)
{DSK}<Users/kaplan/lisp/FIE>FOO.;1   

DIR FIE>
    (FIE now empty)

(SETQ FIE (DIRECTORYNAME ‘FIE>))  (Grab the full path)
{DSK}<Users>kaplan>lisp>FIE>

(DELFILE FIE)  
NIL   (nothing happens)

(DELFILE (PACKFILENAME ‘HOST ‘UNIX ‘BODY FIE))
{UNIX}<Users>kaplan>lisp>FIE>.

DIR FIE>
(error message in promptwindow:  Can’t emumerate …FIE> because no such directory)

**Comment by nbriggs** [comment]
It's hard to know whether it caused trouble -- it might be OK, or it might have unpredictable behavior, later, if you tried to recreate that file, or another file in the same directory, and it might depend on exactly the sequence of create/delete/enumerate/create operations... the code isn't written to either prevent it or handle it if it should happen unbeknownst, so I would be *really* hesitant to encode into Lisp code behavior that depends on that.

If we want to be able to delete directories on the maiko DSK device we should work out how to add that to the maiko code that implements DSK and ensure that the behavior is well-defined for DSK devices that support directories as objects and also comprehends those where it's just a byproduct of the naming syntax of files.
