### ISSUE TITLE
remember preferred case for MAKEFILE'd files written with XCL or other case insensitive readtable

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#579]
i wonder if you're using XCL or other case insensitive readtable to remember (as with SEDIT) that the file "prefers" to be shown in lower case.

@nbriggs complained that the git diffs showed these as changing (COMPARESOURCES would say they were the same)

**Comment by masinter** [comment]
i'm not sure what this was about; quite possibly a misunderstanding?
Anyway, I will close this -- reopen if you can elaborate a problem statement.

**Comment by rmkaplan** [comment]
Probably just another instance where the github file-compare doesn't understand Medley conventions, sees mere typographical and formatting differences as substantive changes.  Which is why GITFNS.
