### ISSUE TITLE
ShellCommand("git remote update origin") can take a really long time

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#594]
(On Mac)

Several minutes in some cases, always hung up in UNIX-GET-NEXT-BUFFER.  Whereas simply entering that command into a separate terminal window while the ShellCommand is running is instantaneous.

**Comment by nbriggs** [comment]
Not sure what's going on -- I haven't been able to reproduce it.  I'll look at the maiko side of things.

**Comment by rmkaplan** [comment]
It’s intermittent.  Sometimes hangs for 3 or 4 minutes, other times just blitzes through

**Comment by rmkaplan** [comment]
I haven't seen this delay in quite awhile.  I'm going to close this.
