### ISSUE TITLE
Preserve file version numbers associated with files

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#61]
@nbriggs 
> [medley repo] doesn't have the version numbers associated with files which are unversioned.

**Comment by masinter** [comment]
I think the problem was also in https://github.com/Interlisp/medley/issues/49#issuecomment-715566486 
maybe Ron did a trim?
find . -type f -iname 'font.~*' -exec ls -l {} \;
-rwx------+ 1 Larry None 182451 Jan 30  2000 ./history/20160626-lispcore/sources/FONT.~1~
-rwx------+ 1 Larry None 182592 Jan 30  2000 ./history/20160626-lispcore/sources/FONT.~2~
-rwx------+ 1 Larry None 190325 Jan 22  2000 ./history/20160626-lispcore/sources/FONT.~3~
-rwx------+ 1 Larry None 190325 Jan 22  2000 ./history/20160626-lispcore/sources/FONT.~4~
-rwx------+ 1 Larry None 34211 May 31  1993 ./history/20160626-lispcore/sources-2.0/FONT.~1~.gz
-rwx------+ 1 Larry None 34468 Oct 13  1995 ./history/20160626-lispcore/sources-2.0/FONT.~2~.gz
-rwx------+ 1 Larry None 190325 Oct 29 19:33 ./medley/lisp/sources/FONT.~3~
-rwx------+ 1 Larry None 190325 Oct 29 19:33 ./medley/lispcore/sources/FONT.~6~
-rwx------+ 1 Larry None 190325 Jun 28  1999 ./medley.ron/lisp/sources/FONT.~3~
-rwx------+ 1 Larry None 190325 Jun 28  1999 ./medley.ron/lispcore/sources/FONT.~6~
-rwx------+ 1 Larry None 182451 Jan 30  2000 ./old-medleydirs/20160626-lispcore/sources/FONT.~1~
-rwx------+ 1 Larry None 182592 Jan 30  2000 ./old-medleydirs/20160626-lispcore/sources/FONT.~2~
-rwx------+ 1 Larry None 190325 Jan 22  2000 ./old-medleydirs/20160626-lispcore/sources/FONT.~3~
-rwx------+ 1 Larry None 190325 Jan 22  2000 ./old-medleydirs/20160626-lispcore/sources/FONT.~4~
-rwx------+ 1 Larry None 34211 May 31  1993 ./old-medleydirs/20160626-lispcore/sources-2.0/FONT.~1~.gz
-rwx------+ 1 Larry None 34468 Oct 13  1995 ./old-medleydirs/20160626-lispcore/sources-2.0/FONT.~2~.gz
-rwx------+ 1 Larry Unknown+Group 190325 Jun 28  1999 ./old-medleydirs/202009-Interlisp/lisp/sources/FONT.~3~
-rwx------+ 1 Larry Unknown+Group 190325 Jun 28  1999 ./old-medleydirs/202009-Interlisp/lispcore/sources/FONT.~6~
-rwx------+ 1 Larry None 190325 Jun 28  1999 ./old-medleydirs/20200919-lispcore/sources/FONT.~6~
-rwx------+ 1 Larry Unknown+Group 190325 Jun 28  1999 ./old-medleydirs/20200923-Interlisp/lisp/sources/FONT.~3~
-rwx------+ 1 Larry Unknown+Group 190325 Jun 28  1999 ./old-medleydirs/20200923-Interlisp/lispcore/sources/FONT.~6~
-rwx------+ 1 Larry None 190325 Jun 28  1999 ./old-medleydirs/20201007-ron-lispcore/lispcore/sources/FONT.~6~
~/ilisp 62%

**Comment by masinter** [comment]
find . -type f -iname 'font.~*' -exec ls -l {} \;
[font-list.txt](https://github.com/Interlisp/medley/files/5469894/font-list.txt)

**Comment by nbriggs** [comment]
I think if when you paste in things with version numbers you wrap it in triple-backquotes on an otherwise empty line before and after it won't think it's markdown -- like this:
```
sample-file.~123~
```
