### ISSUE TITLE
Should (OPENSTREAM :keyword ...) be allowed?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#616]
Seems odd to specify a filename with a keyword.  Currently, (OPENSTREAM :KEYWORD 'OUTPUT 'NEW) makes a file KEYWORD (without the colon).

Seems odd, I think it should be an error

**Comment by masinter** [comment]
The behavior of streams is dictated to some degree by Common Lisp -- there isn't a separate file system between Common Lisp and Interlisp.    That said, Interlisp (and thus Medley Xerox Common Lisp) extend Common Lisp by allowing values that were defined as "is an error".
Among other places, Interlisp allows (and sometimes returns) symbols (in any package) in addition to strings and pathnames.

I used a keyword as a file name in one of the loadup files since I wasn't sure of the *package* value.

**Comment by masinter** [comment]
Not sure I said that right: Common Lisp doesn't allow a symbol to be passed to "open" at all. Most will take strings as well as PATHNAME instances. Interlisp clogs up non-GCd symbols by returning and using file name symbols which are interned into IL package.   I think we considered changing IL to not traffic in symbols and decided it had too many consequences.

**Comment by rmkaplan** [comment]
I get the point about package-names not wanting to be part of file names, and the fact that users working in a package don’t see that the package is implicitly attached to every simple-appearing atom.

But keywords seem to me to be different—they are really an attempt to work around the excesses of the package system, and in that sense they are really ways of doing internal signalling.  They are in a certain sense outside of the normal space of litatoms—they evaluate to themselves and they can’t take on new values.  They have to be specified with the colon—can you ever operate inside the keyword package, so that all unpackaged atoms are implicitly keywords?

So it still seems odd that keywords aren’t an exception to the medley extension for litatom filenames.

(I ran into this because it seemed reasonable to use a keyword to pass a signal about the type of a stream that I wanted at a low-level subfunction where all of the intervening functions were set up to pass a stream argument.  Didn’t want to extend all of the intermediate functions with an additional signalling argument, kind of funky to bind a variable and also have it initialized at the top-level.  But there are obviously work-arounds with different degrees of cleanliness.)

**Comment by masinter** [comment]
the logic of extending cl:open to allow symbols as input but disallow keywords so you could use the fact that it was an otherwise disallowed keyword to signal one bit other than the keyword's symbol-name...

I think we should be moving away from using symbols as file names.
