### ISSUE TITLE
Document what browsers and OSes online.interlisp.org works with

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#623]
from @pmcjones 
> On my MacBook Air (macOS Monterey), it seems to work fine in Firefox, but in Chrome and Safari, the screen goes dark, I see a VNC logo at the left, then that disappears and I’m back at the login screen.

If it doesn't work with some browsers?

**Comment by nbriggs** [comment]
✅ Chrome 96.0.4664.93 on MacOS El Capitan 10.11.6
❌Safari 11.1.2 on MacOS El Capitan 10.11.6
✅ Safari on iOS 15.1
✅ Safari 15.1 on macOS Catalina 10.15.7
✅ Safari 15.1 on macOS Big Sur 10.16.1 (11.1?)

**Comment by rmkaplan** [comment]
It fails on my Safari 15.1 (MacOS Monterey)

**Comment by masinter** [comment]
❌Safari 13.1.2 on macOS High Sierra 10.13.6
✅ Chrome 96.0.4664.93 on macOS High Sierra 10.13.6
✅ Edge .Version 96.0.1054.53 on Windows 10 version 21h1

**Comment by rmkaplan** [comment]
✅ Firefox 94.0.2 on macOS Monterey

**Comment by masinter** [comment]
sort by OS / Version / Browser
As a wiki page so people can update it

**Comment by pmcjones** [comment]
✅ Chrome 96.0.4664.110 (Official Build) (64-bit) on Windows 10 Pro Build 19043
✅ Firefox 95.0 (64-bit) on Windows 10 Pro Build 19043
✅ Chromium Version 72.0.3626.121 (Official Build) on Raspbian 9.13 (32-bit) on Raspberry Pi 2

**Comment by masinter** [comment]
so far, all ok except safari 
all safari fail except 15.1
safari 15.1: see list from nick and ron. I'm not sure what the order is for Monterey
will want to retest when @fghalasz updates noVNC in online
