### ISSUE TITLE
What kind of character is an image object?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#631]
Tedit streams can be treated as character sequences with BIN, BOUT, etc.  But an image object can appear in the middle of a character sequence, and the BIN function returns that object instead of the character code that a calling functions might expect.  In particular, this causes an error with the default \INCCODE.

That can be fixed easily by filling out the tedit file device with special versions of inccode, peekccode that don't crash on image objects.  But that begs the question:  what should they return to their callers--READC, RATOM... ?

A consistent no-error but information-losing solution would be to return some specific fixp code from an undefined region of the character space, signifying that here was an image object at a particular place in the sequence but providing no additional information.  Is there anything better to do?

**Comment by nbriggs** [comment]
20 years ago (from the full.venuesysout) READC failed with `{IMAGEOBJ}#147,4300 is not a NUMBER` in that circumstance.   Is there some reason to change that?   Since it has "always" been an error there should be no code that depends on it doing something else.

**Comment by masinter** [comment]
An image object is not a kind of character. There are ordinary streams and TEdit streams: ordinary streams can only have characters while TEdit streams consist of a stream of characters OR image objects.  

"character sequences with BIN, BOUT" seems like it's wrong: BIN and BOUT deal in (8-bit) bytes. \INCCODE deals in character codes.  It seems right that READC gives an error although I'm not sure about "not a number".

**Comment by masinter** [comment]
not sure what the issue is -- is there a problem? 
I will close -- reopen (and convert to Discussion?) if it needs to be.

**Comment by rmkaplan** [comment]
In order for COMPARETEXT (used by prc etc.) to compare TEDIT files containing image objects, I extended (current master) Tedit so that the caller could specify (as the value of an OBJECTBYTE property) a single particular character code for BIN to return in place of any image object.  This hack at least meant that COMPARETEXT doesn't fail, and it can detect whether image objects are not in the same place between two files. But it won't know whether the image objects are the same or not.

Perhaps a less hacky and more useful strategy would be for a property to specify that the bytes of an imageobject's preprint fn should be returned, one after the other, to successive BIN's, reverting to the next character when the preprint string is exhausted.

A sophisticated caller would at least have control.

**Comment by nbriggs** [comment]
Or perhaps it could return a single 16-bit checksum from the result of the preprint fn, or anything else that's related to the actual content of the image object.  Of course that gives you a 1/65536 chance of failing to detect a change, but...

**Comment by rmkaplan** [comment]
Better than mapping them all to the same thing, but if the caller isn't object-aware (i.e. not expecting to see an object as a value from BIN), then probably the preprint characters themselves would be more useful.  The hash would be good for detecting (based on the preprintfn) that the object had changed in the comparison setting, but even in that setting the characters themselves would be more informative.

Also, returning 16 bits that correspond to a real character would be confusing in a different way.
