### ISSUE TITLE
bitrot in man page

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#636]
man DEFAULTFONT

yields

![image](https://user-images.githubusercontent.com/1116587/147172105-370f4899-0fe8-4b46-98c4-425346652bd9.png)

**Comment by masinter** [comment]
presume another instance of #405

**Comment by rmkaplan** [comment]
Just to comment, this won't be fixed in the currently distributed Tedit code--too hard.  It is fixed in the refactored code that I have been developing.
