### ISSUE TITLE
Bug in Unix DIRECTORY enumeration

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#648]
The function DIRECTORY has a DEFAULTVERS argument.  This defaults to *, meaning all versions, but setting it as the empty string "" nominally is supposed to return the highest version (if the file system supports that, which the Unix code seems to do).

In particular, (DIRECTORY "(medleydir)library" NIL NIL "") does the right thing, produces only newest versions of files in the top-level library directory.

But:  if FILING.ENUMERATION.DEPTH is greater than 1, so that the enumeration also includes files in any subdirectories, then the generators for those subdirectories use * instead of "" for their pattern.  The result:  you get all versions for the files in the lafite/ subdirectory.

**Comment by rmkaplan** [comment]
A little bit more:  The problem seems to be that \UFS.NEXTFILEFN rebinds DEFAULTEXT and DEFAULTVERS to *, no matter what they were on the original call to DIRECTORY.  I'm not whether this would be called in the right context if those bindings were removed.  Maybe those defaults have to be included as extra elements in the FILEGROUP?  But then, what about the generations for other file devices?

**Comment by masinter** [comment]
as late as Medley 2.0, FILING.ENUMERATION.DEPTH was only for XNS file servers. This problem seems to have been fixed.
At some point, following the common conventions of Common Lisp implementations (using ** to mean "arbitrary depth" might be considered, but closing this.s
