### ISSUE TITLE
TEDIT:  garbled files and crashing

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#649]
I think TEDIT is the source of unrecoverable crashes, smashing storage.  It does raw pointer accesses for efficiency, and I suspect without proper bounds checking.  That's one issue.

But the other issue is that TEDIT files from time to time show up as garbled, usually with Kanji characters in the middle of otherwise valid text.  You see this in DINFO files, for example, which may be because of historical rot.

But I now also see it in files that I am just creating.

The first question is whether the file itself is garbled, or whether something is wrong now with the reader (perhaps because of the vary minor adjustments for the EOL change, or maybe the way the XCCS runcode is now handled).  With respect to DINFO files, that would mean that the historical files are good.

I thought I would try to answer that first question by reading a bad file into the original loadups/full.venuesysout.  But I couldn't get TEDIT to open the file because it apparently could not find a proper system init file for that sysout, and therefore it apparently cannot create any display fonts.

Any suggestions for that?

**Comment by nbriggs** [comment]
I've tried starting full.venuesysout with ./run-medley loadups/full.venuesysout and it started OK.   I don't remember whether full.venuesysout used the "old" or "new" font directory organization...

**Comment by nbriggs** [comment]
... and I checked doing a `(FONTCREATE 'MODERN 24 'BRR 0 'DISPLAY NIL 0)` that it opened `/Projects/medley/fonts/displayfonts/c0/MODERN24-BRR-C0.DISPLAYFONT` so it got a compatible setting for the `DISPLAYFONTDIRECTORIES`

**Comment by rmkaplan** [comment]
Try creating a font

**Comment by rmkaplan** [comment]
Oh, I see that you did.  What and where is your system greet file?  And your personal init file?  The same ones that load for current sysouts?

**Comment by nbriggs** [comment]
Only the MEDLEYDIR-INIT for the system greet, no personal init file.

**Comment by rmkaplan** [comment]
I decided to look at the bytes in a smashed Tedit file, using a separate text editor and also using a byte editor (0xED).

First observation is that underneath what shows up as garbled chinese characters is actually the intended text. The problem is that there are some FF character set switches before and after the garble display.

For example, one garble began and ended with FF 00 0A.

In another I saw a sequence beginning with FF FF 00 FF EF 21 FF 00 and ending with FF 00

If you take out those sequences, I think the file would look good.

I don’t know what to make of it.

**Comment by rmkaplan** [comment]
Reply from Nick:

A couple of things come to mind — Could it be confused about what the “current” character set is and therefore figure it needs to output a character set change, when in fact it didn’t? Could it be confused about the character set associated with the thing it’s trying to add/replace in the file and likewise think it needs to adjust the current character set?

It might be helpful to see the call stack any time an FF is written to the file for any reason.

**Comment by rmkaplan** [comment]
Reply from Larry:

This looks like it might be a problem with the XCCS runcodes.
If you OUTCHAR(" ") in charset 0 but it thinks the current stream charset isn’t 0, then it might insert the runcodes to switch back ?
I forget how XCCS runcodes work. Where does it keep the charset state of a character stream?

This shouldn't appear in most of our TEdit files? So we could just run with a check to BOUT of FF?
To get a small reproducible case.

**Comment by rmkaplan** [comment]
My further comment:  When I did the external format transform, I worried about getting TEDIT to respect the external format of plain text files (e.g. a UTF8 file from the outside).  I figured that (except for a little work on the EOL change), that TEDIT binary files could operate as they used to, with their own handling of NS conventions.  In other words, I chickened out.

So TEDIT does in fact have code that worries about thin and fat strings, and thin and fat file-based pieces, and it bouts its own characterset changing bytes.  That is probably a mistake, it should just use the generic \OUTCHAR and let the XCCS outchar fn decide what bytes it needs to put out.  The outchar fn changes the charset that the stream knows about, the bouts don't do that, and things might get screwed up if this gets out of step.  Along those lines, where it is now calling COPYBYTES, because i thinks it knows how to  optimize, it should really be doing COPYCHARS.

It is probably also a mistake for Tedit files to worry about converting to 2-byte run-coded files (shifting to FF FF 0) rather than just dealing with one character at a time.  In fact, probably a mistake for the Tedit piece-table writer to worry about fat and thin.  These add complexity and probably bugs, for little gain in compaction or efficiency.

I'll note that, if the DINFO files were made before the externalformat changes, then this smashing problem was inherited from pre-history.

This is probably the source of smashed files, but it probably isn't the source of smashed string space.

A further note:  I think the general charset set up is also badly designed.  File devices and image streams both seem to have CHARSET functions, but I think they are only relevant for the XCCS run-code optimization (e.g. they know about the NSCHARSETSHIFT).  Maybe this should be a separate issue.

**Comment by rmkaplan** [comment]
As mentioned in our meeting, I think the NS charset shifts in TEDIT-formatted files are there so that the content portion of the file can be seen as a plaintext (XCCS) file.  The binary information about formatting is stored at the end of the file (I think Bravo did it that way too).

But the code in some cases doesn't properly recognize those shifts when the file is read back in.  The fix, in my reworked version of Tedit, is to strip those out of the pieces when the file is read in.  They can/will be reprinted when the internal file representation is printed back out to a file.

Since there are lots of non CS-0 characters in the man pages, you might wonder why we don't see this all the time.  There is inner-loop code in TEDIT to skip these NS shift sequences when it runs into them.  That seems to work pretty well in lots of cases.  So what's special about the cases where it fails?  At least in the example I have looked at in detail ("man foo"), there is an interaction with another aspect of TEDIT's low-level file-byte handling.  For this example, the character shift sequence happens around a 512-byte file-buffer boundary, where some of the bytes are in one buffer and some in the next, and TEDIT was not keeping its internal pointers consistent with the underlying buffer change.

I would still like to see other examples--send me the man search keys when you run across them.

**Comment by masinter** [comment]
many duplicates; converge all on #405
