### ISSUE TITLE
TEDIT: scrolling when the window is partially off screen

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#669]
This has been a long-standing goofiness:  if the bottom of a TEDIT window has been moved so that it is partially off screen, then scrolling produces a garbage display, that is fixed by redisplaying.

TEDIT has its own complicated scrolling function, \TEDIT.SCROLLFN, probably trying to optimize for how much drawing actually gets done.

It seems that I get much better (i.e. correct) behavior if I simply replace TEDIT's special function by the generic SCROLLBYREPAINTFN, which is used by most other applications.

But I don't know whether that is suboptimal in some other way, for example, maybe scrolling a really large file will have to redraw the whole file, not just the part in the clipping region.

Does anybody know or have a guess as to why John rolled his own?

**Comment by rmkaplan** [comment]
More playing around.  TEDIT apparently only draws what is in the clipping region, so scrolling by repainting actually doesn't cause new lines to be drawn.  So, apparently no easy fix.

**Comment by masinter** [comment]
I'd vote for leaving the "goofy" behavior -- it's rare, correctable by the user (Redisplay) and any changes have a significant chance of introducing anomalous behavior in other circumstances.

We have lots of UI issues -- i'd mark this as not just "won't fix" but "don't fix".

**Comment by rmkaplan** [comment]
Happens to me all the time

**Comment by masinter** [comment]
ADVISE(\TEDIT.SCROLLFN :AFTER (\TEDIT.REPAINTFN W]
seems to work for me

**Comment by rmkaplan** [comment]
Works for me too.  I'm putting it at the end of \TEDIT.SCROLLFN, just when the windowregion is not entirely on screen
