### ISSUE TITLE
Maiko/Medley on Raspi4 workaround

### ISSUE THREAD

**Issue by drmpwagner** [Interlisp/medley#67]
/* When trying to get maiko to compile on Raspi4 with the following: */

unzip maiko-master,zip
unzip medley-master.zip
mv maiko-master maiko
mv medley-master medley
PATH=$PATH:/home/pi/medley/bin:/home/pi/maiko/bin
sudo apt-get install clang
sudo apt-get install make
sudo apt-get install libx11-dev
cd maiko/bin 
makeright x

/* leads to an error in time.c regarding F_SETSIG */

/* adding the following before the first #include in the whole time.c file ! fixes the problem */
#define _GNU_SOURCE

/* This is of course a crude workaround that only works locally on Raspberry OS and maybe Debian in general */
/* it makes maiko compile and medley work on a Raspberry Pi */

/* someone more knowledgeable then me might want to fix this once and for all*/

/* PS: I am thrilled that InterLisp D is open source! Thank you all! */

**Comment by masinter** [comment]
I'm going to put this on the Medley Wiki and edit it there

**Comment by waywardmonkeys** [comment]
This was fixed in the code a week ago in interlisp/maiko#104.

**Comment by waywardmonkeys** [comment]
This issue was also duplicated as #97, which is already marked as fixed.
