### ISSUE TITLE
release/docker build glitches

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#676]
testLogin succeeds but both docker builds fail at login.
The maiko and medley builds create a "draft" release -- I've been manually making them public after checking them.
I use the "Automatic" show what's changed, which works for maiko, but for medley it goes all the way back a year to the last release that started with v. for some reason (rather than the last public release).

_Originally posted by @masinter in https://github.com/Interlisp/medley/issues/675#issuecomment-1037363779_

**Comment by fghalasz** [comment]
Login issues for buildDocker fixed in PR#677.  Sorry about that, I got a bit mixed up with docker namespaces vs docker usernames.  Unclear docs but also probably just inattention on my part.
