### ISSUE TITLE
Landing page has lots of random stuff if you scroll down

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#682]
A bunch of one or 2 line messages, each with an OK and a HELP button.  The messages may be useful, but why have the buttons?

**Comment by masinter** [comment]
you need to be more specific... "landing page" where?

**Comment by rmkaplan** [comment]
online.interlisp.org

**Comment by nbriggs** [comment]
All of the black question marks, which if you hover over, just put up a larger question mark.

**Comment by masinter** [comment]
Bizzare -- i've tried it with 3 browsers on windows 10 (edge, firefox, chrome) and 3 on a Mac --

Safari 13.1 gives a popup saying the browser is too old. I've tried it running in "private" mode also (no cookies retained). In no case do I see question marks, or a dialog with "OK".
@nbriggs @rmkaplan 
Please identify browser, browser version, OS, and, if possible, provide a screen snap

**Comment by nbriggs** [comment]
The first one you encounter is next to the "login as guest" button -- Chrome Version 98.0.4758.102 (Official Build) (x86_64) on macOS 10.11.6

![image](https://user-images.githubusercontent.com/8138841/154735422-346188da-5fb4-4304-b09d-358194d55c26.png)

**Comment by nbriggs** [comment]
![image](https://user-images.githubusercontent.com/8138841/154735910-180aa1b3-c051-444f-b51e-bcb16d819f1a.png)

Chrome Version 98.0.4758.102 on macOS.

**Comment by masinter** [comment]
@nbriggs are you by chance running a pop-up blocker? 

![image](https://user-images.githubusercontent.com/1116587/154737569-3e9f320e-301a-4a7c-8bf2-de882842487b.png)

**Comment by fghalasz** [comment]
I see I've completely failed as a ui designer.  The "black circle with ?" are meant to be help badges.  If you click on them a help dialog box should appear - in this case telling you what it means to login as guest.  There are a few such help badges on the main page as well.

Just tested on Windows browsers:  worked fine on Chrome(98) and on Edge(98).  On Firefox(97), presentation was OK, but clicking on the badge did nothing.  Will have to track that down.

I will fire up my Mac and see what the story is with Safari.

Also, if the received wisdom of the crowd is that these badge are just too confusing, I can take them out.

**Comment by masinter** [comment]
@nbriggs sorry, I see now.
But I'm still  puzzled by the original issue
> from @rmkaplan 
> A bunch of one or 2 line messages, each with an OK and a HELP button. The messages may be useful, but why have the buttons?

**Comment by fghalasz** [comment]
Ok.  I think I see the issue.  I use the <dialog> element and dialog.showModal() for all my pop ups.  But turns out that Safari doesn't support <dialog> until version 15.4 (same with Firefox before version 98).  What you are seeing in Safari is the content of the dialog boxes just appended to the end of the page.

I will fix using a polyfill which the chrome folks have provided to solve just this issue.

**Comment by rmkaplan** [comment]
I have 15.2, so that’s probably it.  Apple isn’t showing me a later update.

**Comment by fghalasz** [comment]
I think Nick's issue with a big ? hover is another issue.  Here is what I get on all browsers on Windows.   All the CSS does is set cursor=help.  So is this an issue of the Help cursor on MacOS?

![Screenshot 2022-02-18 103819](https://user-images.githubusercontent.com/1251539/154743969-7fe8577a-ec0d-4a80-9a2f-5e605561e04f.png)

**Comment by nbriggs** [comment]
Could be the macOS help cursor -- looks like this:
![Q-cursor](https://user-images.githubusercontent.com/8138841/154751457-263eb0d7-0507-4529-b103-718ddaa3cb79.png)

**Comment by nbriggs** [comment]
I guess I expected a tooltip such as you'd get on hovering over something clickable, such as this -- 
![image](https://user-images.githubusercontent.com/8138841/154752710-7b3feed3-0dd5-48ee-bf86-a7af6d809d46.png)

**Comment by fghalasz** [comment]
@nbriggs,  that's a lot more work than the single line of CSS I used.  But I'll put it on the todo queue.

**Comment by fghalasz** [comment]
I didn't say it was hard - only that it was more work than the single line of CSS.

But then again, **nothing** in HTML5/CSS is trivial or even almost trivial - too much complexity, too many unexpected interactions and too many browser incompatibilities to make anything trivial.

**Comment by masinter** [comment]
> I didn't say it was hard - only that it was more work than the single line of CSS.
> 
> But then again, **nothing** in HTML5/CSS is trivial or even almost trivial - too much complexity, too many unexpected interactions and too many browser incompatibilities to make anything trivial.

Just like Interlisp / Common Lisp -- strong emphasis on backward compatibility (old programs / web pages must continue to work) at the same time, overwhelming pressure to add new features to support new applications.   Result: enormous "balls of mud".  Every feature is a millstone.

I've tried to write some of these things down without a lot of uptake:

https://www.w3.org/2001/tag/2011/12/evolution/
https://docs.google.com/document/d/1T0DRIZGX7Kh52u_S7at6Yeb-TiCGL3pmknr1XaVEx3s/edit#heading=h.1ci93xb

**Comment by fghalasz** [comment]
Original issue "landing page has lots of stuff..." fixed in PR#6 (in interlisp/online).  Now live.

Will create new issue for tooltip issue.

**Comment by rmkaplan** [comment]
This is much better, also now with Safari 15.3.

Now there is the quite reasonable pop up that warns that files may be deleted, you should use sftp to save them someplace else.  But, how do I do that?  Can I do that within Medley (a shell command) or do I have to get at it some other way?  Where are the files I might want to save?

On the starting page, under advanced, you can click to start an xterm and sftp, but my impression is that that is an alternative to starting Interlisp.  And it has a heading about transferring something to notecards online, with a port, my username...and my password.  If I start up that way, I haven't seen how to then get back to Interlisp, other than by reconnecting..

It would also be useful to have a note that says what you have to do to get rid of your sysout, to release resources before they are reaped.  (IL:LOGOUT T) ?
