### ISSUE TITLE
Infinite loop printing error

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#689]
some errors seem to print to NIL (*STANDARD-OUTPUT*) instead of T (the "terminal"). Need to test but following history (attached) [HISTORY.TXT](https://github.com/Interlisp/medley/files/8106450/HISTORY.TXT) the problem.  The Device error caused a device error trying to break.

Also (while trying to track this down):

Call to (SHOULDNT) in UTF8.INCCODEFN

![image](https://user-images.githubusercontent.com/1116587/154893551-38882991-df5e-4ae1-a2cd-efb8f66f021c.png)

**Comment by rmkaplan** [comment]
UTF8.INCCODEFN doesn’t call SHOULDNT directly.  If this happens again, can you show BT! to see the \ functions?

It does call error when it sees an invalid UTF8 byte sequence. Otherwise, the SHOULDN’T may be coming from underneath, from the device op or stream op for \PEEKBIN or \BIN

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/155003709-f8505544-5562-41da-85fa-041eed29caf0.png)

**Comment by masinter** [comment]
I think /dev/tty is probably read only
![image](https://user-images.githubusercontent.com/1116587/155004300-100a4502-7144-441e-ac57-30355d25f418.png)
can't LOGOUT) without an error
under pengwin (ubuntu-based) linux WSL on Windows 10

**Comment by nbriggs** [comment]
@masinter I think you mean "write only" -- you can certainly write it, but you can't read it.

**Comment by masinter** [comment]
I'll close this without a more compelling example 
Trying with {unix}/dev/stdout

**Comment by nbriggs** [comment]
{unix}/dev/stdout should work fine for output.   You can also do things like
```
lde </var/tmp/utf8.txt
```
and then `(OPENSTREAM "{dsk}/dev/stdin" 'INPUT 'OLD)` and read from the resulting stream.   If the file contains UTF-8 encoded characters it'll do some approximation of the right thing --
![image](https://user-images.githubusercontent.com/8138841/155048145-672ebd29-991d-4191-a3a3-e7917c4acf8f.png)
from
![image](https://user-images.githubusercontent.com/8138841/155048205-755db0d8-29a0-4672-82b6-1720d9894bae.png)

where the file contained <option>a <option>b <option>c <option>d (mac keyboard) entered in Textedit and saved as UTF-8 plain text file.
You won't get what you expect, though, if you're trying to read from the terminal (/dev/stdin not connected to a file) unless the shell is cooperating on the UTF-8 encoded input.   As you saw with /dev/ttyin, you actually read `<esc>z` when you typed `<option>z` (or `<alt-graph>z` or whatever the Windows/WSL calls it) -- the same thing happens on macOS:

![image](https://user-images.githubusercontent.com/8138841/155049659-c3a21ab2-4b97-4b70-a4bc-0ec6a8cbc48a.png)

from typing `(<option>a <option>b <option>c <option>d)` at the shell where I started lde (the characters echo as they are read `^[a`, and escape is indeed `<ctrl>[`, character 27.

**Comment by rmkaplan** [comment]
If you set the external format to :UTF-8 you should see the characters mapped over to XCCS
