### ISSUE TITLE
Online should be clearer about Interlisp vs. Common Lisp in startup

### ISSUE THREAD

**Issue by Bharath-KKB** [Interlisp/medley#690]
**Font related functions missing**
Some functions that are explained in medley-primer.pdf like FONTSET, FONTPROFILE, CREATEW, PP are missing

**To Reproduce**
1. type (FONTSET 'BIGGER)
2. system responds with undefined car of form FONT....
3. similar results with CREATEW/PP etc. 

**Expected behavior**
I thought the medley-primer has basic functions which will work as is. Infact i see the definitions in the sources.

**Screenshots**

**Context (please complete the following information):**
 - OS: Linux/online docker
 - OS Version: Linux Debian 11 for local install/ Chrome on Windows 10 for online setup
 - Host arch: x86_64/dont know for online
 - Maiko version: [maiko-220117-5eba2c3a](https://github.com/Interlisp/maiko/releases/tag/maiko-220117-5eba2c3a) for local setup
 - IL:MAKESYSDATE: [ "19-Feb-2022 04:38:48" for local setupdate /"11-Feb-2022 23:06-42" for online version ]

**Additional context**
None

**Comment by masinter** [comment]
If the screen is big enough, we could set up two EXEC windows, one XCL and one Interlisp side by side, with the prompt window (with bigger, bold font) above both For narrow screens that can't fit side by side,  a "responsive" layout. might fit XCL and IL one above the other

**Comment by Bharath-KKB** [comment]
> Did you type it to an Interlisp exec, or to an XCL exec -- in an Interlisp exec it's spelled (FONTSET 'BIGGER) but in an XCL exec (where the default package is XCL rather than IL) it's spelled (IL:FONTSET 'IL:BIGGER). Get an Interlisp exec by using right button in the background, EXEC > Interlisp (take the default, don't roll out and take the Old-Interlisp).

Many thanks. I was using XCL which is the default. Using IL pkg as you suggested got it working.

**Comment by Bharath-KKB** [comment]
> If the screen is big enough, we could set up two EXEC windows, one XCL and one Interlisp side by side, with the prompt window (with bigger, bold font) above both For narrow screens that can't fit side by side, a "responsive" layout. might fit XCL and IL one above the other

The screen is big enough but cant get to open an EXEC window with INTERLISP. I will figure it out one day :)

**Comment by masinter** [comment]
I'm not sure anyone else has tried going through the medley primer to see what things still work and which have problems.

Back in the day, people could pick up Interlisp as a first programming experience; difficult to demonstrate.

**Comment by masinter** [comment]
I'm reopening this as a problem for first users. Thank you @Bharath-KKB for your patient reporting.

**Comment by nbriggs** [comment]
@Bharath-KKB -- Interlisp Exec:    You need a 2 or 3 button mouse, or know how to have your trackpad/buttons generate a right-mouse-button event as well as the left-mouse-button event.  Then: right-mouse-button down (and hold) in the background (the gray stipple not in any window) and you'll get a pop-up menu with EXEC as one of the items, slide the mouse pointer over that until it highlights, then slide right (it has the ► to indicate it has sub-menus) and over the "Interlisp" item (it also has sub-menus) and release the mouse button on the highlighted "Interlisp" item.   It will then prompt you to position and size the new Exec window -- left button down to freeze the top-left corner and drag out the region and then release it to set the lower-right corner.  Click in the window to give it the keyboard focus and then you can type at it.

**Comment by Bharath-KKB** [comment]
> @Bharath-KKB -- Interlisp Exec: You need a 2 or 3 button mouse, or know how to have your trackpad/buttons generate a right-mouse-button event as well as the left-mouse-button event. Then: right-mouse-button down (and hold) in the background (the gray stipple not in any window) and you'll get a pop-up menu with EXEC as one of the items, slide the mouse pointer over that until it highlights, then slide right (it has the ► to indicate it has sub-menus) and over the "Interlisp" item (it also has sub-menus) and release the mouse button on the highlighted "Interlisp" item. It will then prompt you to position and size the new Exec window -- left button down to freeze the top-left corner and drag out the region and then release it to set the lower-right corner. Click in the window to give it the keyboard focus and then you can type at it.

tried again and it worked. You need to go to the tip of the '>' to get the menu to open. This is a X-Windows issue perhaps. But thanks again

**Comment by nbriggs** [comment]
Interlisp does all its own mouse handling so X isn't involved in anything but putting the Interlisp screen into one window on the display.  It's working as intended:  the hot-spot of the cursor must leave the highlighted item anywhere over the right edge of that item (not just the arrow tip) to get the sub-menu -- it's a little easier with a mouse (which the interaction was designed for) than with a trackpad.

**Comment by masinter** [comment]
Is there a work-around using a trackpad or a magic mouse one-button we can recommend to online users?

**Comment by masinter** [comment]
or even worse, a tablet with a touchscreen

**Comment by nbriggs** [comment]
It depends on your OS options... For macOS you can set options for generating the secondary (i.e., right) click as two-finger tap, or a particular corner of the trackpad.  For the tablet you may be out of luck.  Android has no right-click per se, though that function may come through from a long-press.  Old iPads can't get to online.interlisp.org at all since their Safari is too old.

**Comment by fghalasz** [comment]
The Online main page now gives the user a choice between an Interlisp exec window or a Common Lisp (actually XCL) exec window as the initial exec when starting up Interlisp.
