### ISSUE TITLE
Maiko/Medley on Windows 10 with WSL2 workaround

### ISSUE THREAD

**Issue by drmpwagner** [Interlisp/medley#70]
/*
Maiko/Medley do not seem to run under windows using  the original WSL as described
due to the fact that the original Windows subsystem for Linux does not support _GNU_SOURCE signals
i.e. the Maiko/Medley window shows up under Xming but receives no mouse or keyboard input.
As WSL development has ceased in favour of WSL2 this will not change.

The following receipt works with WSL2 (which is a full Ubuntu running in a shared VM) 
and the free Xserver vcXserv under W10.
Its wordy so anyone unfamiliar can use it.
Using a window manager is added fro convenience as WSL2 does not come with one.

There will be more elegant ways, so please feel free to improve ...
*/

/*
 running Interlisp release Medley 3.5 on Ubuntu 20. on WSL2 on WIndows 10 1909
assuming wsl2 is the default account for ubuntu under Windows10
and the zip files have been downloaded under W10
*/
sudo apt-get install clang
sudo apt-get install make
sudo apt-get install libx11-dev
sudo apt-get install xterm

/* 
accessing Windows C drive to get the downloaded zip files,
so no need to install a browser or git-client in wsl2
*/
cd /mt/c

/* 
copy zip files to /home/wsl2/
note that the path to your Windows Download folder from wsl will be something like:
Users/<YOUR WINDOWS LOGIN NAME>/Downloads
*/
cp <PATH TO YOUR DOWNLOADS FOLDER>/maiko-master.zip /home/wsl2
cp <PATH TO YOUR DOWNLOADS FOLDER>/maiko-master.zip /home/wsl2

/* 
unzip as follows
*/
unzip maiko-master,zip
unzip medley-master.zip
mv maiko-master maiko
mv medley-master medley

/*
compile the sources - there will be some warnings
*/
cd maiko/bin
makeright x
cd

/* 
copy form architecture dependent subdrectory * below maiko to~/medley/bin 
e.g.
*/
cp maiko/linux.x86_64 medley/bin

/* 
set the PATH so that all parts are found
*/
PATH=$PATH:/home/wsl2/medley/bin:/home/wsl2/maiko/bin

/* 
wsl2 runs in a VM with its own  IP,
the W10 IP must be determined in a W10 command window using ipconfig ,..
e.g. here 168.178.192.10
set DISPLAY variable in wsl2 so the Xserver on W10 is found
*/
DISPLAY=168.178.192.10:0 

/* 
on W10 vcXserv a free Xserver should be installed, e.g. from the store
and should be started in a W10 command window without authentication, e.g. 
vcxserv -ac
it will create a large window under W10 where all X apps will show up
use xterm as a test whether mouse and keyboard work under X
*/
xterm &

/* 
start medley with sysout
*/
cd medley
./run-medley -xfull35

/* 
to use the full window size one might want to use a window manager in wsl2
e.g. xfce4
select lightdm when asked
*/
sudo apt-get install xfce4

/* 
once the Xserver runs on W10 and the DISPLAY is set in Ubuntu
start the windows manager
*/
startxfce4

/* 
start medley to fit on a Full-HD screen
*/
./run-medley -xfull35 -geom 1920x1080 -sc 1900x1024

/* enjoy Medley full size ;-) */

**Comment by masinter** [comment]
I think this is covered by the Medley/readme and the medley/intro. If not please reopen the issue (or send a PR) 😄

**Comment by masinter** [comment]
I think this kind of walkthrough is valuable and we should have more, and medley-intro seems better than the README

**Comment by masinter** [comment]
moved to https://github.com/Interlisp/medley/wiki/Maiko-Medley-on-Windows-10-with-WSL2-workaround
