### ISSUE TITLE
An updated version of Online is now live

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#707]
Major changes include:

1.  Notecards.online is now merged into online.interlisp.org.  If you navigate to https://notecards.online, you will get a Notecards-centric version of the online.interlisp.org experience.   Registration is in common for the two "sites" - and is the existing online.interlisp.org registration. 

2.  A web-based File Manager has been added which can be used to upload & download files and folders to/from your online home directory (i.e., dsk/home/medley/ when Online Interlisp is running).   No need anymore for a separate SFTP app.  Access to the File Manager is via the noVNC control bar at the left edge of your browser window when an Interlisp (or Terminal) session is running.  Just click on the File Manager icon, which will be the top icon on the control bar (see image).   The File Manager will open in a separate browser tab.
![Screenshot 2022-02-27 125410](https://user-images.githubusercontent.com/1251539/155900477-5877343c-06fe-4236-98fb-eb4755275d85.png)

3.  Starting up an SFTP Server when starting an Interlisp (or  Terminal) session is now optional - using a checkbox in the Advanced Options section of the main menu page.  The SFTP route is much more efficient for large upload/downloads than the new File Manager so you may still want to use it occasionally. 

4.  Added an option to have a custom ONLINE-INIT loaded instead of the standard ONLINE-INIT that's included in the release.  If the custom init option is checked (under Advanced Options), then online run-medley will use the ONLINE-INIT or ONLINE-INIT.LCOM that is stored in {dsk}/home/medley/il/initdir/   in your online home directory. (Note: the standard ONLINE-INIT already/still loads the file {dsk}/home/medley/il/INIT.  This custom init feature was added mainly to allow me to easily test new versions of ONLINE-INIT - but may come in handy for other purposes.)

5.  Various small UI changes including moving the donate button to the footer.

**Comment by masinter** [comment]
we should move some of the online code into medley for making it more available to users of other configurations.

Are there any links from the online web site to URLs that were in the https://interlisp.org space that is moving?
