### ISSUE TITLE
MEDLEY causes an error if the file isn't found, even if NOERROR=T

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#715]
Suppose foo is not a directory

(MEDLEYDIR "foo" NIL NIL T) returns NIL. Good

But
(MEDLEYDIR "foo" "fie" NIL T) still cause an error.  Bad

**Comment by rmkaplan** [comment]
Actually, the behavior when NOERROR is T and the file/directory exists is also not good.  It returns T instead of the path to the file.

**Comment by masinter** [comment]
should be fixed by PR #721
