### ISSUE TITLE
Online filesystem tab disappears

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#718]
Safari on a Mac.

The vnc-created tab for the local file system worked for a bit, I was able to drag a file over from my Mac desktop.  But then the tab stopped appearing.  Restarting at online.interlisp.. didn't help, restarting Safari didn't bring it back.

But the tab appeared again when I started up in Firefox.

I did not try rebooting my mac, to see if that cleared up Safari.

**Comment by fghalasz** [comment]
What version of Safari and MacOS?

I could not get a repeat of this on my Mac Mini running MacOS 11.5.2 (Big Sur) and Safari 14.1.2 with about 20 minutes of uploading, downloading and deleting files/folders.

I don't think rebooting Mac will do anything.  Did you "Quit Safari" and not just close all its windows when restarting?

Need to find a repeatable case to make any progress on this.

**Comment by rmkaplan** [comment]
Monterey 1.2.1
Safari 15.3

I Quit and restarted Safari, but did not first close its windows.

**Comment by masinter** [comment]
need to turn off pop-up blocker (at least on older macs when using safari)

**Comment by fghalasz** [comment]
Fixed in PR#11 in interlisp/online repo - added warning about popup blockers if file manager window fails to open.
