### ISSUE TITLE
file package integration of Interlisp definition of COMMANDS

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#72]
This came up in examination of @rmkaplan init's definition of "shell"

> We still have shell as a function, not a command.  I remember the reason:  commands are not well integrated into Medley.  In particularly, you can do DEFCOMMAND to install a command and use the COMMANDS filepkg command to store them.  But you can’t work with them once installed—EDITDEF/GETDEF/COPYDEF don’t work for commands.   So, something else that needs to be debugged, probably difficult because the implementation is done in terms of FUNCTIONS and MACROS which are not well integrated (e.g. PF)  into the medley development environment.  And the relevant functions seem to be in the file CMLDEFFER, which has the following legend at the top:
* "BE VERY CAREFUL CHANGING ANYTHING IN THIS FILE!!!  It is heavily self-referential and thick with bootstrapping problems.  All but the most trivial changes (and some of those) are very tricky to make without blowing yourself out of the water...  You have been warned."

**Comment by rmkaplan** [comment]
I tracked this down a little bit.  The various definitions (COMMANDS and a bunch of other things) are strored in hasharrays inside IL:*DEFINITION-HASH-TABLE*.  When a command is defined, it properly appears in the COMMANDS table, and GETDEF etc. work properly.

The problem seems to be that those hashtables are getting cleared somehow as part of making the full makesys.  Not yet sure where the clearing is taking place.

But commands that are defined when running the sysout do go into that table and are accessible.

**Comment by rmkaplan** [comment]
More sleuthing:  if the file with the commands is loaded SYSLOAD, then the commands are defined but don't go into the definitions hashtable.  If the file is loaded with other ldflgs, the commands definitions are available.

So this is reasonable behavior.  It differs from the behavior of system records (SYSRECORDS) which are available as background definitions in the sysout.  That could be a separate issue--whether or not sysloaded definitions in general should be accessible in the sysout.  But I am going to mark this particular issue as closed.

**Comment by masinter** [comment]
I've been thinking we should canonicalize command definitions to be upper-case Interlisp package ...

So you can say (DEFCOMMAND who (&RES) ...) or (DEFCOMMAND "who" ...) etc. and they'll all go to (DEFCOMMAND WHO ....).

The problem  now is that if you don't know how the command was defined, GETDEF just returns NIL.

A generic canonical-name-for(name TYPE) should apply the type's canonicalizer (would work for Loops METHODS, ADVICE and other types where the 'name' has some flexibility.
