### ISSUE TITLE
Online:  separate medley directories from user LOGINHOST/DIR

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#725]
It appears that the il/ subdirectory contains all of the Medley subdirectories, and it also seems to be where the user's personal files would be kept.  Should those be split out:  a MEDLEYDIR directory separate from the default LOGINHOST/DIR directory?

The site greeting file would get the personal greeting file from the LOGINHOST/DIR.

I presume that most users don't want to see that the default location of their personal files is mxied up with all of the medley subdirectories

**Comment by masinter** [comment]
this is very odd. When I go in via xterm
![image](https://user-images.githubusercontent.com/1116587/156908448-bd1bedc0-f5e6-4129-9530-44128242910d.png)

or from medley
![image](https://user-images.githubusercontent.com/1116587/156908514-fddede1d-f6ed-4926-9895-b5924e844ea7.png)

and MEDLEYDIR is /usr/local/interlisp/medley/
![image](https://user-images.githubusercontent.com/1116587/156908623-be31c893-5a19-473e-84b6-1eeb2d779e3c.png)

**Comment by fghalasz** [comment]
A few weeks ago we moved online from V1 to V2.  In V1, the Medley release was kept in /home/medley/il along with the various files normally kept in LOGINHOST/DIR.  In V2, the Medley release is kept in /usr/local/interlisp/medley and the files normally kept in LOGINHOST/DIR are kept in /home/medley/il.

Existing accounts in V1 were converted to the V2 scheme using the following rule:  if the release Medley tree in an account's /home/medley/il directory had been changed in any way (file changed, file added, etc. using dumb byte comparison) then the changed release Medley tree was left unchanged in the account's V2 online /home/medley/il directory.  If the release Medley tree had been unchanged by the user, then the release Medley tree was removed in the account's /home/medley/il directory for V2.

Accounts created initially in V2 are always populated as Larry shows.

So if you are one of the few people who have a converted account with an unwanted release Medley tree on /home/medley/il, then just delete the unwanted files, leaving only INIT, vmem/ and sysout/ (and notefiles/ if you've played with Notecards).

(If this is a big issue, I can go thru and delete the leftover updated Medley release from all converted accounts that still have them - although this runs the danger of deleting changes that someone wants to keep.)

**Comment by fghalasz** [comment]
You can also use the Reset Home Directory button from the main page.  This will delete everything in /home/medley (not just /home/medley/il) and set up the default directories as appropriate.   Note, however, anything of import that you have kept in /home/medley or /home/medley/il will be deleted as well.
