### ISSUE TITLE
problem with fd_set arguments

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#73]
It doesn't work correctly to use an int in place of an fd_set.  The problem shows up in keyevent.c --
```
static int rfds ...
[...]
  if (select(32, (fd_set *)&rfds, NULL, (fd_set *)&efds, &SelectTimeout) >= 0)
```
Compiled with <code>-O0</code> it works, but with <code>-O2</code> it fails.

There are quite a few places where the code should be using an fd_set and the FD_xxx() macros to manipulate them.

**Comment by masinter** [comment]
I wonder if this might have something to do with the problems I was having compiling cygwin and running on WSL1.

**Comment by nbriggs** [comment]
Possible.

This should be fixed by https://github.com/Interlisp/maiko/commit/b234064d91924a86dffd3f60f96588097f9dff47
