### ISSUE TITLE
An updated version of Online is now live

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#742]
An updated version of online.interlisp.org just went live.

Changes include:

1.  Changed branding, featuring the Medley name.
2.  User can now choose between Interlisp and Common Lisp (actually XCL) as the initial Exec window when Interlisp starts up.
3.  Rearranged main page to accommodate these two changes.
4. CLIPBOARD library package now works (Meta-C, Meta-X and Meta-V copy selection to clipboard).  You can transfer clippings between Medley and your home system (where the browser is running) via the clipboard tool available thru the noVNC tool bar on the left side of the Interlisp screen.
5. Scrollwheel now works as expected.
6. A pop-up blocker notice now appears if the File Manager window fails to open correctly.
7. Many misc., mostly cosmetic, changes.

**Comment by fghalasz** [comment]
Oops. One more change:
8.  IL:ONLINEP is now set to T by the ONLINE-INIT.  You can use (AND (BOUNDP 'ONLINEP) ONLINEP) as an "am I online?" test.

**Comment by rmkaplan** [comment]
Can we set IL:ONLINEP to NIL in the non-ONLINE site greeting file?

**Comment by masinter** [comment]
I'd call it MEDLEY-ONLINEP or some such.
What are you using it for? I was hoping to minimize the differences between "online" and "installed".

**Comment by masinter** [comment]
in PR #904 medley with PR https://github.com/Interlisp/online/pull/22 ... rather than advising IDLE to LOGOUT uses the SAVEVM timeout built in.

This announcement is great and we're getting more users. So I think this issue can close.
