### ISSUE TITLE
LOGO window too close to the right edge of the screen window

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#744]
At least for online, the "y" in "Medley" is sometimes clipped.  Maybe move the logo in a few points from the screen edge?

**Comment by masinter** [comment]
not seeing this. (LOGOW) should make a new one. What happens when you call that?

**Comment by fghalasz** [comment]
Depends on screen width (and height?) in a non-linear way.

Try screen dimensions of 900x768 - you will see problem.

Try 800x768 - LOGOW will look OK (although it will be partially buried under the Exec window).

**Comment by masinter** [comment]
Let's work out what we're using the LOGOW for. As a quick way to visually see whether you're in NoteCards or Medley or something else?
I didn't fix the LOGOBITMAP for IDLE-BOUNCING-BOX.

**Comment by masinter** [comment]
I cant make this happen again... did it get fixed?

However, now PROMPTWINDOW has disappeared. I can do a (SHAPEW PROMPTWINDOW) to get it to appear again.

**Comment by masinter** [comment]
fixed in recent online release
