### ISSUE TITLE
loadup scripts reset $HOME which causes remote X connections to fail

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#756]
If you try to build a loadup when you are ssh'd (-X) in to a host... reseting $HOME causes remote X connections to fail because the system attempts to find the Xauth file in $HOME and that's now somewhere else where there is none.

**Comment by nbriggs** [comment]
Still a problem.

**Comment by masinter** [comment]
i think this is fixed. All he loadups use the -loadup option to run-medley, which doesn't reset HOME
