### ISSUE TITLE
COMPAREFILES odd display

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#760]
it looks like it's prettyprinting the comment without (* ...) around it.
![image](https://user-images.githubusercontent.com/1116587/165199186-f1230371-8ddf-43fb-890f-67436b34864c.png)

this is what it looks like in git compare

![image](https://user-images.githubusercontent.com/1116587/165198978-e4ea519d-cca5-4afb-bf4c-e5ceb48104b3.png)

**Comment by rmkaplan** [comment]
It is prettyprinting, and interpreting the comments and font characters as it goes.  The bvm comment was apparently never upgraded, that’s something that could be done when a new date comment is stuck in.

**Comment by rmkaplan** [comment]
To be more precise, the source-compare display is done by comparetext applied to Tedit files that TEDITDEF on EXAMINEDEFS produces for the definitions after they have been read from the source files, not on the original file character sequences.  TEDITDEF calls PRINTDEF.
