### ISSUE TITLE
Interlisp Online Registration Notice does not respond to 'OK'

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#767]
**Describe the bug**
When creating or (in my case) updating an Online Interlisp account, we ask for name and some addition information.  Once the user enters the information and presses OK, we bring up a message box:
![image](https://user-images.githubusercontent.com/22384842/166403530-b011b4ed-d299-49b3-ad33-8c7c9a1be70d.png)

However, pressing OK in the message box does nothing.  The window remains blocking access to Online Interlisp.

I was able to gain access to Online Interlisp via the confirmation email, the link in it took me straight to Medley.

**Comment by fghalasz** [comment]
Fixed in interlisp/online PR#18.  Now in production online.
