### ISSUE TITLE
RESOLVE-MISSING-PACKAGE problem in library-src:GAUGES

### ISSUE THREAD

**Issue by skaisler1** [Interlisp/medley#772]
Loading GAUGES source causes RESOLVE-MISSING-PACKAGE error in (@ width: ,min) naming ",min"

[Problem with RESOLVE-MISSING-PACKAGE.pdf](https://github.com/Interlisp/medley/files/8700231/Problem.with.RESOLVE-MISSING-PACKAGE.pdf)

Why is this not working? I will send file to Interlisp.org

**Comment by nbriggs** [comment]
I looked in loops/library-src/ -- there's a file called GAUGELOADER.  You should load that file and then call (LOADGAUGES) (it takes a couple of arguments, you might want to start with (LOADGAUGES 'SOURCES)).

**Comment by masinter** [comment]
[Problem with RESOLVE-MISSING-PACKAGE.pdf](https://github.com/Interlisp/medley/files/8704182/Problem.with.RESOLVE-MISSING-PACKAGE.1.pdf)

**Comment by masinter** [comment]
The loaders all seem to work loading compiled versions, and it's possible to load sources after.

in https://github.com/Interlisp/loops/pull/13
