### ISSUE TITLE
Fix up Running with Docker instructions (and implementation)

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#782]
@reflektoin thanks for your note. 

I tried this myself and was able to (re)install docker desktop for windows and, following the advice in
https://github.com/Interlisp/medley/wiki/Running-with-Docker and I had problems.

VNC uses socket 5900. X uses socket 6000.  The container has Xvnc running in it. If Medley uses the DISPLAY of the Xvnc server, then you want -p 6000:6000 (instead of 5900) and want the command line to use the DISPLAY setting to be the IP address (followed by :0) of the machine running X.  I can get this to work on the command line inside the container
```
  export DISPLAY=<ip address of X server>:0
  cd /usr/local/interlisp/medley
  ./run-medley -noscroll -dimensions=1280x720 -full
```

If you want to use VNC, that works OK if I use a VNC viewer I got from Microsoft store, but TightVNC complains about authentication or loopback.

The docker image don't pass on the screen dimensions but always use fixed 1200x720.

Running with Docker has the ability to use https://docs.docker.com/storage/volumes/ volumes to mount various volumes on the docker host, including read-only. It would be useful to include an example of mounting (in the docker run command) of mounting /mnt/c readonly the c: volume and mounting the user's "ilisp" directory as /home/medley.

Probably we will need to push some of the logic in the "online" edition into the  image.

_Originally posted by @masinter in https://github.com/Interlisp/medley/issues/765#issuecomment-1139990176_

**Comment by masinter** [comment]
Oops, I split the issue into two -- I left the original CHAT("SHELL") bug and this one on "Running with Docker" wiki page documentation.

**Comment by stumbo** [comment]
Closing - we have moved away from using Docker as a desktop method for running Medley.
