### ISSUE TITLE
prc errors

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#783]
![image](https://user-images.githubusercontent.com/1116587/170898497-8cee87b9-bf4c-42cf-930c-519005ed7703.png)

probably calling with the commit ID rather than commit name would be safer.

**Comment by rmkaplan** [comment]
Was this just a default invocation of the prc command?

I don’t see this now, it may be something that I already fixed.

What is the date of your gitfns?

**Comment by masinter** [comment]
I thought I had started with `gh pr checkout 777` and a new loadup, but when I tried it just now, I didn't get the error.
So maybe I was mistaken, will close this issue now.
