### ISSUE TITLE
Problems with conversion of all TEDIT files to PDF

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#784]
I'm collecting problem reports in one issue, running (HCFILES) from MEDLEY-UTILS.

- [ ] Loading image object definitions uses LOAD on WHEREIS for the image object function. However, these aren't the entry point and loading one file doesn't load enough. So far I've done FILESLOAD on IMTOOLS TMAX SKETCH
- [ ] Font not found SIGMA 20 Postscript. This font is necessary to print lispusers/EQUATIONEXAMPLES.TEDIT
- [ ] There is an undefined function CREATEPCNODE called by TEDIT.BUILD.PCTB1. At some point in Envos repo where this was defined in the file LISPCORE/library/PCTREE. There might already be an issue on this.
- [ ] HCFILES has a hack where it ignores files in the dinfo directory because those aren't really TEdit but some variant defined in doctools.
- [ ] What to do about other .tedit files in other repositories? (Loops, Notecards mainly)

**Comment by masinter** [comment]
Should move HCFILES to the Test repo and fit it in as an automated test of TEdit.

**Comment by masinter** [comment]
big overlap with #838 ("Getting available docs") continue with that issue

**Comment by rmkaplan** [comment]
On the LOAD/WHEREIS for imageobjecgt getfns, I noticed that it wouldn’t help in cases where the getfn of the image object was on a subsidiary file whose loading didn’t bring in everything that was needed. This could be fixed piecemeal, by moving getfns to the top-level file of an app (like SKETCH).  Or to have something other than typical WHEREIS that figures out what super-file needs to be loaded to get everything that an image object needs.  E.g. a calculation that says that if a getfn is on file X, and X is in a FILESLOAD on file Y, then assert that the whereis database says that the getfn is on both X and Y, and the image-object fall back will then know to load both of them.
