### ISSUE TITLE
need TCPOPS from envos repository

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#786]
We need to retrieve the TCPOPS file (envos/xd1d/users/sybalsky/savoir/TCPOPS) from the envos repository as it provides the stream interface to the host TCP operations that maiko implements.  It might take a little cleanup, but it's a better starting point than building from scratch.

**Comment by nbriggs** [comment]
The TCPOPS code is missing quite a few things -- it may have dependencies on code that has been removed, or perhaps code that was never written/completed.

**Comment by masinter** [comment]
I wonder if @tlipkis might know what the savoir files are .... 
```
Date: Mon, 11 Sep 89 18:50:41 PDT
From: tal@mars (Tom Lipkis)
Message-Id: <8909120150.AA22677@mars.>
To: jds@mars
Subject: SYSOUT bugs
Status: RO
```

**Comment by nbriggs** [comment]
Yeah, I noticed the Savoir copyright.   There's code in maiko that provides host tcp access through a TCP subr via an interface that gives access to essentially raw `gethostent`, `getservent`, `socket`, `accept`, `listen`, `connect`, `send`, `recv`, and `close`.   It starts to build on top of that an `OPENTCPSTREAM` implementation, but it depends on `CHARDEVICE` which seems like a suboptimal choice, and a bunch of buffered character routines that don't (and as far as I can see, have never...) exist.

If we want to provide TCP (and UDP) access using the host protocol stack I think this interface (in the maiko code) is the way to go, but then we need to build up the Lisp I/O stream structure on top of that.   I'm not sure which existing FDEV and stream structure is the best to learn from.

**Comment by tlipkis** [comment]
I don't remember doing anything with low-level networking in Medley or
predecessors at Savoir, but it's plausible John Sybalsky did, as
suggested by the filename.

None of the Savoir stuff is online in any place that I'm aware of.  I
have a box of backup tapes from that era, which might be interesting.  I
even found a matching QIC-150 tape drive in the garage, but I didn't
find the SCSI cables, terminators, interface card, etc. that would be
needed to connect it to a modern machine, and they don't appear to be
available.

**Comment by masinter** [comment]
Michele has equipment and experience recovering data from old tables; references to

http://www.tangible-technology.com/tape/baking1.html
https://www.radioworld.com/industry/baking-magnetic-recording-tape
https://arstechnica.com/science/2020/04/the-chemistry-of-why-baking-degraded-reel-to-reel-tapes-can-reverse-damage/
https://www.adventdigitizing.com/blog/bake-me-a-tape-2

**Comment by masinter** [comment]
I can't tell what source are needed and why.
Needed where?
The side conversation about Quic tapes is a separate issue.

**Comment by nbriggs** [comment]
The TCPOPS stuff was part of getting the SUBR interface to the underlying OS TCP and UDP implementation going.  We got a version of TCPOPS, but see June 4: "The TCPOPS code is missing quite a few things -- it may have dependencies on code that has been removed, or perhaps code that was never written/completed."

**Comment by masinter** [comment]
I proposed we put the TCP files back into Library and start with that set.

**Comment by masinter** [comment]
I think the "retrieve the files" has been done. Whether it is enough to recreate Medley TCP code is an open question, but #1185 was merged.
