### ISSUE TITLE
ldex on Solaris currently broken

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#82]
Starting ldex results in a "Pollable Event" message and immediate exit.
Works OK on macOS, Ubuntu, FreeBSD

**Comment by waywardmonkeys** [comment]
Is this new or has it been happening for a while?

**Comment by nbriggs** [comment]
It's new.

**Comment by nbriggs** [comment]
I'm pretty sure it's b234064d91924a86dffd3f60f96588097f9dff47   where I changed fd_set handling, and couldn't test on the Solaris box because it was offline due to network problems.

**Comment by nbriggs** [comment]
I'm breaking for dinner, but without having read the code I'd guess that I managed to turn on signals before the signal handler was setup. Probably in the ethernet code, and we only have the ethernet turned on on SunOS5.

**Comment by nbriggs** [comment]
The root cause of the problem is that <code>init_Xevent()</code> calls <code>ioctl(..., I_SETSIG, S_INPUT)</code> before the Lisp code has initialized the signal handlers.
A solution will have to wait until tomorrow.

**Comment by waywardmonkeys** [comment]
Is that even necessary anymore? On some platforms, I think the Xorg server sets up signal-based I/O correctly, but I don't really know what `ldex` is doing here. (And is your version of Solaris even using Xorg?)

**Comment by nbriggs** [comment]
It may not be necessary.  Yes, Solaris 11.4 on SPARC does use the Xorg server.  It's trying to take an interrupt for all key-press and mouse-movement events.  It's doing that on the FD for the X display socket and Xorg doesn't know anything about it.  In theory, the select() should fire and we should process the events right away anyway -- it may have been put in there before they had the select() working properly, or it may be paranoia, or it may actually get your keys a ms earlier...

**Comment by nbriggs** [comment]
Fixed by Interlisp/maiko@fe0f9fff2cfe83e90b8ef663c11a31fbde4d3a8e (PR Interlisp/maiko#78)
