### ISSUE TITLE
Problems reading older TEdit files (now in medley/docs/internal)

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#828]
I salvaged a number of TEdit and .sketch files from envos which look like important internal documentation.

But none of the TEdits we have going back to full.venuesysout can read them.
They die on CREATEPCNODE and subsequently on INSERT-BRT udf. Loading those functions from an older PCTREE doesn't work. One conjecture is that JDS was in the middle of changing the internal representation of the piece table to use B-tree algorithms, and the reading of newer format TEdit files was completed, but the reading of older version files use code that expects older data structures.
@rmkaplan suggested there might have been a difference between LISP and LISPCORE.
in history/2010s/201626-lispcore/library there are some files in a /new/ directory that differ -- in particular the /new/ files have most (but not all) calls to INSERT-BRT commented out.

**Comment by rmkaplan** [comment]
I think this has been addressed
