### ISSUE TITLE
return using 'q' from RAID gets an X error

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#835]
**Describe the bug**
returning from RAID gives X error now (didn't usedta)

**To Reproduce**

1. run medley
2. (RAID)
3. type q and then y return
4. What happened? see snap

**Expected behavior**
start up X session

**Screenshots**
![image](https://user-images.githubusercontent.com/1116587/179136372-f1214c33-0df5-4f2f-9949-bfb5b82af633.png)

I meant to try earlier maiko to see if the problem was maiko and not some problem with GWIN on Windows 10 as the X server -- got lost getting ssh -X to work.

**Context (please complete the following information):**
 - OS: [e.g. Mac/Linux/Cygwin]
 - OS Version: [e.g. High Siera/Ubuntu 18/Raspbian]
 - Host arch: [e.g. x86_64, arm7l, arm64, sparc]
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: [ date ]

**Additional context**

**Comment by nbriggs** [comment]
I don't see this on my Mac, nor do I see it when I've ssh'd -X to another system and run medley remotely.  What system is this on?  What else was going on?  Is it the latest maiko version?

**Comment by masinter** [comment]
After trying lots of different windows X servers and doing a binary search I discovered is that the problem happens with -noscroll.
If I don't supply -noscroll it works fine .

**Comment by nbriggs** [comment]
Ah, without digging in to the code, the uraid code is probably trying to do something to the scroll bar window(s) and of course that's going to be a NULL pointer when there aren't any.

**Comment by masinter** [comment]
it doesn't crash just reports an X error of a failed request BadWindow.
see screenshot above

**Comment by nbriggs** [comment]
To track down X11 errors, you need to run lde/ldex with option `-xsync` and under the debugger set a breakpoint at `_XDefaultError` (or `_XDefaultIOError` if it's an I/O error that is causing the problem) before replicating the problem.  A backtrace when at that breakpoint will show which X11 call failed and reported the error.  If you don't use `-xsync` then the problem will only be reported when the X11 library I/O buffer gets flushed to the server which will likely be after the call which actually caused the problem.
