### ISSUE TITLE
The BIGNUM declaration is not in EXPORTS.ALL

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#859]
It is defined in LLBIGNUM, used at least by TEDIT.  Should be exported

**Comment by nbriggs** [comment]
Shouldn't that code be doing `(TYPEP NEWLEN 'BIGNUM)` or `(TYPENAMEP NEWLEN 'BIGNUM)` ?

**Comment by masinter** [comment]
That was a hack I should have not introduced. Trying to HCFILES (TEdit Hardcopy) of the envos repo hit a (at the time fatal) RAID call because it was trying to PUTBASEFIXP of a BIGNUM in the middle of an UNINTERRUPTABLE section of code.

**Comment by rmkaplan** [comment]
I’l try one of those.

**Comment by masinter** [comment]
just turn it into a > 0 < max piece-length test.

**Comment by rmkaplan** [comment]
Does max-piece-length already exist?

**Comment by nbriggs** [comment]
I would check if (the error case)`NEWLEN` is < 0 or > MAX.FIXP since Larry pointed out it was
> trying to PUTBASEFIXP of a BIGNUM

**Comment by rmkaplan** [comment]
OK
