### ISSUE TITLE
maiko: Look at removing oether.c and oldeether.c

### ISSUE THREAD

**Issue by waywardmonkeys** [Interlisp/medley#88]
Can we remove `src/oether.c` (old version of `src/ether.c`) and `src/oldeether.c` (old version of `src/oldeether.c`)?

**Comment by masinter** [comment]
go for it -- looks like litter

**Comment by waywardmonkeys** [comment]
This was addressed in acc86a4df7e1ef21173f81d4d0ba57fe5687ced8
