### ISSUE TITLE
room fails

### ISSUE THREAD

**Issue by tfeb** [Interlisp/medley#888]
**Describe the bug**
`(cl:room)` fails with `NIL is not a number`.

**To Reproduce**
- run Medley, in an XCL exec say `(room)`.

**Expected behavior**
It should at least not fail.

**Context (please complete the following information):**
 - OS:Ubunto
 - OS 22.04
 - Host arch: arm64
 - Maiko version: current release?
 - IL:MAKESYSDATE: 30-Jul-2022 22:42:01

**Comment by tfeb** [comment]
Note, this is hardly urgent!

**Comment by nbriggs** [comment]
... because (IL:STORAGE.LEFT) is only returning a 3 element list instead of the 5 elements that CL:ROOM expects.  It's not clear that the DINFO documentation  for IL:STORAGE.LEFT (5 elements) is current and whether the info it suggests would be returned makes sense in current systems.

**Comment by nbriggs** [comment]
Note that (IL:STORAGE) provides much more information.

**Comment by tfeb** [comment]
@masinter thank you.  I will try this on Monday.  Pretty sure someone else should check it as my knowledge of the internals of this is zero.
