### ISSUE TITLE
Add author to FILECREATED expression

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#908]
The FILECREATED expressions contains the meta data for Lisp source and compiled file, in particular the date of creation/compilation, the previous date, and the changes.

We use the date information to set the Unix directory date, because otherwise the directory only shows the date of the download, or maybe of the commit.  The actual creation date in particular is important for the GITFNS compare.

In old file servers I think the actual author of the file was also passed along with the file, and looking at the author in a directory listing or a compare-directories listing was useful.  But now we only see as the author the user of the machine that the file is downloaded to.  The author is perhaps implicit in the FILECREATED expression, since it contains the full-file-name of the file, which typically also includes the name of the logged in user.  (Although that would disappear if we worked in the world of Medley pseudohosts.)

I propose to be more explicit:  add a :by keyword to the FILECREATED expression with either the (USERNAME) or the INITIALS at file-creation time.  Presumably that can't be installed in the Unix directory (since most users don't have accounts on most machines).  But Medley tools, like COMPAREDIRECTORIES/GITFNS can then show that information to give a little more sense of the provenance of a file.  (With the TEDIT revisions, TEDITFILES could also have that extra bit of metadata.

(For privacy, maybe we should also have a DONT setting.)

**Comment by masinter** [comment]
git can provide the name anf email address supplied by whoever did the commit.
And our online users (if they want to keep files) will have supplied name and email address.
I don't think (USERNAME) is so useful may more -- maybe we should change it to fit into modern naming.

I'd rather have the names externally derived and tracked to adapt how things worked then to how things work now.

**Comment by rmkaplan** [comment]
What name to use when you make the file is one issue.  But my point is that you want to be able to know who made the file by looking at it, not by having some record of its provenance.

**Comment by masinter** [comment]
the edited dates are ugly and hard to read, and it seems they pile up.
I like the keeping info about who edited what when, but I'm not sure it belongs at the file level or when. Initials are cute; i want to compile a list of old ones and associate with names.

**Comment by masinter** [comment]
maybe user initials -- people set those for the edit date?
I'd propose adding an EDITED-BY: <initials> field at the top.
Will that break anything having another field besides :changes-to
