### ISSUE TITLE
undefined function \CATRANSLATE in EDITCALLERS

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#925]
get left out?

**Comment by rmkaplan** [comment]
It’s a macro on IOCHAR, probably should be exported if it is used in FILEPKG.

**Comment by masinter** [comment]
My bad, something else was going on.

**Comment by rmkaplan** [comment]
But probably should be exported anyway

**Comment by masinter** [comment]
@rmkaplan you can double check if you want but I think it probably already is.
