### ISSUE TITLE
GITFNS:  Failure on "git diff --merge-base origin/master idle-patches --name-status"

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#958]
On my system:  `prc idle-patches` failed with "Command failed: git diff --merge-base origin/master idle-patches --name-status". 

Turns out that `git diff --merge-base` does not exist on the version of git I am using.  Specifically, I am running Ubuntu 20.04 LTS (on WSL2, but that's not really relevant) on which the latest git version is 2.25.1.   The --merge-base option was not introduced until git version 2.30.

Lots and lots of people in this world still running Ubuntu 20.04 LTS (despite release of 22.04 LTS in April 2022) - including online.interlisp.org.

Fix is easy (I think).  From latest git manual (version 2.37.3):

> If --merge-base is given, use the merge base of the two commits for the "before" side. **git diff --merge-base A B is equivalent to git diff $(git merge-base A B) B**

Also, we might want to document a minimum version of git needed to support GITFNS.  Also for gh, for that matter.

**Comment by rmkaplan** [comment]
Put in Frank's recommended change to the prc merge-base in git diff.  Seems to work

**Comment by fghalasz** [comment]
Fixed in PR#956 (RMK70). Closing.
