### ISSUE TITLE
HELPSYS/CLHS.INDEX fails when MEDLEYDIR not writeable (e.g, online or Linux non-dev install)

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#974]
In some installs, MEDLEYDIR is not writeable.  In these installs, CLHS.INDEX fails because it tries to create the directory <MEDLEYDIR>/tmp/clhs/ and to subsequently write the file <MEDLEYDIR>/tmp/clhs/clindex.htm.

This will happen on any install where Medley is installed into a 'global' location like /usr/local/.  Examples, online and the non-dev Ubuntu/WSL install that I am working on.

Fixing this 'right' will get us into a (long) discussion of where to put various Medley files and under what circumstances.

But for now, I think moving these 'temp' files for CLHS to /tmp or /var/tmp would fix the immediate problem. 

Biggest difference is that /tmp is (by default) cleared on reboot, while /var/tmp is not.  I am pretty sure that /var/tmp exists on all major Linux distros as well as MacOS.  Both are user writeable.

**Comment by masinter** [comment]
I made MEDLEYDIR a function to call so that you could put (MEDLEYDIR "tmp") and (MEDLEYDIR "sources") on different devices.

But in this case using {CORE} for holding the CLHS parsed index (or serving the index, parsed, on interlisp.org ). There is a question of the CLHS license restrictions, but I think they're including the Common Lisp Issues without a copyright release from the issue authors.

**Comment by fghalasz** [comment]
Not sure exactly what you are suggesting.  Do we rewrite the MEDLEYDIR function to return completely different paths depending on the DIRNAME argument - so that (MEDLEYDIR "tmp") returns "{DSK}<tmp>", but (MEDLEYDIR "sources"} returns "{DSK}<usr>local>interlisp>medley>sources".  And where do we do this rewrite - in the site INIT file or ???.

Seems it would make more sense to create a TMPDIR function that would would return a path to a directory or file in a temporary directory.  TMPDIR could use the following to determine where the temp directory is:
1. The value of the globalvar TMPDIR
2. (MEDLEYDIR "tmp") if that directory is writeable
3. /tmp (or /var/tmp) otherwise.

2&3 will cover almost all cases.  And if not, you can set TMPDIR in your site (or personal) init file to override.

Higher level functions like CLHS.INDEX who "know" they need a temp directory or file could then use (TMPDIR "clhs") instead of (MEDLEYDIR "tmp/clhs").

**Comment by nbriggs** [comment]
I'd expect it to use a file on `{CORE}` to store a temp file assuming it's not so large as to interfere with the vmem available, but if *is* likely to be largeish, then it probably could be caching it on `{unix}/tmp/clhs/...` assuming that `{unix}/tmp/...` is going to be an acceptable temporary name on basically any system we run on (perhaps not on Android on a phone).  But... it certainly shouldn't be caching anything using `(MEDLEYDIR ...)` since that is *supposed* to be the installation directory not a place to write anything.

**Comment by rmkaplan** [comment]
{TMP} could be a pseudohost that points to different things in different contexts.  At least then the intent would be passed around in the filename, without benefit of a function call, which could indirect off to the side.

**Comment by nbriggs** [comment]
Yeah, it could, assuming you have the pseudohost code loaded and it has been set up to map {TMP} to "{unix}/tmp" -- but does that really get you anything over the plain string filename with "{unix}/tmp/..."?

I think it was a mistake for the HELPSYS code to use (MEDLEYDIR ...) for temporary files at all.

The HELPSYS code already has the variable IRM.HOST&DIR, and the CLHS code already has the CLHS.ROOT.URL variable, so I don't see why the CLHS can't follow the same pattern and have CLHS.HOST&DIR and set it, if not set when HELPSYS is loaded, to "{unix}/tmp", where, if it can't find clhs.index it will cache the file.

**Comment by fghalasz** [comment]
@nbriggs {CORE} doesn't always work - as in the CLHS.INDEX case which uses ShellCommand and curl to fetch the index from a website.  Need a "real" file (at least temporarily) for curl to write into.

Also /tmp is not always ideal in the dev-install case where one could be running multiple instances of Medley - presumably each from a different MEDLEYDIR.  In this case, we either have to come up with a complicated mechanism to keep separate subdirectories in /tmp or we set the TMPDIR to be a subdir of MEDLEYDIR.

Aside from the proper location of TMPDIR, this issue is coming up now because Medley overloads the meaning of MEDLEYDIR.  It is both the install dir and the "work" dir.  In the "dev" install case that works OK.  But in the "non-dev" install case (e.g., online), the install dir is non-writeable and hence can't be the same as the work dir.  I think the conflation of install dir and work dir is endemic in Medley since it was built for the dev case, with not much thought given to the non-dev case.

**Comment by nbriggs** [comment]
Right, I forgot that it was going to use `curl` to get the file.   For the CLHS case, i'd expect plain `/tmp` to be OK *unless* two instances were trying to fetch the file at the same time... since it really is the same file it's fetching and caching.  In my opinion `MEDLEYDIR` should only ever have been the install location, and that's the way I treat it.  Anything writable (from Lisp) I expect to be in (subdirectory of) my LOGINHOST/DIR, or some specific name I'm giving it.

**Comment by fghalasz** [comment]
@nbriggs  Probably a best practice not to hardwire in a pathname (even something as quasi-universal as /tmp) in lots of places in the code.  Better to have an accessor variable or function that can be changed in one place.  

In particular, should we ever hope to support Windows directly, I don't think the "/tmp" path works there (despite the fact that it is legacy Posix).  [Never mind all of the unix we are building in everywhere else to make the Windows direct case nearly impossible.]

**Comment by nbriggs** [comment]
Re: not hardwiring -- yeah, but either way the "proper" value (for, say, `CLHS.HOST&DIR`) should be set in the site initialization file and if it's not set there it either needs a reasonable default that will work for most people or it should complain that it must be set.  It ought to be checked, too, in case someone *does* set it to a name that can't be used externally like `{core}`.

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/194728670-cdffecb7-6eec-4575-8b0a-0bfc80733578.png)
the license statement for the CLHS is very restrictive -- you may NOT create a derivative work.
I was being clever by writing a parser where the end-user was creating a derivative work for their own fair use exception.
On the other hand, they're using [my words on many issues](http://www.lispworks.com/documentation/HyperSpec/Issues/iss260_w.htm) without any release from me, so I wouldn't worry about copyright on this.

**Comment by masinter** [comment]
I haven't written any Lisp code that hardwires the location of the "tmp" directory -- the idea was to mediate all of the various medley pathnames by a call to MEDLEYDIR -- with the final path also encapsulated. For pathnames that are in DIRECTORIES lists, those get reset by (MEDLEY-INIT-VARS) which assigns directories in LISPUSERSDIRECTORIES etc., and which calls MEDLEYDIR also.

![image](https://user-images.githubusercontent.com/1116587/194729701-dde208cd-297b-4df4-aadf-5538c0862fe0.png)
![image](https://user-images.githubusercontent.com/1116587/194729789-50c1c45f-87cb-4a3f-9af6-026051eeadd6.png)


Some of the complexity might be to requirements that we don't have now -- of wanting to do loadups in sections and having each step adapt to the layout of the directories. But getting this worked out was one of the biggest chunks of time to making loadups happen.

**Comment by orcmid** [comment]
> @nbriggs 
> In particular, should we ever hope to support Windows directly, I don't think the "/tmp" path works there (despite the fact that it is legacy Posix). [Never mind all of the unix we are building in everywhere else to make the Windows direct case nearly impossible.]

In current versions of Windows, the environment variables `TMP` and `TEMP` are defined to an user-specific `temp/` folder.   This doesn't help so much for multiple-instance cases unless you can avoid collisions with temp-file naming (and the fact that instances of other applications might be doing that too).

I suggest that the work-folder idea might serve better.   There is an odd conflation with the location of binaries that can work for Windows.  With certain kinds of deployment, code can be in a folder that has subfolders (e.g., for resources) and can have working folders that are instance-writable but not globally visible.  

I'm not so clear on the POSIX influence.  Either way I agree a native Windows implementation is pretty iffy, especially if the goal were to walk and talk like a Windows application.

**Comment by masinter** [comment]
Pull request #983 resolves the original issue by just saving the index in the repo/loadup/etc.
no need for any tmp file at all.
(Except that the index might be considered a 'derivative work' or not)
