### ISSUE TITLE
Lafite "Send Mail" errors in OPENSTRINGSTREAM with invalid argument list #<IO Text Stream/...>

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#982]
I turned on Lafite in NS mode, talking to the Dodo mail server.  Attempting to send a message dies with
```
OPENSTRINGSTREAM
"STR"    #<IO Text Stream/136,10500>
"ACCESS" INPUT
```
stack trace is:
```
\ILLEGAL.ARG
OPENSTRINGSTREAM
\SENDMESSAGE.RESTARTABLE ("FORM" is the IO Text Stream)
\SENDMESSAGE ("FORM" is the IO Text Stream)
\EVALFORM (*FORM* is (\SENDMESSAGE (QUOTE #<IO Text Stream ...>) NIL NIL)
```

**Comment by nbriggs** [comment]
Well, it looks like a well-formed IO Text Stream that is being passed in, and `(TEXTSTREAMP ...)` of it is non-NIL.

**Comment by nbriggs** [comment]
The bug is actually in `\SENDMESSAGE.RESTARTABLE`, where it does
```
(SETQ EDITORRESULT
   (TEDIT (OPENSTRINGSTREAM FORM) EDITORWINDOW T ...))
```

**Comment by nbriggs** [comment]
@rmkaplan -- what's really the right thing to replace the `(TEDIT (OPENSTRINGSTREAM FORM) ...)` with?  I got further with:

```
          [SETQ EDITORRESULT (TEDIT (OR (TEXTSTREAMP FORM)
                                        (OPENSTRINGSTREAM FORM))
                                    EDITORWINDOW T (APPEND TEDITPROPS (LIST 'FONT LAFITEEDITORFONT]
```
but I'm not sure that's actually correct.

**Comment by rmkaplan** [comment]
I think

(CL:IF (STRINGP FORM)  (OPENSTREAMSTRING FORM)   FORM)

Only strings are the funny case in this legacy interface, given our transition to generally interpreting strings uniformly as file names (like atoms and paths) and not as containers of characters to be edited.

**Comment by nbriggs** [comment]
OK, I'll see if I can compile it after making that change.   I had a lot of trouble over its use of `(type? ...)`
