### ISSUE TITLE
Seeing pdf's and ps files from the file browser

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#993]
Following along on Larry's import and viewing of the commonlisp hyperspec, I think it would also be convenient to be able to show a postscript or pdf file (or some other hardcopy file format that the operating system knows about) by clicking the "See" button in the file-browser menu.

For example, if a file has a known hardcopy extension (e.g. PS, PDF), then on a mac at least this can be viewed in a separate desktop window by
     (ShellCommand "open -a Preview >native version of the filename>)

Is there a generic interface that converts Lisp file names into native host-dependent filenames (including the formatting of version numbers)--I have forgotten.

Can we set up a table of operating-system dependent commands that would generalize this?

This could all be hidden as a separate branch under the function TEDIT-SEE in TEDIT.

**Comment by masinter** [comment]
this is much harder. We might be able to use the 'dodo' networking to render Interpress files -- to simulate printing Listings (with PRETTYFILEINDEX lispusers), although if we share a dodo print server we'd need to emulate the piles of leftover printouts and occasional paper jams.

**Comment by rmkaplan** [comment]
Interpress might be nice, if we have historical documents.  But I’m more interested in having convenient access to current document formats where we don’t have the interpretation code in Lisp but they can be viewed by other tools on the system.  Even for our own documentation files for library/lispuser packages that haven’t been or can’t be coerced into Helpsys format.
